In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

import pycountry

# Get the directory where the current notebook is located
current_dir = Path.cwd()

# Define the path relative to the notebook
data_path1 = current_dir.parent / "data" / "epidemiology.csv" #This file contains the epidemiological data, including the number of cases, deaths, and recoveries for each country and date.
data_path2 = current_dir.parent / "data" / "oxford-government-response.csv" #This file contains the Oxford COVID-19 Government Response Tracker data, which includes various indicators of government responses to the pandemic, such as school closures, travel restrictions, and public information campaigns.
data_path3 = current_dir.parent / "data" / "vaccinations.csv" #This file contains vaccination data, including the number of vaccinations administered, the percentage of the population vaccinated, and the types of vaccines used in each country.
data_path4 = current_dir.parent / "data" / "daily-tests-per-thousand-people-smoothed-7-day.csv" #This file contains data on the number of daily tests per thousand people, smoothed over a 7-day period.

In [2]:
# Load the datasets
data1=pd.read_csv(data_path1) #epedemiology data
data2=pd.read_csv(data_path2) #government response data
data3=pd.read_csv(data_path3) #vaccination data
data4=pd.read_csv(data_path4) #testing data

In [3]:
#Examine the first few rows of the datasets
data1.head(2)

,date,location_key,new_confirmed,new_deceased,new_recovered,new_tested,cumulative_confirmed,cumulative_deceased,cumulative_recovered,cumulative_tested
0,2020-01-01,AD,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN
1,2020-01-02,AD,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN

In [4]:
data2.head(2)

,date,location_key,school_closing,workplace_closing,cancel_public_events,restrictions_on_gatherings,public_transport_closing,stay_at_home_requirements,restrictions_on_internal_movement,international_travel_controls,...,fiscal_measures,international_support,public_information_campaigns,testing_policy,contact_tracing,emergency_investment_in_healthcare,investment_in_vaccines,facial_coverings,vaccination_policy,stringency_index
0,2020-01-01,AD,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2020-01-02,AD,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
data3.head(2)

,date,location_key,new_persons_vaccinated,cumulative_persons_vaccinated,new_persons_fully_vaccinated,cumulative_persons_fully_vaccinated,new_vaccine_doses_administered,cumulative_vaccine_doses_administered,new_persons_vaccinated_pfizer,cumulative_persons_vaccinated_pfizer,...,new_persons_fully_vaccinated_janssen,cumulative_persons_fully_vaccinated_janssen,new_vaccine_doses_administered_janssen,cumulative_vaccine_doses_administered_janssen,new_persons_vaccinated_sinovac,total_persons_vaccinated_sinovac,new_persons_fully_vaccinated_sinovac,total_persons_fully_vaccinated_sinovac,new_vaccine_doses_administered_sinovac,total_vaccine_doses_administered_sinovac
0,2021-01-25,AD,NaN,576.0,NaN,NaN,NaN,576.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021-02-01,AD,460.0,1036.0,NaN,NaN,460.0,1036.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
data4.head(2)

,Entity,Code,Day,Daily tests per thousand people (7-day smoothed),Daily tests per thousand people (7-day smoothed) (Annotations)
0,Afghanistan,AFG,2022-02-05,0.032,NaN
1,Afghanistan,AFG,2022-02-06,0.032,NaN

In [7]:
# Filter for country codes only (leave out regional data)
# Return unique location keys for dataset 1
def get_unique_location_keys(data1):
    return list(set(data1["location_key"].dropna().str.split("_").str[0]))

unique_Country_Keys1 = get_unique_location_keys(data1)

print(unique_Country_Keys1)
print(len(unique_Country_Keys1))

['GI', 'TT', 'VN', 'DK', 'DJ', 'GU', 'IT', 'PW', 'SH', 'MZ', 'TR', 'SR', 'TM', 'SI', 'NZ', 'FJ', 'LV', 'MA', 'HU', 'KP', 'SN', 'TG', 'SE', 'KN', 'FK', 'QA', 'GY', 'SB', 'BZ', 'GL', 'LA', 'NE', 'XK', 'AT', 'GG', 'BF', 'SO', 'GM', 'KW', 'JE', 'SK', 'CZ', 'TC', 'CO', 'JO', 'BY', 'IQ', 'BD', 'MG', 'KR', 'MN', 'IN', 'AD', 'PF', 'ST', 'TW', 'NG', 'SL', 'CK', 'MK', 'BG', 'BA', 'NL', 'GW', 'LC', 'SY', 'BI', 'OM', 'FR', 'MV', 'BO', 'MW', 'RE', 'NP', 'AU', 'LR', 'NU', 'VA', 'GB', 'MO', 'GN', 'TJ', 'VI', 'FI', 'CM', 'CU', 'SA', 'MH', 'AL', 'SC', 'YE', 'MD', 'DO', 'DZ', 'IE', 'PT', 'TK', 'VU', 'BB', 'BR', 'CI', 'ET', 'CG', 'ZM', 'LU', 'CN', 'EG', 'AS', 'IL', 'GR', 'AO', 'AI', 'LI', 'CR', 'UA', 'MQ', 'US', 'CV', 'KE', 'PR', 'BN', 'NC', 'LT', 'CA', 'MP', 'KY', 'TV', 'HT', 'WS', 'KZ', 'NI', 'BJ', 'PN', 'EH', 'AE', 'PA', 'PS', 'NO', 'GH', 'PY', 'CL', 'YT', 'MX', 'KH', 'GT', 'LS', 'MS', 'LB', 'RW', 'GD', 'ZA', 'ZW', 'GF', 'BT', 'MR', 'PL', 'RU', 'JM', 'PG', 'AW', 'IR', 'EE', 'GQ', 'UY', 'CW', 'ES', 'BE', 'EC', 'FO', 'ER', 'IM', 'RO', 'SS', 'BH', 'DM', 'MY', 'MM', 'HK', 'LY', 'SX', 'VC', 'DE', 'PH', 'SV', 'PK', 'KM', 'CH', 'SD', 'ME', 'VG', 'RS', 'CD', 'FM', 'WF', 'TL', 'KI', 'UZ', 'HR', 'CF', 'TD', 'VE', 'BS', 'GE', 'HN', 'SZ', 'AF', 'MU', 'AM', 'BW', 'MC', 'PE', 'TH', 'MT', 'ID', 'SM', 'BM', 'IS', 'AR', 'ML', 'GA', 'JP', 'KG', 'TZ', 'AZ', 'SG', 'TN', 'TO', 'UG', 'NR', 'LK', 'CY', 'AG']
232

In [8]:
# Filter for country codes only (leave out regional data)
# Return unique location keys for dataset 2
def get_unique_location_keys(data2):
    return list(set(data2["location_key"].dropna().str.split("_").str[0]))

unique_Country_Keys2 = get_unique_location_keys(data2)

print(unique_Country_Keys2)
print(len(unique_Country_Keys2))

['TT', 'VN', 'DK', 'DJ', 'GU', 'IT', 'MZ', 'TR', 'SR', 'TM', 'SI', 'NZ', 'FJ', 'LV', 'MA', 'HU', 'SN', 'TG', 'SE', 'QA', 'GY', 'SB', 'BZ', 'GL', 'LA', 'NE', 'XK', 'AT', 'BF', 'SO', 'GM', 'KW', 'SK', 'CZ', 'CO', 'JO', 'BY', 'IQ', 'BD', 'MG', 'KR', 'MN', 'IN', 'AD', 'TW', 'NG', 'SL', 'BG', 'BA', 'NL', 'SY', 'BI', 'OM', 'FR', 'BO', 'MW', 'NP', 'AU', 'LR', 'GB', 'MO', 'GN', 'TJ', 'VI', 'FI', 'CM', 'CU', 'SA', 'SC', 'AL', 'YE', 'MD', 'DO', 'DZ', 'IE', 'PT', 'VU', 'BB', 'BR', 'CI', 'ET', 'CG', 'ZM', 'LU', 'CN', 'EG', 'IL', 'GR', 'AO', 'LI', 'CR', 'UA', 'US', 'CV', 'KE', 'PR', 'BN', 'LT', 'CA', 'HT', 'KZ', 'NI', 'BJ', 'AE', 'PA', 'NO', 'GH', 'PY', 'CL', 'MX', 'KH', 'GT', 'LS', 'LB', 'RW', 'GD', 'ZA', 'ZW', 'BT', 'MR', 'PL', 'RU', 'JM', 'PG', 'AW', 'IR', 'EE', 'UY', 'ES', 'BE', 'EC', 'FO', 'ER', 'RO', 'SS', 'BH', 'DM', 'MY', 'MM', 'HK', 'LY', 'DE', 'PH', 'SV', 'PK', 'KM', 'CH', 'SD', 'RS', 'CD', 'TL', 'KI', 'UZ', 'HR', 'CF', 'TD', 'VE', 'BS', 'GE', 'HN', 'SZ', 'AF', 'MU', 'BW', 'MC', 'PE', 'TH', 'MT', 'ID', 'SM', 'BM', 'IS', 'AR', 'ML', 'GA', 'JP', 'KG', 'TZ', 'AZ', 'SG', 'TN', 'TO', 'UG', 'LK', 'CY', 'PS']
186

In [ ]:
# Function to convert location_key from ISO-2 to ISO-3 format
def convert_iso2_to_iso3(location_key):
    """
    Convert a location_key from ISO-2 to ISO-3 format.
    """
    if pd.isna(location_key):
        return location_key
    
    parts = location_key.split("_")
    iso2 = parts[0]
    
    country = pycountry.countries.get(alpha_2=iso2)
    
    if country:
        parts[0] = country.alpha_3  # Replace ISO-2 with ISO-3
        return "_".join(parts)
    else:
        return location_key  # Return original if not found (e.g. 'XK' for Kosovo)

In [9]:
# Pulling out focus data from dataset 1 
# Filtering dataset to only include data by country
focus_data1 = data1[data1['location_key'].isin(unique_Country_Keys1)]
focus_data1.info()

<class 'pandas.DataFrame'>
Index: 226892 entries, 0 to 12525824
Data columns (total 10 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   date                  226892 non-null  str
 1   location_key          226892 non-null  str
 2   new_confirmed         226799 non-null  float64
 3   new_deceased          226624 non-null  float64
 4   new_recovered         15712 non-null   float64
 5   new_tested            76705 non-null   float64
 6   cumulative_confirmed  226798 non-null  float64
 7   cumulative_deceased   226625 non-null  float64
 8   cumulative_recovered  14759 non-null   float64
 9   cumulative_tested     80010 non-null   float64
dtypes: float64(8), str(2)
memory usage: 19.0 MB

In [ ]:
# Pulling out focus data from dataset 2
# Filtering dataset to only include data by country
focus_data2 = data2[data2['location_key'].isin(unique_Country_Keys2)]
focus_data2.info()

# Pulling out focus data from dataset 3 (vaccination data)
# Filter for country codes only (leave out regional data)
unique_Country_Keys3 = list(set(data3['location_key'].dropna().str.split('_').str[0]))
focus_data3 = data3[data3['location_key'].isin(unique_Country_Keys3)]
focus_data3.info()

<class 'pandas.DataFrame'>
Index: 171200 entries, 0 to 303968
Data columns (total 22 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   date                                171200 non-null  str
 1   location_key                        171200 non-null  str
 2   school_closing                      170800 non-null  float64
 3   workplace_closing                   170803 non-null  float64
 4   cancel_public_events                170785 non-null  float64
 5   restrictions_on_gatherings          170781 non-null  float64
 6   public_transport_closing            170785 non-null  float64
 7   stay_at_home_requirements           170780 non-null  float64
 8   restrictions_on_internal_movement   170765 non-null  float64
 9   international_travel_controls       170787 non-null  float64
 10  income_support                      170733 non-null  float64
 11  debt_relief                         170747 non-null  float64
 12  fiscal_measures                     105697 non-null  float64
 13  international_support               105777 non-null  float64
 14  public_information_campaigns        170791 non-null  float64
 15  testing_policy                      170767 non-null  float64
 16  contact_tracing                     170708 non-null  float64
 17  emergency_investment_in_healthcare  105659 non-null  float64
 18  investment_in_vaccines              166826 non-null  float64
 19  facial_coverings                    171036 non-null  float64
 20  vaccination_policy                  171091 non-null  float64
 21  stringency_index                    170751 non-null  float64
dtypes: float64(20), str(2)
memory usage: 30.0 MB

In [11]:
# Number of days recorded for each country in dataset 1
focus_data1_numberOfDays=focus_data1['location_key'].value_counts()
focus_data1_numberOfDays

location_key
AU    990
TH    990
AT    989
BE    989
BR    989
     ...
ZW    987
TW    974
HK    693
MO    152
EH      1
Name: count, Length: 232, dtype: int64

In [12]:
# Number of days recorded for each country in datset 2
focus_data2_numberOfDays=focus_data2['location_key'].value_counts()
focus_data2_numberOfDays

location_key
AF    938
AU    938
CL    938
HR    938
MT    938
     ...
GU    899
PS    898
CZ    881
KM    342
GD     87
Name: count, Length: 186, dtype: int64

In [13]:
#Analyzing the distribution of the number of days recorded for each country in both datasets using boxplot statistics

def boxplot_stats(series):
    q1 = series.quantile(0.25)
    median = series.quantile(0.5)
    q3 = series.quantile(0.75)
    iqr = q3 - q1

    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr

    outliers = series[(series < lower_bound) | (series > upper_bound)]

    return {
        "min": series.min(),
        "Q1": q1,
        "median": median,
        "Q3": q3,
        "max": series.max(),
        "IQR": iqr,
        "lower_bound": lower_bound,
        "upper_bound": upper_bound,
        "num_outliers": len(outliers)
    }

# Apply to both datasets
stats1 = boxplot_stats(focus_data1_numberOfDays)
stats2 = boxplot_stats(focus_data2_numberOfDays)

# Convert to DataFrame for clean display
summary = pd.DataFrame([stats1, stats2], 
                       index=["Dataset 1", "Dataset 2"])

print(summary)

           min     Q1  median     Q3  max   IQR  lower_bound  upper_bound  \
Dataset 1    1  987.0   987.0  987.0  990   0.0        987.0        987.0
Dataset 2   87  923.0   930.0  937.0  938  14.0        902.0        958.0

           num_outliers
Dataset 1            26
Dataset 2             9

In [14]:
# Using statistics to filter the data
# We will keep countries that have number of days recorded >= Q1 (first quartile)

# For dataset 1
q1_dataset1 = stats1['Q1']
# Filtering dataset to exclude data with observation numbers below Q1
filtered_countries_1 = focus_data1_numberOfDays[focus_data1_numberOfDays >= q1_dataset1].index.tolist()
filtered_focus_data1 = focus_data1[focus_data1['location_key'].isin(filtered_countries_1)]

print(f"Dataset 1 - Q1 threshold: {q1_dataset1}")
print(f"Countries kept (>= Q1): {len(filtered_countries_1)}")
print(f"Filtered data1 shape: {filtered_focus_data1.shape}")

Dataset 1 - Q1 threshold: 987.0
Countries kept (>= Q1): 228
Filtered data1 shape: (225072, 10)

# Epidemiologi_global_covid 
### - Streamlining data to include same dates

In [15]:
# For dataset 1
# Finding the first common observation date shared for all of the countries to make the comparison fair

filtered_focus_data1 = filtered_focus_data1.copy()

filtered_focus_data1['date'] = pd.to_datetime(filtered_focus_data1['date'].astype('string'), errors='coerce').dt.normalize()

min_dates_1 = filtered_focus_data1.groupby('location_key')['date'].min()
max_dates_1 = filtered_focus_data1.groupby('location_key')['date'].max()

first_common_1 = min_dates_1.max()
last_common_1 = max_dates_1.min()

print(f"First common date: {first_common_1}")
print(f"Last common date: {last_common_1}")

# Filtering the filtered_focus_data1 to only include this data interval
filtered_focus_data1_common = filtered_focus_data1[
    (filtered_focus_data1['date'] >= first_common_1) &
    (filtered_focus_data1['date'] <= last_common_1)
].copy()

print(f"filtered_focus_data1_common shape: {filtered_focus_data1_common.shape}")

# Investigate if some dates are missing for some countries. Print the dates and countries missing for the date interval

date_range = pd.date_range(start=first_common_1, end=last_common_1, freq='D')

missing_by_country_1 = {}
for country, group in filtered_focus_data1_common.groupby('location_key'):
    missing_dates = date_range.difference(pd.DatetimeIndex(group['date']))
    if len(missing_dates):
        missing_by_country_1[country] = missing_dates

if missing_by_country_1:
    print("\nMissing dates in filtered_focus_data1_common:")
    for country, missing_dates in missing_by_country_1.items():
        print(f"{country}: {len(missing_dates)} missing dates (first few: {missing_dates[:5].tolist()})")
else:
    print("\nNo missing dates found in filtered_focus_data1_common.")

First common date: 2020-01-02 00:00:00
Last common date: 2022-09-13 00:00:00
filtered_focus_data1_common shape: (224808, 10)

No missing dates found in filtered_focus_data1_common.

### - Checking for potential missing data

In [16]:
# Check that each country has at least one entity value for every data column in filtered_focus_data1_common.
# This helps verify that each country doesn't have systematic missingness.

def check_country_column_non_missing(df, country_col='location_key', threshold=1):
    """Return non-missing counts, missing-category flags, and a summary per country."""
    # Count non-missing entries per country and column
    non_missing_counts = df.groupby(country_col).apply(lambda group: group.notna().sum())
    if country_col in non_missing_counts.columns:
        non_missing_counts = non_missing_counts.drop(columns=[country_col])

    # Identify columns where the count of non-missing values is below the threshold
    missing_flags = (non_missing_counts < threshold)
    missing_matrix = missing_flags.astype(object)
    missing_matrix[missing_flags] = 'Non'
    missing_matrix[~missing_flags] = ''

    # Build a summary table and list missing categories for each country
    missing_categories = {
        country: non_missing_counts.columns[missing_flags.loc[country]].tolist()
        for country in non_missing_counts.index
    }

    summary = pd.DataFrame({
        'has_minimum_per_column': [len(categories) == 0 for categories in missing_categories.values()],
        'missing_columns': [', '.join(categories) if categories else '' for categories in missing_categories.values()]
    }, index=non_missing_counts.index)

    return non_missing_counts, missing_flags, missing_matrix, summary, missing_categories

# Run the check on filtered_focus_data1_common
non_missing_counts, missing_flags, missing_matrix, country_summary, missing_categories = check_country_column_non_missing(filtered_focus_data1_common)

print("\nSummary of missing data per category:")
missing_per_category = (missing_matrix == 'Non').sum()
print(missing_per_category)

if country_summary['has_minimum_per_column'].all():
    print("\nAll countries have at least one non-missing value in every column.")
else:
    print("\nCountries with missing entities in one or more categories:")
    for country, categories in missing_categories.items():
        if categories:
            print(f"- {country}: missing data in {', '.join(categories)}")

Summary of missing data per category:
date                      0
new_confirmed             0
new_deceased              0
new_recovered           210
new_tested               75
cumulative_confirmed      0
cumulative_deceased       0
cumulative_recovered    210
cumulative_tested        46
dtype: int64

Countries with missing entities in one or more categories:
- AD: missing data in new_recovered, new_tested, cumulative_recovered
- AE: missing data in new_recovered, cumulative_recovered
- AF: missing data in new_recovered, new_tested, cumulative_recovered
- AG: missing data in new_recovered, new_tested, cumulative_recovered
- AI: missing data in new_recovered, new_tested, cumulative_recovered
- AL: missing data in new_recovered, cumulative_recovered
- AM: missing data in new_recovered, cumulative_recovered
- AO: missing data in new_recovered, cumulative_recovered
- AR: missing data in new_recovered, cumulative_recovered
- AS: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- AW: missing data in new_recovered, cumulative_recovered
- AZ: missing data in new_recovered, cumulative_recovered
- BA: missing data in new_recovered, cumulative_recovered
- BB: missing data in new_recovered, cumulative_recovered
- BD: missing data in new_recovered, cumulative_recovered
- BE: missing data in new_recovered, cumulative_recovered
- BF: missing data in new_recovered, cumulative_recovered
- BG: missing data in new_recovered, cumulative_recovered
- BH: missing data in new_recovered, cumulative_recovered
- BI: missing data in new_recovered, cumulative_recovered
- BJ: missing data in new_recovered, new_tested, cumulative_recovered
- BM: missing data in new_recovered, cumulative_recovered
- BN: missing data in new_recovered, cumulative_recovered
- BO: missing data in new_recovered, cumulative_recovered
- BS: missing data in new_recovered, cumulative_recovered
- BT: missing data in new_recovered, cumulative_recovered
- BW: missing data in new_recovered, cumulative_recovered
- BY: missing data in new_recovered, cumulative_recovered
- BZ: missing data in new_recovered, cumulative_recovered
- CA: missing data in new_recovered, cumulative_recovered
- CD: missing data in new_recovered, new_tested, cumulative_recovered
- CF: missing data in new_recovered, new_tested, cumulative_recovered
- CG: missing data in new_recovered, new_tested, cumulative_recovered
- CH: missing data in new_recovered, cumulative_recovered
- CI: missing data in new_recovered, cumulative_recovered
- CK: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- CM: missing data in new_recovered, new_tested, cumulative_recovered
- CN: missing data in new_tested
- CR: missing data in new_recovered, cumulative_recovered
- CU: missing data in new_recovered, cumulative_recovered
- CV: missing data in new_recovered, cumulative_recovered, cumulative_tested
- CW: missing data in new_recovered, cumulative_recovered
- CY: missing data in new_recovered, cumulative_recovered
- DE: missing data in new_recovered, new_tested, cumulative_recovered
- DJ: missing data in new_recovered, cumulative_recovered
- DK: missing data in new_recovered, cumulative_recovered
- DM: missing data in new_recovered, cumulative_recovered
- DO: missing data in new_recovered, cumulative_recovered
- DZ: missing data in new_recovered, new_tested, cumulative_recovered
- EC: missing data in new_recovered, cumulative_recovered
- EE: missing data in new_recovered, cumulative_recovered
- EG: missing data in new_recovered, new_tested, cumulative_recovered
- ER: missing data in new_recovered, new_tested, cumulative_recovered
- ES: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- ET: missing data in new_recovered, cumulative_recovered
- FI: missing data in new_recovered, cumulative_recovered
- FJ: missing data in new_recovered, cumulative_recovered
- FK: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- FM: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- FO: missing data in new_recovered, cumulative_recovered
- GA: missing data in new_recovered, cumulative_recovered
- GB: missing data in new_recovered, cumulative_recovered
- GD: missing data in new_recovered, cumulative_recovered
- GE: missing data in new_recovered, cumulative_recovered
- GF: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- GG: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- GH: missing data in new_recovered, cumulative_recovered
- GI: missing data in new_recovered, cumulative_recovered
- GL: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- GM: missing data in new_recovered, new_tested, cumulative_recovered
- GN: missing data in new_recovered, new_tested, cumulative_recovered
- GQ: missing data in new_recovered, cumulative_recovered
- GR: missing data in new_recovered, cumulative_recovered
- GT: missing data in new_recovered, cumulative_recovered
- GU: missing data in new_recovered, cumulative_recovered
- GW: missing data in new_recovered, cumulative_recovered
- GY: missing data in new_recovered, new_tested, cumulative_recovered
- HN: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- HR: missing data in new_recovered, cumulative_recovered
- HT: missing data in new_recovered, cumulative_recovered
- HU: missing data in new_recovered, cumulative_recovered
- IE: missing data in new_recovered, cumulative_recovered
- IL: missing data in new_recovered, cumulative_recovered
- IM: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- IN: missing data in new_recovered, cumulative_recovered
- IQ: missing data in new_recovered, cumulative_recovered
- IR: missing data in new_recovered, cumulative_recovered
- IS: missing data in new_recovered, cumulative_recovered
- JE: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- JM: missing data in new_recovered, cumulative_recovered
- JO: missing data in new_recovered, cumulative_recovered
- JP: missing data in new_recovered, cumulative_recovered
- KE: missing data in new_recovered, cumulative_recovered
- KG: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- KH: missing data in new_recovered, cumulative_recovered
- KI: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- KM: missing data in new_recovered, new_tested, cumulative_recovered
- KN: missing data in new_recovered, cumulative_recovered
- KP: missing data in new_recovered, cumulative_recovered
- KR: missing data in new_recovered, cumulative_recovered
- KW: missing data in new_recovered, cumulative_recovered
- KY: missing data in new_recovered, cumulative_recovered
- KZ: missing data in new_recovered, cumulative_recovered
- LA: missing data in new_recovered, cumulative_recovered
- LB: missing data in new_recovered, cumulative_recovered
- LC: missing data in new_recovered, cumulative_recovered
- LK: missing data in new_recovered, cumulative_recovered
- LR: missing data in new_recovered, new_tested, cumulative_recovered
- LS: missing data in new_recovered, cumulative_recovered
- LT: missing data in new_recovered, cumulative_recovered
- LU: missing data in new_recovered, cumulative_recovered
- LV: missing data in new_recovered, cumulative_recovered
- LY: missing data in new_recovered, cumulative_recovered, cumulative_tested
- MA: missing data in new_recovered, cumulative_recovered
- MC: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- MD: missing data in new_recovered, cumulative_recovered, cumulative_tested
- ME: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- MG: missing data in new_recovered, cumulative_recovered
- MH: missing data in new_recovered, cumulative_recovered
- MK: missing data in new_recovered, cumulative_recovered
- ML: missing data in new_recovered, cumulative_recovered
- MM: missing data in new_recovered, cumulative_recovered
- MN: missing data in new_recovered, cumulative_recovered
- MP: missing data in new_recovered, cumulative_recovered
- MQ: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- MR: missing data in new_recovered, cumulative_recovered
- MS: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- MT: missing data in new_recovered, cumulative_recovered
- MU: missing data in new_recovered, new_tested, cumulative_recovered
- MV: missing data in new_recovered, cumulative_recovered
- MW: missing data in new_recovered, cumulative_recovered
- MX: missing data in new_recovered, cumulative_recovered
- MZ: missing data in new_recovered, cumulative_recovered
- NC: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- NE: missing data in new_recovered, cumulative_recovered
- NG: missing data in new_recovered, cumulative_recovered
- NI: missing data in new_recovered, new_tested, cumulative_recovered
- NL: missing data in new_recovered, cumulative_recovered
- NO: missing data in new_recovered, cumulative_recovered
- NP: missing data in new_recovered, cumulative_recovered
- NR: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- NU: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- NZ: missing data in new_recovered, cumulative_recovered
- OM: missing data in new_recovered, new_tested, cumulative_recovered
- PA: missing data in new_recovered, cumulative_recovered
- PE: missing data in new_recovered, new_tested, cumulative_recovered
- PF: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- PG: missing data in new_recovered, new_tested, cumulative_recovered
- PK: missing data in new_recovered, cumulative_recovered
- PL: missing data in new_recovered, cumulative_recovered
- PN: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- PR: missing data in new_recovered, cumulative_recovered
- PS: missing data in new_recovered, cumulative_recovered, cumulative_tested
- PW: missing data in new_recovered, new_tested, cumulative_recovered
- PY: missing data in new_recovered, cumulative_recovered
- QA: missing data in new_recovered, cumulative_recovered
- RE: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- RO: missing data in new_tested
- RS: missing data in new_recovered, cumulative_recovered
- RU: missing data in new_recovered, cumulative_recovered
- RW: missing data in new_recovered, cumulative_recovered
- SA: missing data in new_recovered, cumulative_recovered
- SB: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- SC: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- SD: missing data in new_recovered, new_tested, cumulative_recovered
- SE: missing data in new_recovered, cumulative_recovered
- SG: missing data in new_recovered, cumulative_recovered, cumulative_tested
- SH: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- SK: missing data in new_recovered, cumulative_recovered
- SL: missing data in new_recovered, cumulative_recovered
- SM: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- SN: missing data in new_recovered, cumulative_recovered
- SO: missing data in new_recovered, new_tested, cumulative_recovered
- SR: missing data in new_recovered, cumulative_recovered
- SS: missing data in new_recovered, cumulative_recovered
- ST: missing data in new_recovered, cumulative_recovered
- SV: missing data in new_recovered, cumulative_recovered
- SX: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- SY: missing data in new_recovered, new_tested, cumulative_recovered
- SZ: missing data in new_recovered, cumulative_recovered
- TC: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- TD: missing data in new_recovered, new_tested, cumulative_recovered
- TG: missing data in new_recovered, cumulative_recovered
- TJ: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- TK: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- TL: missing data in new_recovered, cumulative_recovered
- TM: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- TN: missing data in new_recovered, cumulative_recovered
- TO: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- TR: missing data in new_recovered, cumulative_recovered
- TT: missing data in new_recovered, cumulative_recovered
- TV: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- TZ: missing data in new_recovered, new_tested, cumulative_recovered
- UG: missing data in new_recovered, cumulative_recovered
- US: missing data in new_recovered, cumulative_recovered
- UY: missing data in new_recovered, cumulative_recovered
- UZ: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- VA: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- VC: missing data in new_recovered, cumulative_recovered
- VE: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- VG: missing data in new_recovered, new_tested, cumulative_recovered
- VI: missing data in new_recovered, cumulative_recovered
- VN: missing data in new_recovered, cumulative_recovered
- VU: missing data in new_recovered, new_tested, cumulative_recovered
- WF: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- WS: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- XK: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- YE: missing data in new_recovered, new_tested, cumulative_recovered
- YT: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- ZA: missing data in new_recovered, cumulative_recovered
- ZM: missing data in new_recovered, cumulative_recovered
- ZW: missing data in new_recovered, cumulative_recovered

In [33]:
# Function to remove 'new_recovered' and 'cumulative_recovered' columns from the dataframe
def remove_recovered_columns(df):
    """
    Remove 'new_recovered' and 'cumulative_recovered' columns if they exist in the dataframe.
    """
    columns_to_remove = ['new_recovered', 'cumulative_recovered']
    df = df.drop(columns=[col for col in columns_to_remove if col in df.columns], errors='ignore')
    return df

# Apply the function to filtered_focus_data1_common
filtered_focus_data1_common = remove_recovered_columns(filtered_focus_data1_common)

print(f"After removing columns with too few datapoints, shape: {filtered_focus_data1_common.shape}")
print("Columns remaining:", list(filtered_focus_data1_common.columns))

After removing columns with too few datapoints, shape: (224808, 8)
Columns remaining: ['date', 'location_key', 'new_confirmed', 'new_deceased', 'new_tested', 'cumulative_confirmed', 'cumulative_deceased', 'cumulative_tested']

### - Saving the cleaned dataset

In [35]:
#Saving this filterede data for data 1 as a CSV file
output_path = current_dir.parent / 'data' / 'epidemiologi_global_covid_data.csv'
filtered_focus_data1_common.to_csv(output_path, index=False)
print(f"\nSaved merged dataset to: {output_path}")

filtered_focus_data1_common.head()

Saved merged dataset to: c:\Users\Lenovo\OneDrive - Danmarks Tekniske Universitet\02806 Social data analysis and visualization\final_project\data\epidemiologi_global_covid_data.csv

,date,location_key,new_confirmed,new_deceased,new_tested,cumulative_confirmed,cumulative_deceased,cumulative_tested
1,2020-01-02,AD,0.0,0.0,NaN,0.0,0.0,NaN
2,2020-01-03,AD,0.0,0.0,NaN,0.0,0.0,NaN
3,2020-01-04,AD,0.0,0.0,NaN,0.0,0.0,NaN
4,2020-01-05,AD,0.0,0.0,NaN,0.0,0.0,NaN
5,2020-01-06,AD,0.0,0.0,NaN,0.0,0.0,NaN

# Merged data (Dataset 1 and Dataset 2) 
### - Streamlining data to include same dates

In [19]:
# Selecting focus countries for deep dive analysis
focus_countries = ['DNK', 'DEU', 'GBR']

In [ ]:
# Apply the convert_iso2_to_iso3 function to all datasets
focus_data1["location_key"] = focus_data1["location_key"].apply(convert_iso2_to_iso3)
focus_data2["location_key"] = focus_data2["location_key"].apply(convert_iso2_to_iso3)
focus_data3["location_key"] = focus_data3["location_key"].apply(convert_iso2_to_iso3)

In [21]:
focus_data1.head(2)

,date,location_key,new_confirmed,new_deceased,new_recovered,new_tested,cumulative_confirmed,cumulative_deceased,cumulative_recovered,cumulative_tested
0,2020-01-01,AND,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN
1,2020-01-02,AND,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN

In [22]:
focus_data2.head(2)

,date,location_key,school_closing,workplace_closing,cancel_public_events,restrictions_on_gatherings,public_transport_closing,stay_at_home_requirements,restrictions_on_internal_movement,international_travel_controls,...,fiscal_measures,international_support,public_information_campaigns,testing_policy,contact_tracing,emergency_investment_in_healthcare,investment_in_vaccines,facial_coverings,vaccination_policy,stringency_index
0,2020-01-01,AND,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2020-01-02,AND,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [23]:
# Merge epidemiology and Oxford government response datasets on date + location_key
merged_data = focus_data1.merge(
    focus_data2,
    on=['date', 'location_key'],
    how='inner',
    validate='one_to_one'
)

# Keep only the selected focus countries
merged_data = merged_data[merged_data['location_key'].isin(focus_countries)].copy()

print(f"focus_data1 shape: {focus_data1.shape}")
print(f"focus_data2 shape: {focus_data2.shape}")
print(f"Merged shape:      {merged_data.shape}")

focus_data1 shape: (226892, 10)
focus_data2 shape: (171200, 22)
Merged shape:      (2787, 30)

In [24]:
merged_data

,date,location_key,new_confirmed,new_deceased,new_recovered,new_tested,cumulative_confirmed,cumulative_deceased,cumulative_recovered,cumulative_tested,...,fiscal_measures,international_support,public_information_campaigns,testing_policy,contact_tracing,emergency_investment_in_healthcare,investment_in_vaccines,facial_coverings,vaccination_policy,stringency_index
39867,2020-01-01,DEU,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00
39868,2020-01-02,DEU,1.0,0.0,NaN,NaN,1.0,0.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00
39869,2020-01-03,DEU,0.0,0.0,NaN,NaN,1.0,0.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00
39870,2020-01-04,DEU,0.0,0.0,NaN,NaN,1.0,0.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00
39871,2020-01-05,DEU,0.0,0.0,NaN,NaN,1.0,0.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56571,2022-07-21,GBR,14154.0,155.0,NaN,NaN,23255603.0,184020.0,NaN,NaN,...,NaN,NaN,2.0,2.0,0.0,NaN,0.0,1.0,5.0,11.11
56572,2022-07-22,GBR,12374.0,157.0,NaN,NaN,23267977.0,184177.0,NaN,NaN,...,NaN,NaN,2.0,2.0,0.0,NaN,0.0,1.0,5.0,11.11
56573,2022-07-23,GBR,9927.0,159.0,NaN,NaN,23277904.0,184336.0,NaN,NaN,...,NaN,NaN,2.0,2.0,0.0,NaN,0.0,1.0,5.0,11.11
56574,2022-07-24,GBR,11271.0,183.0,NaN,NaN,23289175.0,184519.0,NaN,NaN,...,NaN,NaN,2.0,2.0,0.0,NaN,0.0,1.0,5.0,11.11
56575,2022-07-25,GBR,13295.0,151.0,NaN,NaN,23302470.0,184670.0,NaN,NaN,...,NaN,NaN,2.0,2.0,0.0,NaN,0.0,1.0,5.0,11.11

In [25]:
# Number of days recorded for each country in merged data
merged_data_numberOfDays=merged_data['location_key'].value_counts()
merged_data_numberOfDays

location_key
GBR    937
DEU    930
DNK    920
Name: count, dtype: int64

In [26]:
# Using statistics to filter the data
# We will keep countries that have number of days recorded >= Q1 (first quartile)

# For merged dataset
q1_mergedData = stats2['Q1']
# Filtering dataset to exclude data with observation numbers below Q1
filtered_countries_2 = merged_data_numberOfDays[merged_data_numberOfDays >= q1_mergedData].index.tolist()
filtered_mergedData = merged_data[merged_data['location_key'].isin(filtered_countries_2)]

print(f"\nDataset 2 - Q1 threshold: {q1_mergedData}")
print(f"Countries kept (>= Q1): {len(filtered_countries_2)}")
print(f"Filtered data2 shape: {filtered_mergedData.shape}")

filtered_mergedData

Dataset 2 - Q1 threshold: 923.0
Countries kept (>= Q1): 2
Filtered data2 shape: (1867, 30)

,date,location_key,new_confirmed,new_deceased,new_recovered,new_tested,cumulative_confirmed,cumulative_deceased,cumulative_recovered,cumulative_tested,...,fiscal_measures,international_support,public_information_campaigns,testing_policy,contact_tracing,emergency_investment_in_healthcare,investment_in_vaccines,facial_coverings,vaccination_policy,stringency_index
39867,2020-01-01,DEU,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00
39868,2020-01-02,DEU,1.0,0.0,NaN,NaN,1.0,0.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00
39869,2020-01-03,DEU,0.0,0.0,NaN,NaN,1.0,0.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00
39870,2020-01-04,DEU,0.0,0.0,NaN,NaN,1.0,0.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00
39871,2020-01-05,DEU,0.0,0.0,NaN,NaN,1.0,0.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56571,2022-07-21,GBR,14154.0,155.0,NaN,NaN,23255603.0,184020.0,NaN,NaN,...,NaN,NaN,2.0,2.0,0.0,NaN,0.0,1.0,5.0,11.11
56572,2022-07-22,GBR,12374.0,157.0,NaN,NaN,23267977.0,184177.0,NaN,NaN,...,NaN,NaN,2.0,2.0,0.0,NaN,0.0,1.0,5.0,11.11
56573,2022-07-23,GBR,9927.0,159.0,NaN,NaN,23277904.0,184336.0,NaN,NaN,...,NaN,NaN,2.0,2.0,0.0,NaN,0.0,1.0,5.0,11.11
56574,2022-07-24,GBR,11271.0,183.0,NaN,NaN,23289175.0,184519.0,NaN,NaN,...,NaN,NaN,2.0,2.0,0.0,NaN,0.0,1.0,5.0,11.11
56575,2022-07-25,GBR,13295.0,151.0,NaN,NaN,23302470.0,184670.0,NaN,NaN,...,NaN,NaN,2.0,2.0,0.0,NaN,0.0,1.0,5.0,11.11

In [27]:

#Filter dates to only include dates shared for the selected countries in merged dataset
# Finding the first common observation date fro the merged dataset for all of the countries to make the comparison fair
merged_data_before_filter = merged_data.copy()
merged_data = merged_data.copy()

merged_data['date'] = pd.to_datetime(merged_data['date'].astype('string'), errors='coerce').dt.normalize()

min_dates_2 = merged_data.groupby('location_key')['date'].min()
max_dates_2 = merged_data.groupby('location_key')['date'].max()

first_common_2 = min_dates_2.max()
last_common_2  = max_dates_2.min()

first_common_date = max(first_common_1, first_common_2)
last_common_date  = min(last_common_1, last_common_2)

print(f"First common date (dataset 1 & 2): {first_common_date}")
print(f"Last  common date (dataset 1 & 2): {last_common_date}")


# filtering merged_data to only include dates between these two dates

merged_data= merged_data[
    (merged_data['date'] >= first_common_date) &
    (merged_data['date'] <= last_common_date)
].copy()

print(f"merged_data shape: {merged_data.shape}")

# Show which dates were removed for each country after filtering

removed_dates_by_country = {}

for country in merged_data_before_filter['location_key'].unique():

    dates_before = pd.DatetimeIndex(
        merged_data_before_filter.loc[
            merged_data_before_filter['location_key'] == country,
            'date'
        ].unique()
    )

    dates_after = pd.DatetimeIndex(
        merged_data.loc[
            merged_data['location_key'] == country,
            'date'
        ].unique()
    )

    removed_dates = dates_before.difference(dates_after)

    if len(removed_dates) > 0:
        removed_dates_by_country[country] = removed_dates

# Print results
if removed_dates_by_country:
    print("\nDates removed from merged_data after filtering:")

    for country, removed_dates in removed_dates_by_country.items():
        print(
            f"{country}: {len(removed_dates)} removed dates "
            f"(first few: {removed_dates[:10].tolist()})"
        )
else:
    print("\nNo dates were removed by filtering.")

First common date (dataset 1 & 2): 2020-01-02 00:00:00
Last  common date (dataset 1 & 2): 2022-07-08 00:00:00
merged_data shape: (2757, 30)

Dates removed from merged_data after filtering:
DEU: 11 removed dates (first few: [Timestamp('2020-01-01 00:00:00'), Timestamp('2022-07-09 00:00:00'), Timestamp('2022-07-10 00:00:00'), Timestamp('2022-07-11 00:00:00'), Timestamp('2022-07-12 00:00:00'), Timestamp('2022-07-13 00:00:00'), Timestamp('2022-07-14 00:00:00'), Timestamp('2022-07-15 00:00:00'), Timestamp('2022-07-16 00:00:00'), Timestamp('2022-07-17 00:00:00')])
DNK: 1 removed dates (first few: [Timestamp('2020-01-01 00:00:00')])
GBR: 18 removed dates (first few: [Timestamp('2020-01-01 00:00:00'), Timestamp('2022-07-09 00:00:00'), Timestamp('2022-07-10 00:00:00'), Timestamp('2022-07-11 00:00:00'), Timestamp('2022-07-12 00:00:00'), Timestamp('2022-07-13 00:00:00'), Timestamp('2022-07-14 00:00:00'), Timestamp('2022-07-15 00:00:00'), Timestamp('2022-07-16 00:00:00'), Timestamp('2022-07-17 00:00:00')])

### - Adding vaccination data

In [ ]:
# Function to merge vaccination data with merged_data
def merge_vaccination_data(merged_df, vaccination_df):
    """
    Merge vaccination data with the merged COVID dataset on date and location_key.
    Assumes vaccination data location_key is already in ISO-3 format.
    """
    # Create a copy of vaccination data
    vax_data = vaccination_df.copy()
    
    # Standardize date column
    vax_data['date'] = pd.to_datetime(vax_data['date'].astype('string'), errors='coerce').dt.normalize()
    
    # Merge on date and location_key
    merged_with_vax = merged_df.merge(
        vax_data,
        on=['date', 'location_key'],
        how='left',
        validate='many_to_one'
    )
    
    return merged_with_vax

# Apply the merge
merged_data_with_vaccination = merge_vaccination_data(merged_data, focus_data3)

print(f"Original merged_data shape: {merged_data.shape}")
print(f"After adding vaccination data shape: {merged_data_with_vaccination.shape}")
print(f"New columns from vaccination data: {[col for col in merged_data_with_vaccination.columns if col not in merged_data.columns]}")

### - Checking for potentially missing data

In [30]:
# Check that each country has at least one entity value for every data column in merged_data.
# This helps verify that each country doesn't have systematic missingness.

def check_country_column_non_missing(df, country_col='location_key', threshold=1):
    """Return non-missing counts, missing-category flags, and a summary per country."""
    # Count non-missing entries per country and column
    non_missing_counts = df.groupby(country_col).apply(lambda group: group.notna().sum())
    if country_col in non_missing_counts.columns:
        non_missing_counts = non_missing_counts.drop(columns=[country_col])

    # Identify columns where the count of non-missing values is below the threshold
    missing_flags = (non_missing_counts < threshold)
    missing_matrix = missing_flags.astype(object)
    missing_matrix[missing_flags] = 'Non'
    missing_matrix[~missing_flags] = ''

    # Build a summary table and list missing categories for each country
    missing_categories = {
        country: non_missing_counts.columns[missing_flags.loc[country]].tolist()
        for country in non_missing_counts.index
    }

    summary = pd.DataFrame({
        'has_minimum_per_column': [len(categories) == 0 for categories in missing_categories.values()],
        'missing_columns': [', '.join(categories) if categories else '' for categories in missing_categories.values()]
    }, index=non_missing_counts.index)

    return non_missing_counts, missing_flags, missing_matrix, summary, missing_categories

# Run the check on merged_data
non_missing_counts, missing_flags, missing_matrix, country_summary, missing_categories = check_country_column_non_missing(merged_data)

print("\nSummary of missing data per category:")
missing_per_category = (missing_matrix == 'Non').sum()
print(missing_per_category)

if country_summary['has_minimum_per_column'].all():
    print("\nAll countries have at least one non-missing value in every column.")
else:
    print("\nCountries with missing entities in one or more categories:")
    for country, categories in missing_categories.items():
        if categories:
            print(f"- {country}: missing data in {', '.join(categories)}")

Summary of missing data per category:
date                                  0
new_confirmed                         0
new_deceased                          0
new_recovered                         3
new_tested                            1
cumulative_confirmed                  0
cumulative_deceased                   0
cumulative_recovered                  3
cumulative_tested                     0
school_closing                        0
workplace_closing                     0
cancel_public_events                  0
restrictions_on_gatherings            0
public_transport_closing              0
stay_at_home_requirements             0
restrictions_on_internal_movement     0
international_travel_controls         0
income_support                        0
debt_relief                           0
fiscal_measures                       0
international_support                 0
public_information_campaigns          0
testing_policy                        0
contact_tracing                       0
emergency_investment_in_healthcare    0
investment_in_vaccines                0
facial_coverings                      0
vaccination_policy                    0
stringency_index                      0
dtype: int64

Countries with missing entities in one or more categories:
- DEU: missing data in new_recovered, new_tested, cumulative_recovered
- DNK: missing data in new_recovered, cumulative_recovered
- GBR: missing data in new_recovered, cumulative_recovered

### - Adding vaccination data

Original merged_data shape: (2757, 30)
After adding vaccination data shape: (2757, 60)
New columns from vaccination data: ['new_persons_vaccinated', 'cumulative_persons_vaccinated', 'new_persons_fully_vaccinated', 'cumulative_persons_fully_vaccinated', 'new_vaccine_doses_administered', 'cumulative_vaccine_doses_administered', 'new_persons_vaccinated_pfizer', 'cumulative_persons_vaccinated_pfizer', 'new_persons_fully_vaccinated_pfizer', 'cumulative_persons_fully_vaccinated_pfizer', 'new_vaccine_doses_administered_pfizer', 'cumulative_vaccine_doses_administered_pfizer', 'new_persons_vaccinated_moderna', 'cumulative_persons_vaccinated_moderna', 'new_persons_fully_vaccinated_moderna', 'cumulative_persons_fully_vaccinated_moderna', 'new_vaccine_doses_administered_moderna', 'cumulative_vaccine_doses_administered_moderna', 'new_persons_vaccinated_janssen', 'cumulative_persons_vaccinated_janssen', 'new_persons_fully_vaccinated_janssen', 'cumulative_persons_fully_vaccinated_janssen', 'new_vaccine_doses_administered_janssen', 'cumulative_vaccine_doses_administered_janssen', 'new_persons_vaccinated_sinovac', 'total_persons_vaccinated_sinovac', 'new_persons_fully_vaccinated_sinovac', 'total_persons_fully_vaccinated_sinovac', 'new_vaccine_doses_administered_sinovac', 'total_vaccine_doses_administered_sinovac']

### - Saving the cleaned datasets

In [28]:
# Save to CSV
output_path = current_dir.parent / 'data' / 'merged_covid_data.csv'
merged_data.to_csv(output_path, index=False)
print(f"\nSaved merged dataset to: {output_path}")

merged_data.head()

Saved merged dataset to: c:\Users\Lenovo\OneDrive - Danmarks Tekniske Universitet\02806 Social data analysis and visualization\final_project\data\merged_covid_data.csv

,date,location_key,new_confirmed,new_deceased,new_recovered,new_tested,cumulative_confirmed,cumulative_deceased,cumulative_recovered,cumulative_tested,...,fiscal_measures,international_support,public_information_campaigns,testing_policy,contact_tracing,emergency_investment_in_healthcare,investment_in_vaccines,facial_coverings,vaccination_policy,stringency_index
39868,2020-01-02,DEU,1.0,0.0,NaN,NaN,1.0,0.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39869,2020-01-03,DEU,0.0,0.0,NaN,NaN,1.0,0.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39870,2020-01-04,DEU,0.0,0.0,NaN,NaN,1.0,0.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39871,2020-01-05,DEU,0.0,0.0,NaN,NaN,1.0,0.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39872,2020-01-06,DEU,0.0,0.0,NaN,NaN,1.0,0.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0