In [116]:
import pandas as pd
import numpy as np
from pathlib import Path

import pycountry

# Get the directory where the current notebook is located
current_dir = Path.cwd()

# Define the path relative to the notebook
data_path1 = current_dir.parent / "data" / "epidemiology.csv"
data_path2 = current_dir.parent / "data" / "oxford-government-response.csv"

In [117]:
# Load the datasets
data1=pd.read_csv(data_path1)
data2=pd.read_csv(data_path2)

In [118]:
#Examine the first few rows of the datasets
data1.head(5)

,date,location_key,new_confirmed,new_deceased,new_recovered,new_tested,cumulative_confirmed,cumulative_deceased,cumulative_recovered,cumulative_tested
0,2020-01-01,AD,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN
1,2020-01-02,AD,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN
2,2020-01-03,AD,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN
3,2020-01-04,AD,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN
4,2020-01-05,AD,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN

In [119]:
data2.head(5)

,date,location_key,school_closing,workplace_closing,cancel_public_events,restrictions_on_gatherings,public_transport_closing,stay_at_home_requirements,restrictions_on_internal_movement,international_travel_controls,...,fiscal_measures,international_support,public_information_campaigns,testing_policy,contact_tracing,emergency_investment_in_healthcare,investment_in_vaccines,facial_coverings,vaccination_policy,stringency_index
0,2020-01-01,AD,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2020-01-02,AD,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2020-01-03,AD,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2020-01-04,AD,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2020-01-05,AD,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [120]:
# Investigating the dataformat of the location_keys
# Get unique values from the first column (column index 0)
unique_first_cells1 = data1["location_key"].dropna().unique()
print(unique_first_cells1)

<StringArray>
[        'AD',         'AE',         'AF',     'AF_BAL',     'AF_BAM',
     'AF_BDG',     'AF_BDS',     'AF_BGL',     'AF_DAY',     'AF_FRA',
 ...
 'ZA_NW_DC40',      'ZA_WC',  'ZA_WC_CPT',  'ZA_WC_DC1',  'ZA_WC_DC2',
  'ZA_WC_DC3',  'ZA_WC_DC4',  'ZA_WC_DC5',         'ZM',         'ZW']
Length: 20905, dtype: str

In [121]:
# Investigating the dataformat of the location_keys
# Get unique values from the first column (column index 0)
unique_first_cells2 = data2["location_key"].dropna().unique()
print(unique_first_cells2)

<StringArray>
[    'AD',     'AE',     'AF',     'AL',     'AO',     'AR',     'AT',
     'AU', 'AU_ACT', 'AU_NSW',
 ...
     'UZ',     'VE',     'VI',     'VN',     'VU',     'XK',     'YE',
     'ZA',     'ZM',     'ZW']
Length: 355, dtype: str

In [122]:
# Filter for country codes only (leave out regional data)
# Return unique location keys for dataset 1
def get_unique_location_keys(data1):
    return list(set(data1["location_key"].dropna().str.split("_").str[0]))

unique_Country_Keys1 = get_unique_location_keys(data1)

print(unique_Country_Keys1)
print(len(unique_Country_Keys1))

['KH', 'GR', 'RE', 'NZ', 'ST', 'ME', 'TG', 'MK', 'SS', 'IT', 'PF', 'JE', 'RW', 'MN', 'BD', 'PS', 'LB', 'GQ', 'MR', 'IS', 'CV', 'IM', 'DM', 'ID', 'GY', 'KR', 'ES', 'SA', 'YT', 'MX', 'GT', 'MW', 'PW', 'TL', 'TK', 'KY', 'BA', 'JM', 'SX', 'US', 'CD', 'BT', 'CK', 'LK', 'AW', 'MQ', 'XK', 'ZW', 'AS', 'IL', 'KG', 'SK', 'JP', 'HU', 'IE', 'SE', 'EC', 'MV', 'TT', 'YE', 'LA', 'MP', 'NE', 'PN', 'BE', 'ZM', 'KP', 'FK', 'SG', 'PE', 'TZ', 'TD', 'CO', 'DO', 'GB', 'PL', 'CZ', 'ER', 'SV', 'LR', 'KZ', 'AI', 'LT', 'KM', 'BZ', 'MG', 'GE', 'CA', 'MM', 'HN', 'MH', 'TR', 'HK', 'AM', 'ET', 'GN', 'AL', 'GA', 'CN', 'GH', 'CF', 'IQ', 'SD', 'AG', 'SR', 'GL', 'MC', 'RU', 'AT', 'UA', 'TM', 'AF', 'BH', 'VC', 'DJ', 'CH', 'SL', 'UZ', 'TJ', 'WF', 'SZ', 'VI', 'NI', 'EH', 'UG', 'KI', 'CY', 'GG', 'PA', 'MD', 'AU', 'EG', 'GI', 'SI', 'FI', 'TO', 'CW', 'GU', 'QA', 'GW', 'BM', 'BO', 'MU', 'TC', 'MO', 'BG', 'PY', 'TH', 'NO', 'CI', 'PR', 'LV', 'SM', 'SO', 'AE', 'KN', 'PK', 'PT', 'ZA', 'LC', 'VE', 'FR', 'MZ', 'NP', 'SY', 'BF', 'KW', 'VG', 'NU', 'TW', 'EE', 'TV', 'ML', 'SB', 'BR', 'KE', 'SC', 'BJ', 'LY', 'CR', 'BY', 'BW', 'OM', 'LU', 'CL', 'TN', 'VA', 'FM', 'GD', 'IN', 'AD', 'BS', 'GF', 'MA', 'HR', 'JO', 'BI', 'CM', 'DK', 'UY', 'BB', 'DZ', 'HT', 'CU', 'LI', 'NC', 'VU', 'FO', 'IR', 'MS', 'MY', 'DE', 'RO', 'AZ', 'AR', 'PG', 'SH', 'RS', 'NG', 'WS', 'MT', 'VN', 'CG', 'PH', 'LS', 'NL', 'FJ', 'NR', 'GM', 'AO', 'SN', 'BN']
232

In [123]:
# Filter for country codes only (leave out regional data)
# Return unique location keys for dataset 2
def get_unique_location_keys(data2):
    return list(set(data2["location_key"].dropna().str.split("_").str[0]))

unique_Country_Keys2 = get_unique_location_keys(data2)

print(unique_Country_Keys2)
print(len(unique_Country_Keys2))

['KH', 'GR', 'TG', 'NZ', 'SS', 'IT', 'RW', 'MN', 'BD', 'PS', 'LB', 'MR', 'IS', 'CV', 'DM', 'ID', 'GY', 'KR', 'ES', 'SA', 'MX', 'GT', 'MW', 'TL', 'BA', 'JM', 'US', 'CD', 'BT', 'LK', 'AW', 'XK', 'ZW', 'IL', 'KG', 'SK', 'JP', 'HU', 'IE', 'SE', 'EC', 'TT', 'YE', 'LA', 'NE', 'BE', 'ZM', 'SG', 'PE', 'TZ', 'TD', 'CO', 'DO', 'GB', 'PL', 'CZ', 'ER', 'SV', 'LR', 'KZ', 'LT', 'KM', 'BZ', 'MG', 'GE', 'CA', 'MM', 'HN', 'TR', 'HK', 'ET', 'GN', 'AL', 'GA', 'CN', 'GH', 'CF', 'IQ', 'SD', 'SR', 'GL', 'MC', 'RU', 'AT', 'UA', 'TM', 'AF', 'BH', 'DJ', 'CH', 'SL', 'UZ', 'TJ', 'SZ', 'VI', 'NI', 'UG', 'KI', 'CY', 'PA', 'MD', 'AU', 'EG', 'SI', 'FI', 'TO', 'GU', 'QA', 'BM', 'BO', 'MU', 'MO', 'BG', 'PY', 'TH', 'NO', 'CI', 'PR', 'LV', 'SM', 'SO', 'AE', 'PK', 'PT', 'ZA', 'VE', 'FR', 'MZ', 'NP', 'SY', 'BF', 'KW', 'TW', 'EE', 'ML', 'SB', 'BR', 'KE', 'SC', 'BJ', 'LY', 'CR', 'BY', 'BW', 'OM', 'LU', 'CL', 'TN', 'GD', 'IN', 'AD', 'BS', 'MA', 'HR', 'JO', 'BI', 'CM', 'DK', 'UY', 'BB', 'DZ', 'HT', 'CU', 'LI', 'VU', 'FO', 'IR', 'MY', 'RO', 'DE', 'AZ', 'AR', 'PG', 'RS', 'NG', 'MT', 'VN', 'CG', 'PH', 'LS', 'NL', 'FJ', 'SN', 'GM', 'AO', 'BN']
186

In [124]:
# Pulling out focus data from dataset 1
# Filtering dataset to only include data by country
focus_data1 = data1[data1['location_key'].isin(unique_Country_Keys1)]
focus_data1.info()

<class 'pandas.DataFrame'>
Index: 226892 entries, 0 to 12525824
Data columns (total 10 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   date                  226892 non-null  str
 1   location_key          226892 non-null  str
 2   new_confirmed         226799 non-null  float64
 3   new_deceased          226624 non-null  float64
 4   new_recovered         15712 non-null   float64
 5   new_tested            76705 non-null   float64
 6   cumulative_confirmed  226798 non-null  float64
 7   cumulative_deceased   226625 non-null  float64
 8   cumulative_recovered  14759 non-null   float64
 9   cumulative_tested     80010 non-null   float64
dtypes: float64(8), str(2)
memory usage: 19.0 MB

In [125]:
# Pulling out focus data from dataset 2
# Filtering dataset to only include data by country
focus_data2 = data2[data2['location_key'].isin(unique_Country_Keys2)]
focus_data2.info()

<class 'pandas.DataFrame'>
Index: 171200 entries, 0 to 303968
Data columns (total 22 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   date                                171200 non-null  str
 1   location_key                        171200 non-null  str
 2   school_closing                      170800 non-null  float64
 3   workplace_closing                   170803 non-null  float64
 4   cancel_public_events                170785 non-null  float64
 5   restrictions_on_gatherings          170781 non-null  float64
 6   public_transport_closing            170785 non-null  float64
 7   stay_at_home_requirements           170780 non-null  float64
 8   restrictions_on_internal_movement   170765 non-null  float64
 9   international_travel_controls       170787 non-null  float64
 10  income_support                      170733 non-null  float64
 11  debt_relief                         170747 non-null  float64
 12  fiscal_measures                     105697 non-null  float64
 13  international_support               105777 non-null  float64
 14  public_information_campaigns        170791 non-null  float64
 15  testing_policy                      170767 non-null  float64
 16  contact_tracing                     170708 non-null  float64
 17  emergency_investment_in_healthcare  105659 non-null  float64
 18  investment_in_vaccines              166826 non-null  float64
 19  facial_coverings                    171036 non-null  float64
 20  vaccination_policy                  171091 non-null  float64
 21  stringency_index                    170751 non-null  float64
dtypes: float64(20), str(2)
memory usage: 30.0 MB

In [126]:
# Number of days recorded for each country in dataset 1
focus_data1_numberOfDays=focus_data1['location_key'].value_counts()
focus_data1_numberOfDays

location_key
AU    990
TH    990
AT    989
BE    989
BR    989
     ...
ZW    987
TW    974
HK    693
MO    152
EH      1
Name: count, Length: 232, dtype: int64

In [127]:
# Number of days recorded for each country in datset 2
focus_data2_numberOfDays=focus_data2['location_key'].value_counts()
focus_data2_numberOfDays

location_key
AF    938
AU    938
CL    938
HR    938
MT    938
     ...
GU    899
PS    898
CZ    881
KM    342
GD     87
Name: count, Length: 186, dtype: int64

In [ ]:
#Analyzing the distribution of the number of days recorded for each country in both datasets using boxplot statistics

def boxplot_stats(series):
    q1 = series.quantile(0.25)
    median = series.quantile(0.5)
    q3 = series.quantile(0.75)
    iqr = q3 - q1

    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr

    outliers = series[(series < lower_bound) | (series > upper_bound)]

    return {
        "min": series.min(),
        "Q1": q1,
        "median": median,
        "Q3": q3,
        "max": series.max(),
        "IQR": iqr,
        "lower_bound": lower_bound,
        "upper_bound": upper_bound,
        "num_outliers": len(outliers)
    }

# Apply to both datasets
stats1 = boxplot_stats(focus_data1_numberOfDays)
stats2 = boxplot_stats(focus_data2_numberOfDays)

# Convert to DataFrame for clean display
summary = pd.DataFrame([stats1, stats2], 
                       index=["Dataset 1", "Dataset 2"])

print(summary)

           min     Q1  median     Q3  max   IQR  lower_bound  upper_bound  \
Dataset 1    1  987.0   987.0  987.0  990   0.0        987.0        987.0
Dataset 2   87  923.0   930.0  937.0  938  14.0        902.0        958.0

           num_outliers
Dataset 1            26
Dataset 2             9

In [ ]:
# Using statistics to filter the data
# We will keep countries that have number of days recorded >= Q1 (first quartile)

# For dataset 1
q1_dataset1 = stats1['Q1']
# Filtering dataset to exclude data with observation numbers below Q1
filtered_countries_1 = focus_data1_numberOfDays[focus_data1_numberOfDays >= q1_dataset1].index.tolist()
filtered_focus_data1 = focus_data1[focus_data1['location_key'].isin(filtered_countries_1)]

print(f"Dataset 1 - Q1 threshold: {q1_dataset1}")
print(f"Countries kept (>= Q1): {len(filtered_countries_1)}")
print(f"Filtered data1 shape: {filtered_focus_data1.shape}")

# For dataset 2
q1_dataset2 = stats2['Q1']
# Filtering dataset to exclude data with observation numbers below Q1
filtered_countries_2 = focus_data2_numberOfDays[focus_data2_numberOfDays >= q1_dataset2].index.tolist()
filtered_focus_data2 = focus_data2[focus_data2['location_key'].isin(filtered_countries_2)]

print(f"\nDataset 2 - Q1 threshold: {q1_dataset2}")
print(f"Countries kept (>= Q1): {len(filtered_countries_2)}")
print(f"Filtered data2 shape: {filtered_focus_data2.shape}")

Dataset 1 - Q1 threshold: 987.0
Countries kept (>= Q1): 228
Filtered data1 shape: (225072, 10)

Dataset 2 - Q1 threshold: 923.0
Countries kept (>= Q1): 144
Filtered data2 shape: (134272, 22)

In [130]:
# For dataset 1
# Finding the first common observation date shared for all of the countries to make the comparison fair

filtered_focus_data1 = filtered_focus_data1.copy()

filtered_focus_data1['date'] = pd.to_datetime(filtered_focus_data1['date'].astype('string'), errors='coerce').dt.normalize()

min_dates_1 = filtered_focus_data1.groupby('location_key')['date'].min()
max_dates_1 = filtered_focus_data1.groupby('location_key')['date'].max()

first_common_1 = min_dates_1.max()
last_common_1 = max_dates_1.min()

print(f"First common date: {first_common_1}")
print(f"Last common date: {last_common_1}")

# Filtering the filtered_focus_data1 to only include this data interval
filtered_focus_data1_common = filtered_focus_data1[
    (filtered_focus_data1['date'] >= first_common_1) &
    (filtered_focus_data1['date'] <= last_common_1)
].copy()

print(f"filtered_focus_data1_common shape: {filtered_focus_data1_common.shape}")

# Investigate if some dates are missing for some countries. Print the dates and countries missing for the date interval

date_range = pd.date_range(start=first_common_date, end=last_common_date, freq='D')

missing_by_country_1 = {}
for country, group in filtered_focus_data1_common.groupby('location_key'):
    missing_dates = date_range.difference(pd.DatetimeIndex(group['date']))
    if len(missing_dates):
        missing_by_country_1[country] = missing_dates

if missing_by_country_1:
    print("\nMissing dates in filtered_focus_data1_common:")
    for country, missing_dates in missing_by_country_1.items():
        print(f"{country}: {len(missing_dates)} missing dates (first few: {missing_dates[:5].tolist()})")
else:
    print("\nNo missing dates found in filtered_focus_data1_common.")

First common date: 2020-01-02 00:00:00
Last common date: 2022-09-13 00:00:00
filtered_focus_data1_common shape: (224808, 10)

No missing dates found in filtered_focus_data1_common.

In [131]:
#Saving this filterede data for data 1 as a CSV file
output_path = current_dir.parent / 'data' / 'epidemiologi_global_covid_data.csv'
merged_data.to_csv(output_path, index=False)
print(f"\nSaved merged dataset to: {output_path}")

merged_data.head()

Saved merged dataset to: c:\Users\Lenovo\OneDrive - Danmarks Tekniske Universitet\02806 Social data analysis and visualization\final_project\data\epidemiologi_global_covid_data.csv

,date,location_key,new_confirmed,new_deceased,new_recovered,new_tested,cumulative_confirmed,cumulative_deceased,cumulative_recovered,cumulative_tested,...,fiscal_measures,international_support,public_information_campaigns,testing_policy,contact_tracing,emergency_investment_in_healthcare,investment_in_vaccines,facial_coverings,vaccination_policy,stringency_index
0,2020-01-02,AE,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2020-01-03,AE,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2020-01-04,AE,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2020-01-05,AE,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2020-01-06,AE,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:

def get_unique_location_keys(data2):
    return list(set(data2["location_key"].dropna().str.split("_").str[0]))

# Get country codes
unique_Country_Keys2 = get_unique_location_keys(data2)

# Keep ONLY rows where location_key is exactly a country code
focus_data2 = data2[data2["location_key"].isin(unique_Country_Keys2)]

print(focus_data2.info())

<class 'pandas.DataFrame'>
Index: 171200 entries, 0 to 303968
Data columns (total 22 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   date                                171200 non-null  str
 1   location_key                        171200 non-null  str
 2   school_closing                      170800 non-null  float64
 3   workplace_closing                   170803 non-null  float64
 4   cancel_public_events                170785 non-null  float64
 5   restrictions_on_gatherings          170781 non-null  float64
 6   public_transport_closing            170785 non-null  float64
 7   stay_at_home_requirements           170780 non-null  float64
 8   restrictions_on_internal_movement   170765 non-null  float64
 9   international_travel_controls       170787 non-null  float64
 10  income_support                      170733 non-null  float64
 11  debt_relief                         170747 non-null  float64
 12  fiscal_measures                     105697 non-null  float64
 13  international_support               105777 non-null  float64
 14  public_information_campaigns        170791 non-null  float64
 15  testing_policy                      170767 non-null  float64
 16  contact_tracing                     170708 non-null  float64
 17  emergency_investment_in_healthcare  105659 non-null  float64
 18  investment_in_vaccines              166826 non-null  float64
 19  facial_coverings                    171036 non-null  float64
 20  vaccination_policy                  171091 non-null  float64
 21  stringency_index                    170751 non-null  float64
dtypes: float64(20), str(2)
memory usage: 30.0 MB
None

In [133]:


filtered_focus_data1_common

,date,location_key,new_confirmed,new_deceased,new_recovered,new_tested,cumulative_confirmed,cumulative_deceased,cumulative_recovered,cumulative_tested
1,2020-01-02,AD,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN
2,2020-01-03,AD,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN
3,2020-01-04,AD,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN
4,2020-01-05,AD,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN
5,2020-01-06,AD,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
12525820,2022-09-09,ZW,11.0,0.0,NaN,NaN,256870.0,5596.0,NaN,NaN
12525821,2022-09-10,ZW,18.0,0.0,NaN,NaN,256888.0,5596.0,NaN,NaN
12525822,2022-09-11,ZW,0.0,0.0,NaN,NaN,256888.0,5596.0,NaN,NaN
12525823,2022-09-12,ZW,51.0,0.0,NaN,NaN,256939.0,5596.0,NaN,NaN
12525824,2022-09-13,ZW,0.0,0.0,NaN,NaN,256939.0,5596.0,NaN,NaN

In [134]:
filtered_focus_data2_common

,date,location_key,school_closing,workplace_closing,cancel_public_events,restrictions_on_gatherings,public_transport_closing,stay_at_home_requirements,restrictions_on_internal_movement,international_travel_controls,...,fiscal_measures,international_support,public_information_campaigns,testing_policy,contact_tracing,emergency_investment_in_healthcare,investment_in_vaccines,facial_coverings,vaccination_policy,stringency_index
902,2020-01-02,AE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00
903,2020-01-03,AE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00
904,2020-01-04,AE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00
905,2020-01-05,AE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00
906,2020-01-06,AE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
302123,2022-07-21,ZA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,2.0,3.0,2.0,NaN,0.0,0.0,5.0,11.11
302124,2022-07-22,ZA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,2.0,3.0,2.0,NaN,0.0,0.0,5.0,11.11
302125,2022-07-23,ZA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,2.0,3.0,2.0,NaN,0.0,0.0,5.0,11.11
302126,2022-07-24,ZA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,2.0,3.0,2.0,NaN,0.0,0.0,5.0,11.11
302127,2022-07-25,ZA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,2.0,3.0,2.0,NaN,0.0,0.0,5.0,11.11

In [135]:
# Merge epidemiology and Oxford government response datasets on date + location_key
merged_data = filtered_focus_data1_common.merge(filtered_focus_data2_common, on=['date', 'location_key'], how='inner')

print(f"filtered_focus_data1_common shape: {filtered_focus_data1_common.shape}")
print(f"filtered_focus_data2_common shape: {filtered_focus_data2_common.shape}")
print(f"Merged shape:      {merged_data.shape}")

filtered_focus_data1_common shape: (224808, 10)
filtered_focus_data2_common shape: (134128, 22)
Merged shape:      (132268, 30)

In [136]:
# Selecting focus countries for deep dive analysis
focus_countries = ['DNK', 'DEU', 'GBR']

In [137]:

#Filter dates to only include dates shared for the selected countries in both datasets
#For dataset 1 and 2 combined
# Finding the first common observation date acrossed the two datasets shared for all of the countries to make the comparison fair

filtered_focus_data2 = filtered_focus_data2.copy()

filtered_focus_data2['date'] = pd.to_datetime(filtered_focus_data2['date'].astype('string'), errors='coerce').dt.normalize()

min_dates_2 = filtered_focus_data1.groupby('location_key')['date'].min()
max_dates_2 = filtered_focus_data1.groupby('location_key')['date'].max()

first_common_2 = min_dates_2.max()
last_common_2  = max_dates_2.min()

first_common_date = max(first_common_1, first_common_2)
last_common_date  = min(last_common_1, last_common_2)

print(f"First common date (dataset 1 & 2): {first_common_date}")
print(f"Last  common date (dataset 1 & 2): {last_common_date}")


# filtered_focus_data2 to only include dates between these two dates

filtered_focus_data2_common = filtered_focus_data2[
    (filtered_focus_data2['date'] >= first_common_date) &
    (filtered_focus_data2['date'] <= last_common_date)
].copy()

print(f"filtered_focus_data2_common shape: {filtered_focus_data2_common.shape}")


missing_by_country_2 = {}
for country, group in filtered_focus_data2_common.groupby('location_key'):
    missing_dates = date_range.difference(pd.DatetimeIndex(group['date']))
    if len(missing_dates):
        missing_by_country_2[country] = missing_dates

if missing_by_country_2:
    print("\nMissing dates in filtered_focus_data2_common:")
    for country, missing_dates in missing_by_country_2.items():
        print(f"{country}: {len(missing_dates)} missing dates (first few: {missing_dates[:5].tolist()})")
else:
    print("\nNo missing dates found in filtered_focus_data2_common.")

First common date (dataset 1 & 2): 2020-01-02 00:00:00
Last  common date (dataset 1 & 2): 2022-09-13 00:00:00
filtered_focus_data2_common shape: (134128, 22)

Missing dates in filtered_focus_data2_common:
AE: 57 missing dates (first few: [Timestamp('2022-07-19 00:00:00'), Timestamp('2022-07-20 00:00:00'), Timestamp('2022-07-21 00:00:00'), Timestamp('2022-07-22 00:00:00'), Timestamp('2022-07-23 00:00:00')])
AF: 49 missing dates (first few: [Timestamp('2022-07-27 00:00:00'), Timestamp('2022-07-28 00:00:00'), Timestamp('2022-07-29 00:00:00'), Timestamp('2022-07-30 00:00:00'), Timestamp('2022-07-31 00:00:00')])
AR: 63 missing dates (first few: [Timestamp('2022-07-13 00:00:00'), Timestamp('2022-07-14 00:00:00'), Timestamp('2022-07-15 00:00:00'), Timestamp('2022-07-16 00:00:00'), Timestamp('2022-07-17 00:00:00')])
AT: 50 missing dates (first few: [Timestamp('2022-07-26 00:00:00'), Timestamp('2022-07-27 00:00:00'), Timestamp('2022-07-28 00:00:00'), Timestamp('2022-07-29 00:00:00'), Timestamp('2022-07-30 00:00:00')])
AU: 49 missing dates (first few: [Timestamp('2022-07-27 00:00:00'), Timestamp('2022-07-28 00:00:00'), Timestamp('2022-07-29 00:00:00'), Timestamp('2022-07-30 00:00:00'), Timestamp('2022-07-31 00:00:00')])
AW: 50 missing dates (first few: [Timestamp('2022-07-26 00:00:00'), Timestamp('2022-07-27 00:00:00'), Timestamp('2022-07-28 00:00:00'), Timestamp('2022-07-29 00:00:00'), Timestamp('2022-07-30 00:00:00')])
BA: 53 missing dates (first few: [Timestamp('2022-07-23 00:00:00'), Timestamp('2022-07-24 00:00:00'), Timestamp('2022-07-25 00:00:00'), Timestamp('2022-07-26 00:00:00'), Timestamp('2022-07-27 00:00:00')])
BB: 58 missing dates (first few: [Timestamp('2022-07-18 00:00:00'), Timestamp('2022-07-19 00:00:00'), Timestamp('2022-07-20 00:00:00'), Timestamp('2022-07-21 00:00:00'), Timestamp('2022-07-22 00:00:00')])
BD: 50 missing dates (first few: [Timestamp('2022-07-26 00:00:00'), Timestamp('2022-07-27 00:00:00'), Timestamp('2022-07-28 00:00:00'), Timestamp('2022-07-29 00:00:00'), Timestamp('2022-07-30 00:00:00')])
BG: 50 missing dates (first few: [Timestamp('2022-07-26 00:00:00'), Timestamp('2022-07-27 00:00:00'), Timestamp('2022-07-28 00:00:00'), Timestamp('2022-07-29 00:00:00'), Timestamp('2022-07-30 00:00:00')])
BH: 50 missing dates (first few: [Timestamp('2022-07-26 00:00:00'), Timestamp('2022-07-27 00:00:00'), Timestamp('2022-07-28 00:00:00'), Timestamp('2022-07-29 00:00:00'), Timestamp('2022-07-30 00:00:00')])
BI: 50 missing dates (first few: [Timestamp('2022-07-26 00:00:00'), Timestamp('2022-07-27 00:00:00'), Timestamp('2022-07-28 00:00:00'), Timestamp('2022-07-29 00:00:00'), Timestamp('2022-07-30 00:00:00')])
BJ: 60 missing dates (first few: [Timestamp('2022-07-16 00:00:00'), Timestamp('2022-07-17 00:00:00'), Timestamp('2022-07-18 00:00:00'), Timestamp('2022-07-19 00:00:00'), Timestamp('2022-07-20 00:00:00')])
BM: 64 missing dates (first few: [Timestamp('2022-07-12 00:00:00'), Timestamp('2022-07-13 00:00:00'), Timestamp('2022-07-14 00:00:00'), Timestamp('2022-07-15 00:00:00'), Timestamp('2022-07-16 00:00:00')])
BN: 56 missing dates (first few: [Timestamp('2022-07-20 00:00:00'), Timestamp('2022-07-21 00:00:00'), Timestamp('2022-07-22 00:00:00'), Timestamp('2022-07-23 00:00:00'), Timestamp('2022-07-24 00:00:00')])
BO: 57 missing dates (first few: [Timestamp('2022-07-19 00:00:00'), Timestamp('2022-07-20 00:00:00'), Timestamp('2022-07-21 00:00:00'), Timestamp('2022-07-22 00:00:00'), Timestamp('2022-07-23 00:00:00')])
BR: 54 missing dates (first few: [Timestamp('2022-07-22 00:00:00'), Timestamp('2022-07-23 00:00:00'), Timestamp('2022-07-24 00:00:00'), Timestamp('2022-07-25 00:00:00'), Timestamp('2022-07-26 00:00:00')])
BS: 50 missing dates (first few: [Timestamp('2022-07-26 00:00:00'), Timestamp('2022-07-27 00:00:00'), Timestamp('2022-07-28 00:00:00'), Timestamp('2022-07-29 00:00:00'), Timestamp('2022-07-30 00:00:00')])
BT: 51 missing dates (first few: [Timestamp('2022-07-25 00:00:00'), Timestamp('2022-07-26 00:00:00'), Timestamp('2022-07-27 00:00:00'), Timestamp('2022-07-28 00:00:00'), Timestamp('2022-07-29 00:00:00')])
BW: 50 missing dates (first few: [Timestamp('2022-07-26 00:00:00'), Timestamp('2022-07-27 00:00:00'), Timestamp('2022-07-28 00:00:00'), Timestamp('2022-07-29 00:00:00'), Timestamp('2022-07-30 00:00:00')])
BY: 56 missing dates (first few: [Timestamp('2022-07-20 00:00:00'), Timestamp('2022-07-21 00:00:00'), Timestamp('2022-07-22 00:00:00'), Timestamp('2022-07-23 00:00:00'), Timestamp('2022-07-24 00:00:00')])
BZ: 57 missing dates (first few: [Timestamp('2022-07-19 00:00:00'), Timestamp('2022-07-20 00:00:00'), Timestamp('2022-07-21 00:00:00'), Timestamp('2022-07-22 00:00:00'), Timestamp('2022-07-23 00:00:00')])
CA: 50 missing dates (first few: [Timestamp('2022-07-26 00:00:00'), Timestamp('2022-07-27 00:00:00'), Timestamp('2022-07-28 00:00:00'), Timestamp('2022-07-29 00:00:00'), Timestamp('2022-07-30 00:00:00')])
CD: 57 missing dates (first few: [Timestamp('2022-07-19 00:00:00'), Timestamp('2022-07-20 00:00:00'), Timestamp('2022-07-21 00:00:00'), Timestamp('2022-07-22 00:00:00'), Timestamp('2022-07-23 00:00:00')])
CF: 57 missing dates (first few: [Timestamp('2022-07-19 00:00:00'), Timestamp('2022-07-20 00:00:00'), Timestamp('2022-07-21 00:00:00'), Timestamp('2022-07-22 00:00:00'), Timestamp('2022-07-23 00:00:00')])
CG: 59 missing dates (first few: [Timestamp('2022-07-17 00:00:00'), Timestamp('2022-07-18 00:00:00'), Timestamp('2022-07-19 00:00:00'), Timestamp('2022-07-20 00:00:00'), Timestamp('2022-07-21 00:00:00')])
CH: 51 missing dates (first few: [Timestamp('2022-07-25 00:00:00'), Timestamp('2022-07-26 00:00:00'), Timestamp('2022-07-27 00:00:00'), Timestamp('2022-07-28 00:00:00'), Timestamp('2022-07-29 00:00:00')])
CI: 62 missing dates (first few: [Timestamp('2022-07-14 00:00:00'), Timestamp('2022-07-15 00:00:00'), Timestamp('2022-07-16 00:00:00'), Timestamp('2022-07-17 00:00:00'), Timestamp('2022-07-18 00:00:00')])
CL: 49 missing dates (first few: [Timestamp('2022-07-27 00:00:00'), Timestamp('2022-07-28 00:00:00'), Timestamp('2022-07-29 00:00:00'), Timestamp('2022-07-30 00:00:00'), Timestamp('2022-07-31 00:00:00')])
CM: 54 missing dates (first few: [Timestamp('2022-07-22 00:00:00'), Timestamp('2022-07-23 00:00:00'), Timestamp('2022-07-24 00:00:00'), Timestamp('2022-07-25 00:00:00'), Timestamp('2022-07-26 00:00:00')])
CO: 50 missing dates (first few: [Timestamp('2022-07-26 00:00:00'), Timestamp('2022-07-27 00:00:00'), Timestamp('2022-07-28 00:00:00'), Timestamp('2022-07-29 00:00:00'), Timestamp('2022-07-30 00:00:00')])
CU: 64 missing dates (first few: [Timestamp('2022-07-12 00:00:00'), Timestamp('2022-07-13 00:00:00'), Timestamp('2022-07-14 00:00:00'), Timestamp('2022-07-15 00:00:00'), Timestamp('2022-07-16 00:00:00')])
CY: 64 missing dates (first few: [Timestamp('2022-07-12 00:00:00'), Timestamp('2022-07-13 00:00:00'), Timestamp('2022-07-14 00:00:00'), Timestamp('2022-07-15 00:00:00'), Timestamp('2022-07-16 00:00:00')])
DE: 57 missing dates (first few: [Timestamp('2022-07-19 00:00:00'), Timestamp('2022-07-20 00:00:00'), Timestamp('2022-07-21 00:00:00'), Timestamp('2022-07-22 00:00:00'), Timestamp('2022-07-23 00:00:00')])
DJ: 55 missing dates (first few: [Timestamp('2022-07-21 00:00:00'), Timestamp('2022-07-22 00:00:00'), Timestamp('2022-07-23 00:00:00'), Timestamp('2022-07-24 00:00:00'), Timestamp('2022-07-25 00:00:00')])
DM: 63 missing dates (first few: [Timestamp('2022-07-13 00:00:00'), Timestamp('2022-07-14 00:00:00'), Timestamp('2022-07-15 00:00:00'), Timestamp('2022-07-16 00:00:00'), Timestamp('2022-07-17 00:00:00')])
DO: 62 missing dates (first few: [Timestamp('2022-07-14 00:00:00'), Timestamp('2022-07-15 00:00:00'), Timestamp('2022-07-16 00:00:00'), Timestamp('2022-07-17 00:00:00'), Timestamp('2022-07-18 00:00:00')])
DZ: 57 missing dates (first few: [Timestamp('2022-07-19 00:00:00'), Timestamp('2022-07-20 00:00:00'), Timestamp('2022-07-21 00:00:00'), Timestamp('2022-07-22 00:00:00'), Timestamp('2022-07-23 00:00:00')])
EC: 50 missing dates (first few: [Timestamp('2022-07-26 00:00:00'), Timestamp('2022-07-27 00:00:00'), Timestamp('2022-07-28 00:00:00'), Timestamp('2022-07-29 00:00:00'), Timestamp('2022-07-30 00:00:00')])
EE: 50 missing dates (first few: [Timestamp('2022-07-26 00:00:00'), Timestamp('2022-07-27 00:00:00'), Timestamp('2022-07-28 00:00:00'), Timestamp('2022-07-29 00:00:00'), Timestamp('2022-07-30 00:00:00')])
EG: 51 missing dates (first few: [Timestamp('2022-07-25 00:00:00'), Timestamp('2022-07-26 00:00:00'), Timestamp('2022-07-27 00:00:00'), Timestamp('2022-07-28 00:00:00'), Timestamp('2022-07-29 00:00:00')])
ER: 50 missing dates (first few: [Timestamp('2022-07-26 00:00:00'), Timestamp('2022-07-27 00:00:00'), Timestamp('2022-07-28 00:00:00'), Timestamp('2022-07-29 00:00:00'), Timestamp('2022-07-30 00:00:00')])
ES: 51 missing dates (first few: [Timestamp('2022-07-25 00:00:00'), Timestamp('2022-07-26 00:00:00'), Timestamp('2022-07-27 00:00:00'), Timestamp('2022-07-28 00:00:00'), Timestamp('2022-07-29 00:00:00')])
ET: 57 missing dates (first few: [Timestamp('2022-07-19 00:00:00'), Timestamp('2022-07-20 00:00:00'), Timestamp('2022-07-21 00:00:00'), Timestamp('2022-07-22 00:00:00'), Timestamp('2022-07-23 00:00:00')])
FJ: 57 missing dates (first few: [Timestamp('2022-07-19 00:00:00'), Timestamp('2022-07-20 00:00:00'), Timestamp('2022-07-21 00:00:00'), Timestamp('2022-07-22 00:00:00'), Timestamp('2022-07-23 00:00:00')])
GA: 57 missing dates (first few: [Timestamp('2022-07-19 00:00:00'), Timestamp('2022-07-20 00:00:00'), Timestamp('2022-07-21 00:00:00'), Timestamp('2022-07-22 00:00:00'), Timestamp('2022-07-23 00:00:00')])
GB: 50 missing dates (first few: [Timestamp('2022-07-26 00:00:00'), Timestamp('2022-07-27 00:00:00'), Timestamp('2022-07-28 00:00:00'), Timestamp('2022-07-29 00:00:00'), Timestamp('2022-07-30 00:00:00')])
GH: 57 missing dates (first few: [Timestamp('2022-07-19 00:00:00'), Timestamp('2022-07-20 00:00:00'), Timestamp('2022-07-21 00:00:00'), Timestamp('2022-07-22 00:00:00'), Timestamp('2022-07-23 00:00:00')])
GL: 50 missing dates (first few: [Timestamp('2022-07-26 00:00:00'), Timestamp('2022-07-27 00:00:00'), Timestamp('2022-07-28 00:00:00'), Timestamp('2022-07-29 00:00:00'), Timestamp('2022-07-30 00:00:00')])
GM: 64 missing dates (first few: [Timestamp('2022-07-12 00:00:00'), Timestamp('2022-07-13 00:00:00'), Timestamp('2022-07-14 00:00:00'), Timestamp('2022-07-15 00:00:00'), Timestamp('2022-07-16 00:00:00')])
GN: 50 missing dates (first few: [Timestamp('2022-07-26 00:00:00'), Timestamp('2022-07-27 00:00:00'), Timestamp('2022-07-28 00:00:00'), Timestamp('2022-07-29 00:00:00'), Timestamp('2022-07-30 00:00:00')])
GR: 51 missing dates (first few: [Timestamp('2022-07-25 00:00:00'), Timestamp('2022-07-26 00:00:00'), Timestamp('2022-07-27 00:00:00'), Timestamp('2022-07-28 00:00:00'), Timestamp('2022-07-29 00:00:00')])
GT: 53 missing dates (first few: [Timestamp('2022-07-23 00:00:00'), Timestamp('2022-07-24 00:00:00'), Timestamp('2022-07-25 00:00:00'), Timestamp('2022-07-26 00:00:00'), Timestamp('2022-07-27 00:00:00')])
GY: 50 missing dates (first few: [Timestamp('2022-07-26 00:00:00'), Timestamp('2022-07-27 00:00:00'), Timestamp('2022-07-28 00:00:00'), Timestamp('2022-07-29 00:00:00'), Timestamp('2022-07-30 00:00:00')])
HK: 58 missing dates (first few: [Timestamp('2022-07-18 00:00:00'), Timestamp('2022-07-19 00:00:00'), Timestamp('2022-07-20 00:00:00'), Timestamp('2022-07-21 00:00:00'), Timestamp('2022-07-22 00:00:00')])
HN: 50 missing dates (first few: [Timestamp('2022-07-26 00:00:00'), Timestamp('2022-07-27 00:00:00'), Timestamp('2022-07-28 00:00:00'), Timestamp('2022-07-29 00:00:00'), Timestamp('2022-07-30 00:00:00')])
HR: 49 missing dates (first few: [Timestamp('2022-07-27 00:00:00'), Timestamp('2022-07-28 00:00:00'), Timestamp('2022-07-29 00:00:00'), Timestamp('2022-07-30 00:00:00'), Timestamp('2022-07-31 00:00:00')])
HU: 60 missing dates (first few: [Timestamp('2022-07-16 00:00:00'), Timestamp('2022-07-17 00:00:00'), Timestamp('2022-07-18 00:00:00'), Timestamp('2022-07-19 00:00:00'), Timestamp('2022-07-20 00:00:00')])
ID: 53 missing dates (first few: [Timestamp('2022-07-23 00:00:00'), Timestamp('2022-07-24 00:00:00'), Timestamp('2022-07-25 00:00:00'), Timestamp('2022-07-26 00:00:00'), Timestamp('2022-07-27 00:00:00')])
IE: 54 missing dates (first few: [Timestamp('2022-07-22 00:00:00'), Timestamp('2022-07-23 00:00:00'), Timestamp('2022-07-24 00:00:00'), Timestamp('2022-07-25 00:00:00'), Timestamp('2022-07-26 00:00:00')])
IL: 50 missing dates (first few: [Timestamp('2022-07-26 00:00:00'), Timestamp('2022-07-27 00:00:00'), Timestamp('2022-07-28 00:00:00'), Timestamp('2022-07-29 00:00:00'), Timestamp('2022-07-30 00:00:00')])
IN: 56 missing dates (first few: [Timestamp('2022-07-20 00:00:00'), Timestamp('2022-07-21 00:00:00'), Timestamp('2022-07-22 00:00:00'), Timestamp('2022-07-23 00:00:00'), Timestamp('2022-07-24 00:00:00')])
IQ: 50 missing dates (first few: [Timestamp('2022-07-26 00:00:00'), Timestamp('2022-07-27 00:00:00'), Timestamp('2022-07-28 00:00:00'), Timestamp('2022-07-29 00:00:00'), Timestamp('2022-07-30 00:00:00')])
IS: 50 missing dates (first few: [Timestamp('2022-07-26 00:00:00'), Timestamp('2022-07-27 00:00:00'), Timestamp('2022-07-28 00:00:00'), Timestamp('2022-07-29 00:00:00'), Timestamp('2022-07-30 00:00:00')])
IT: 56 missing dates (first few: [Timestamp('2022-07-20 00:00:00'), Timestamp('2022-07-21 00:00:00'), Timestamp('2022-07-22 00:00:00'), Timestamp('2022-07-23 00:00:00'), Timestamp('2022-07-24 00:00:00')])
JM: 63 missing dates (first few: [Timestamp('2022-07-13 00:00:00'), Timestamp('2022-07-14 00:00:00'), Timestamp('2022-07-15 00:00:00'), Timestamp('2022-07-16 00:00:00'), Timestamp('2022-07-17 00:00:00')])
JO: 57 missing dates (first few: [Timestamp('2022-07-19 00:00:00'), Timestamp('2022-07-20 00:00:00'), Timestamp('2022-07-21 00:00:00'), Timestamp('2022-07-22 00:00:00'), Timestamp('2022-07-23 00:00:00')])
JP: 50 missing dates (first few: [Timestamp('2022-07-26 00:00:00'), Timestamp('2022-07-27 00:00:00'), Timestamp('2022-07-28 00:00:00'), Timestamp('2022-07-29 00:00:00'), Timestamp('2022-07-30 00:00:00')])
KE: 50 missing dates (first few: [Timestamp('2022-07-26 00:00:00'), Timestamp('2022-07-27 00:00:00'), Timestamp('2022-07-28 00:00:00'), Timestamp('2022-07-29 00:00:00'), Timestamp('2022-07-30 00:00:00')])
KG: 51 missing dates (first few: [Timestamp('2022-07-25 00:00:00'), Timestamp('2022-07-26 00:00:00'), Timestamp('2022-07-27 00:00:00'), Timestamp('2022-07-28 00:00:00'), Timestamp('2022-07-29 00:00:00')])
KH: 50 missing dates (first few: [Timestamp('2022-07-26 00:00:00'), Timestamp('2022-07-27 00:00:00'), Timestamp('2022-07-28 00:00:00'), Timestamp('2022-07-29 00:00:00'), Timestamp('2022-07-30 00:00:00')])
KW: 57 missing dates (first few: [Timestamp('2022-07-19 00:00:00'), Timestamp('2022-07-20 00:00:00'), Timestamp('2022-07-21 00:00:00'), Timestamp('2022-07-22 00:00:00'), Timestamp('2022-07-23 00:00:00')])
KZ: 64 missing dates (first few: [Timestamp('2022-07-12 00:00:00'), Timestamp('2022-07-13 00:00:00'), Timestamp('2022-07-14 00:00:00'), Timestamp('2022-07-15 00:00:00'), Timestamp('2022-07-16 00:00:00')])
LA: 52 missing dates (first few: [Timestamp('2022-07-24 00:00:00'), Timestamp('2022-07-25 00:00:00'), Timestamp('2022-07-26 00:00:00'), Timestamp('2022-07-27 00:00:00'), Timestamp('2022-07-28 00:00:00')])
LK: 50 missing dates (first few: [Timestamp('2022-07-26 00:00:00'), Timestamp('2022-07-27 00:00:00'), Timestamp('2022-07-28 00:00:00'), Timestamp('2022-07-29 00:00:00'), Timestamp('2022-07-30 00:00:00')])
LR: 57 missing dates (first few: [Timestamp('2022-07-19 00:00:00'), Timestamp('2022-07-20 00:00:00'), Timestamp('2022-07-21 00:00:00'), Timestamp('2022-07-22 00:00:00'), Timestamp('2022-07-23 00:00:00')])
LT: 56 missing dates (first few: [Timestamp('2022-07-20 00:00:00'), Timestamp('2022-07-21 00:00:00'), Timestamp('2022-07-22 00:00:00'), Timestamp('2022-07-23 00:00:00'), Timestamp('2022-07-24 00:00:00')])
LU: 50 missing dates (first few: [Timestamp('2022-07-26 00:00:00'), Timestamp('2022-07-27 00:00:00'), Timestamp('2022-07-28 00:00:00'), Timestamp('2022-07-29 00:00:00'), Timestamp('2022-07-30 00:00:00')])
LV: 51 missing dates (first few: [Timestamp('2022-07-25 00:00:00'), Timestamp('2022-07-26 00:00:00'), Timestamp('2022-07-27 00:00:00'), Timestamp('2022-07-28 00:00:00'), Timestamp('2022-07-29 00:00:00')])
LY: 59 missing dates (first few: [Timestamp('2022-07-17 00:00:00'), Timestamp('2022-07-18 00:00:00'), Timestamp('2022-07-19 00:00:00'), Timestamp('2022-07-20 00:00:00'), Timestamp('2022-07-21 00:00:00')])
MG: 61 missing dates (first few: [Timestamp('2022-07-15 00:00:00'), Timestamp('2022-07-16 00:00:00'), Timestamp('2022-07-17 00:00:00'), Timestamp('2022-07-18 00:00:00'), Timestamp('2022-07-19 00:00:00')])
ML: 56 missing dates (first few: [Timestamp('2022-07-20 00:00:00'), Timestamp('2022-07-21 00:00:00'), Timestamp('2022-07-22 00:00:00'), Timestamp('2022-07-23 00:00:00'), Timestamp('2022-07-24 00:00:00')])
MM: 58 missing dates (first few: [Timestamp('2022-07-18 00:00:00'), Timestamp('2022-07-19 00:00:00'), Timestamp('2022-07-20 00:00:00'), Timestamp('2022-07-21 00:00:00'), Timestamp('2022-07-22 00:00:00')])
MN: 61 missing dates (first few: [Timestamp('2022-07-15 00:00:00'), Timestamp('2022-07-16 00:00:00'), Timestamp('2022-07-17 00:00:00'), Timestamp('2022-07-18 00:00:00'), Timestamp('2022-07-19 00:00:00')])
MO: 54 missing dates (first few: [Timestamp('2022-07-22 00:00:00'), Timestamp('2022-07-23 00:00:00'), Timestamp('2022-07-24 00:00:00'), Timestamp('2022-07-25 00:00:00'), Timestamp('2022-07-26 00:00:00')])
MR: 50 missing dates (first few: [Timestamp('2022-07-26 00:00:00'), Timestamp('2022-07-27 00:00:00'), Timestamp('2022-07-28 00:00:00'), Timestamp('2022-07-29 00:00:00'), Timestamp('2022-07-30 00:00:00')])
MT: 49 missing dates (first few: [Timestamp('2022-07-27 00:00:00'), Timestamp('2022-07-28 00:00:00'), Timestamp('2022-07-29 00:00:00'), Timestamp('2022-07-30 00:00:00'), Timestamp('2022-07-31 00:00:00')])
MU: 59 missing dates (first few: [Timestamp('2022-07-17 00:00:00'), Timestamp('2022-07-18 00:00:00'), Timestamp('2022-07-19 00:00:00'), Timestamp('2022-07-20 00:00:00'), Timestamp('2022-07-21 00:00:00')])
MW: 59 missing dates (first few: [Timestamp('2022-07-17 00:00:00'), Timestamp('2022-07-18 00:00:00'), Timestamp('2022-07-19 00:00:00'), Timestamp('2022-07-20 00:00:00'), Timestamp('2022-07-21 00:00:00')])
MX: 64 missing dates (first few: [Timestamp('2022-07-12 00:00:00'), Timestamp('2022-07-13 00:00:00'), Timestamp('2022-07-14 00:00:00'), Timestamp('2022-07-15 00:00:00'), Timestamp('2022-07-16 00:00:00')])
MY: 50 missing dates (first few: [Timestamp('2022-07-26 00:00:00'), Timestamp('2022-07-27 00:00:00'), Timestamp('2022-07-28 00:00:00'), Timestamp('2022-07-29 00:00:00'), Timestamp('2022-07-30 00:00:00')])
NE: 51 missing dates (first few: [Timestamp('2022-07-25 00:00:00'), Timestamp('2022-07-26 00:00:00'), Timestamp('2022-07-27 00:00:00'), Timestamp('2022-07-28 00:00:00'), Timestamp('2022-07-29 00:00:00')])
NG: 63 missing dates (first few: [Timestamp('2022-07-11 00:00:00'), Timestamp('2022-07-13 00:00:00'), Timestamp('2022-07-14 00:00:00'), Timestamp('2022-07-15 00:00:00'), Timestamp('2022-07-16 00:00:00')])
NI: 57 missing dates (first few: [Timestamp('2022-07-19 00:00:00'), Timestamp('2022-07-20 00:00:00'), Timestamp('2022-07-21 00:00:00'), Timestamp('2022-07-22 00:00:00'), Timestamp('2022-07-23 00:00:00')])
NL: 58 missing dates (first few: [Timestamp('2022-07-18 00:00:00'), Timestamp('2022-07-19 00:00:00'), Timestamp('2022-07-20 00:00:00'), Timestamp('2022-07-21 00:00:00'), Timestamp('2022-07-22 00:00:00')])
NO: 58 missing dates (first few: [Timestamp('2022-07-18 00:00:00'), Timestamp('2022-07-19 00:00:00'), Timestamp('2022-07-20 00:00:00'), Timestamp('2022-07-21 00:00:00'), Timestamp('2022-07-22 00:00:00')])

In [138]:
# Save to CSV
output_path = current_dir.parent / 'data' / 'merged_covid_data.csv'
merged_data.to_csv(output_path, index=False)
print(f"\nSaved merged dataset to: {output_path}")

merged_data.head()

Saved merged dataset to: c:\Users\Lenovo\OneDrive - Danmarks Tekniske Universitet\02806 Social data analysis and visualization\final_project\data\merged_covid_data.csv

,date,location_key,new_confirmed,new_deceased,new_recovered,new_tested,cumulative_confirmed,cumulative_deceased,cumulative_recovered,cumulative_tested,...,fiscal_measures,international_support,public_information_campaigns,testing_policy,contact_tracing,emergency_investment_in_healthcare,investment_in_vaccines,facial_coverings,vaccination_policy,stringency_index
0,2020-01-02,AE,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2020-01-03,AE,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2020-01-04,AE,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2020-01-05,AE,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2020-01-06,AE,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0