In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

import pycountry

# Get the directory where the current notebook is located
current_dir = Path.cwd()

# Define the path relative to the notebook
data_path1 = current_dir.parent / "data" / "epidemiology.csv" #This file contains the epidemiological data, including the number of cases, deaths, and recoveries for each country and date.
data_path2 = current_dir.parent / "data" / "oxford-government-response.csv" #This file contains the Oxford COVID-19 Government Response Tracker data, which includes various indicators of government responses to the pandemic, such as school closures, travel restrictions, and public information campaigns.
data_path3 = current_dir.parent / "data" / "vaccinations.csv" #This file contains vaccination data, including the number of vaccinations administered, the percentage of the population vaccinated, and the types of vaccines used in each country.
data_path4 = current_dir.parent / "data" / "daily-tests-per-thousand-people-smoothed-7-day.csv" #This file contains data on the number of daily tests per thousand people, smoothed over a 7-day period.

In [2]:
# Load the datasets
data1=pd.read_csv(data_path1) #epedemiology data
data2=pd.read_csv(data_path2) #government response data
data3=pd.read_csv(data_path3) #vaccination data
data4=pd.read_csv(data_path4) #testing data

In [3]:
#Examine the first few rows of the datasets
data1.head(2)

,date,location_key,new_confirmed,new_deceased,new_recovered,new_tested,cumulative_confirmed,cumulative_deceased,cumulative_recovered,cumulative_tested
0,2020-01-01,AD,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN
1,2020-01-02,AD,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN

In [4]:
data2.head(2)

,date,location_key,school_closing,workplace_closing,cancel_public_events,restrictions_on_gatherings,public_transport_closing,stay_at_home_requirements,restrictions_on_internal_movement,international_travel_controls,...,fiscal_measures,international_support,public_information_campaigns,testing_policy,contact_tracing,emergency_investment_in_healthcare,investment_in_vaccines,facial_coverings,vaccination_policy,stringency_index
0,2020-01-01,AD,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2020-01-02,AD,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
data3.head(2)

,date,location_key,new_persons_vaccinated,cumulative_persons_vaccinated,new_persons_fully_vaccinated,cumulative_persons_fully_vaccinated,new_vaccine_doses_administered,cumulative_vaccine_doses_administered,new_persons_vaccinated_pfizer,cumulative_persons_vaccinated_pfizer,...,new_persons_fully_vaccinated_janssen,cumulative_persons_fully_vaccinated_janssen,new_vaccine_doses_administered_janssen,cumulative_vaccine_doses_administered_janssen,new_persons_vaccinated_sinovac,total_persons_vaccinated_sinovac,new_persons_fully_vaccinated_sinovac,total_persons_fully_vaccinated_sinovac,new_vaccine_doses_administered_sinovac,total_vaccine_doses_administered_sinovac
0,2021-01-25,AD,NaN,576.0,NaN,NaN,NaN,576.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021-02-01,AD,460.0,1036.0,NaN,NaN,460.0,1036.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
data4.head(2)

,Entity,Code,Day,Daily tests per thousand people (7-day smoothed),Daily tests per thousand people (7-day smoothed) (Annotations)
0,Afghanistan,AFG,2022-02-05,0.032,NaN
1,Afghanistan,AFG,2022-02-06,0.032,NaN

In [7]:
# Filter for country codes only (leave out regional data)
# Return unique location keys for dataset 1
def get_unique_location_keys(data1):
    return list(set(data1["location_key"].dropna().str.split("_").str[0]))

unique_Country_Keys1 = get_unique_location_keys(data1)

print(unique_Country_Keys1)
print(len(unique_Country_Keys1))

['SN', 'PR', 'LC', 'CY', 'LA', 'UY', 'FI', 'UZ', 'FJ', 'SX', 'NI', 'RE', 'PL', 'IE', 'MN', 'NO', 'JM', 'EC', 'FM', 'LS', 'ME', 'CO', 'MR', 'TG', 'KG', 'GU', 'LR', 'PH', 'DO', 'GT', 'NU', 'AL', 'DK', 'SO', 'AI', 'RO', 'BG', 'IS', 'CN', 'AU', 'MG', 'TR', 'BR', 'VG', 'TD', 'KR', 'CV', 'VU', 'IT', 'KY', 'BJ', 'HU', 'HT', 'AS', 'BN', 'ES', 'MO', 'PT', 'RW', 'MS', 'CK', 'MK', 'SY', 'SZ', 'BD', 'KN', 'OM', 'SG', 'DE', 'SH', 'AF', 'ID', 'FO', 'RS', 'BZ', 'PG', 'GI', 'GR', 'MU', 'MA', 'VI', 'DM', 'PF', 'NR', 'WS', 'LV', 'KZ', 'MD', 'WF', 'CW', 'GM', 'LK', 'CD', 'LT', 'HN', 'SC', 'KI', 'JE', 'TT', 'QA', 'TL', 'GN', 'BO', 'BI', 'EH', 'BS', 'IR', 'MT', 'JO', 'BE', 'TC', 'LB', 'MC', 'PK', 'AR', 'GA', 'VN', 'XK', 'AZ', 'YT', 'NE', 'MP', 'MZ', 'BB', 'CF', 'PW', 'BW', 'CI', 'JP', 'KW', 'KP', 'HK', 'CZ', 'NC', 'GW', 'TV', 'SL', 'GB', 'UG', 'BT', 'TO', 'LY', 'CL', 'PE', 'GQ', 'TJ', 'VC', 'FK', 'SR', 'MY', 'BF', 'PS', 'MW', 'ET', 'TH', 'CH', 'ER', 'UA', 'TK', 'DJ', 'NZ', 'ST', 'PA', 'DZ', 'ZW', 'IN', 'AE', 'TW', 'NL', 'AM', 'TM', 'US', 'MV', 'NG', 'CR', 'LI', 'ML', 'RU', 'AG', 'GD', 'EE', 'TZ', 'GF', 'AD', 'BY', 'BM', 'CU', 'GL', 'SA', 'VE', 'CM', 'KH', 'NP', 'GH', 'IQ', 'CA', 'EG', 'FR', 'SS', 'HR', 'TN', 'SV', 'YE', 'MX', 'IM', 'GY', 'ZM', 'AO', 'AT', 'SI', 'CG', 'GG', 'SD', 'SK', 'BA', 'AW', 'MQ', 'KM', 'GE', 'KE', 'MM', 'PN', 'PY', 'VA', 'LU', 'ZA', 'MH', 'SM', 'SB', 'SE', 'BH', 'IL']
232

In [8]:
# Filter for country codes only (leave out regional data)
# Return unique location keys for dataset 2
def get_unique_location_keys(data2):
    return list(set(data2["location_key"].dropna().str.split("_").str[0]))

unique_Country_Keys2 = get_unique_location_keys(data2)

print(unique_Country_Keys2)
print(len(unique_Country_Keys2))

['SN', 'PR', 'CY', 'LA', 'UY', 'FI', 'UZ', 'FJ', 'NI', 'PL', 'IE', 'MN', 'NO', 'JM', 'EC', 'LS', 'CO', 'MR', 'TG', 'KG', 'GU', 'LR', 'PH', 'DO', 'GT', 'SO', 'AL', 'DK', 'RO', 'BG', 'IS', 'CN', 'AU', 'MG', 'TR', 'BR', 'TD', 'KR', 'CV', 'VU', 'IT', 'BJ', 'HU', 'HT', 'BN', 'ES', 'MO', 'PT', 'RW', 'SY', 'SZ', 'BD', 'SG', 'OM', 'DE', 'AF', 'ID', 'FO', 'RS', 'BZ', 'PG', 'GR', 'MU', 'MA', 'VI', 'DM', 'LV', 'KZ', 'MD', 'GM', 'LK', 'CD', 'LT', 'HN', 'SC', 'KI', 'TT', 'QA', 'TL', 'GN', 'BO', 'BI', 'BS', 'IR', 'MT', 'JO', 'BE', 'LB', 'MC', 'PK', 'AR', 'GA', 'VN', 'XK', 'AZ', 'NE', 'MZ', 'BB', 'CF', 'BW', 'CI', 'JP', 'KW', 'HK', 'CZ', 'SL', 'GB', 'UG', 'BT', 'TO', 'LY', 'CL', 'PE', 'TJ', 'SR', 'MY', 'BF', 'PS', 'MW', 'ET', 'TH', 'CH', 'ER', 'UA', 'DJ', 'NZ', 'PA', 'DZ', 'ZW', 'IN', 'AE', 'TW', 'NL', 'TM', 'US', 'NG', 'CR', 'LI', 'ML', 'RU', 'GD', 'EE', 'TZ', 'AD', 'BY', 'BM', 'CU', 'GL', 'SA', 'VE', 'CM', 'KH', 'NP', 'GH', 'IQ', 'CA', 'EG', 'FR', 'SS', 'HR', 'TN', 'SV', 'YE', 'MX', 'GY', 'ZM', 'AO', 'AT', 'SI', 'CG', 'SD', 'SK', 'BA', 'AW', 'KM', 'GE', 'KE', 'MM', 'PY', 'LU', 'ZA', 'SM', 'SB', 'SE', 'BH', 'IL']
186

In [9]:
# Function to convert location_key from ISO-2 to ISO-3 format
def convert_iso2_to_iso3(location_key):
    """
    Convert a location_key from ISO-2 to ISO-3 format.
    """
    if pd.isna(location_key):
        return location_key
    
    parts = location_key.split("_")
    iso2 = parts[0]
    
    country = pycountry.countries.get(alpha_2=iso2)
    
    if country:
        parts[0] = country.alpha_3  # Replace ISO-2 with ISO-3
        return "_".join(parts)
    else:
        return location_key  # Return original if not found (e.g. 'XK' for Kosovo)

In [10]:
# Pulling out focus data from dataset 1 
# Filtering dataset to only include data by country
focus_data1 = data1[data1['location_key'].isin(unique_Country_Keys1)]
focus_data1.info()

<class 'pandas.DataFrame'>
Index: 226892 entries, 0 to 12525824
Data columns (total 10 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   date                  226892 non-null  str
 1   location_key          226892 non-null  str
 2   new_confirmed         226799 non-null  float64
 3   new_deceased          226624 non-null  float64
 4   new_recovered         15712 non-null   float64
 5   new_tested            76705 non-null   float64
 6   cumulative_confirmed  226798 non-null  float64
 7   cumulative_deceased   226625 non-null  float64
 8   cumulative_recovered  14759 non-null   float64
 9   cumulative_tested     80010 non-null   float64
dtypes: float64(8), str(2)
memory usage: 19.0 MB

In [11]:
# Pulling out focus data from dataset 2
# Filtering dataset to only include data by country
focus_data2 = data2[data2['location_key'].isin(unique_Country_Keys2)]
focus_data2.info()

# Pulling out focus data from dataset 3 (vaccination data)
# Filter for country codes only (leave out regional data)
unique_Country_Keys3 = list(set(data3['location_key'].dropna().str.split('_').str[0]))
focus_data3 = data3[data3['location_key'].isin(unique_Country_Keys3)]
focus_data3.info()

<class 'pandas.DataFrame'>
Index: 171200 entries, 0 to 303968
Data columns (total 22 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   date                                171200 non-null  str
 1   location_key                        171200 non-null  str
 2   school_closing                      170800 non-null  float64
 3   workplace_closing                   170803 non-null  float64
 4   cancel_public_events                170785 non-null  float64
 5   restrictions_on_gatherings          170781 non-null  float64
 6   public_transport_closing            170785 non-null  float64
 7   stay_at_home_requirements           170780 non-null  float64
 8   restrictions_on_internal_movement   170765 non-null  float64
 9   international_travel_controls       170787 non-null  float64
 10  income_support                      170733 non-null  float64
 11  debt_relief                         170747 non-null  float64
 12  fiscal_measures                     105697 non-null  float64
 13  international_support               105777 non-null  float64
 14  public_information_campaigns        170791 non-null  float64
 15  testing_policy                      170767 non-null  float64
 16  contact_tracing                     170708 non-null  float64
 17  emergency_investment_in_healthcare  105659 non-null  float64
 18  investment_in_vaccines              166826 non-null  float64
 19  facial_coverings                    171036 non-null  float64
 20  vaccination_policy                  171091 non-null  float64
 21  stringency_index                    170751 non-null  float64
dtypes: float64(20), str(2)
memory usage: 30.0 MB
<class 'pandas.DataFrame'>
Index: 55873 entries, 0 to 2545117
Data columns (total 32 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   date                                           55873 non-null  str
 1   location_key                                   55873 non-null  str
 2   new_persons_vaccinated                         54577 non-null  float64
 3   cumulative_persons_vaccinated                  51786 non-null  float64
 4   new_persons_fully_vaccinated                   52513 non-null  float64
 5   cumulative_persons_fully_vaccinated            50019 non-null  float64
 6   new_vaccine_doses_administered                 54922 non-null  float64
 7   cumulative_vaccine_doses_administered          54431 non-null  float64
 8   new_persons_vaccinated_pfizer                  569 non-null    float64
 9   cumulative_persons_vaccinated_pfizer           569 non-null    float64
 10  new_persons_fully_vaccinated_pfizer            1111 non-null   float64
 11  cumulative_persons_fully_vaccinated_pfizer     1112 non-null   float64
 12  new_vaccine_doses_administered_pfizer          542 non-null    float64
 13  cumulative_vaccine_doses_administered_pfizer   543 non-null    float64
 14  new_persons_vaccinated_moderna                 0 non-null      float64
 15  cumulative_persons_vaccinated_moderna          0 non-null      float64
 16  new_persons_fully_vaccinated_moderna           542 non-null    float64
 17  cumulative_persons_fully_vaccinated_moderna    543 non-null    float64
 18  new_vaccine_doses_administered_moderna         542 non-null    float64
 19  cumulative_vaccine_doses_administered_moderna  543 non-null    float64
 20  new_persons_vaccinated_janssen                 0 non-null      float64
 21  cumulative_persons_vaccinated_janssen          0 non-null      float64
 22  new_persons_fully_vaccinated_janssen           542 non-null    float64
 23  cumulative_persons_fully_vaccinated_janssen    543 non-null    float64
 24  new_vaccine_doses_administered_janssen         542 non-null    float64
 25  cumulative_vaccine_doses_administered_janssen  543 non-null    float64
 26  new_persons_vaccinated_sinovac                 569 non-null    float64
 27  total_persons_vaccinated_sinovac               569 non-null    float64
 28  new_persons_fully_vaccinated_sinovac           0 non-null      float64
 29  total_persons_fully_vaccinated_sinovac         0 non-null      float64
 30  new_vaccine_doses_administered_sinovac         0 non-null      float64
 31  total_vaccine_doses_administered_sinovac       0 non-null      float64
dtypes: float64(30), str(2)
memory usage: 14.1 MB

In [12]:
# Number of days recorded for each country in dataset 1
focus_data1_numberOfDays=focus_data1['location_key'].value_counts()
focus_data1_numberOfDays

location_key
AU    990
TH    990
AT    989
BE    989
BR    989
     ...
ZW    987
TW    974
HK    693
MO    152
EH      1
Name: count, Length: 232, dtype: int64

In [13]:
# Number of days recorded for each country in datset 2
focus_data2_numberOfDays=focus_data2['location_key'].value_counts()
focus_data2_numberOfDays

location_key
AF    938
AU    938
CL    938
HR    938
MT    938
     ...
GU    899
PS    898
CZ    881
KM    342
GD     87
Name: count, Length: 186, dtype: int64

In [14]:
#Analyzing the distribution of the number of days recorded for each country in both datasets using boxplot statistics

def boxplot_stats(series):
    q1 = series.quantile(0.25)
    median = series.quantile(0.5)
    q3 = series.quantile(0.75)
    iqr = q3 - q1

    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr

    outliers = series[(series < lower_bound) | (series > upper_bound)]

    return {
        "min": series.min(),
        "Q1": q1,
        "median": median,
        "Q3": q3,
        "max": series.max(),
        "IQR": iqr,
        "lower_bound": lower_bound,
        "upper_bound": upper_bound,
        "num_outliers": len(outliers)
    }

# Apply to both datasets
stats1 = boxplot_stats(focus_data1_numberOfDays)
stats2 = boxplot_stats(focus_data2_numberOfDays)

# Convert to DataFrame for clean display
summary = pd.DataFrame([stats1, stats2], 
                       index=["Dataset 1", "Dataset 2"])

print(summary)

           min     Q1  median     Q3  max   IQR  lower_bound  upper_bound  \
Dataset 1    1  987.0   987.0  987.0  990   0.0        987.0        987.0
Dataset 2   87  923.0   930.0  937.0  938  14.0        902.0        958.0

           num_outliers
Dataset 1            26
Dataset 2             9

In [15]:
# Using statistics to filter the data
# We will keep countries that have number of days recorded >= Q1 (first quartile)

# For dataset 1
q1_dataset1 = stats1['Q1']
# Filtering dataset to exclude countries with observation numbers below Q1
filtered_countries_1 = focus_data1_numberOfDays[focus_data1_numberOfDays >= q1_dataset1].index.tolist()
filtered_focus_data1 = focus_data1[focus_data1['location_key'].isin(filtered_countries_1)]

print(f"Dataset 1 - Q1 threshold: {q1_dataset1}")
print(f"Countries kept (>= Q1): {len(filtered_countries_1)}")
print(f"Filtered data1 shape: {filtered_focus_data1.shape}")

Dataset 1 - Q1 threshold: 987.0
Countries kept (>= Q1): 228
Filtered data1 shape: (225072, 10)

# Epidemiologi_global_covid 
### - Checking for potential missing data

In [16]:
# Check that each country has at least one entity value for every data column in filtered_focus_data1_common.
# This helps verify that each country doesn't have systematic missingness.

def check_country_column_non_missing(df, country_col='location_key', threshold=1):
    """Return non-missing counts, missing-category flags, and a summary per country."""
    # Count non-missing entries per country and column
    non_missing_counts = df.groupby(country_col).apply(lambda group: group.notna().sum())
    if country_col in non_missing_counts.columns:
        non_missing_counts = non_missing_counts.drop(columns=[country_col])

    # Identify columns where the count of non-missing values is below the threshold
    missing_flags = (non_missing_counts < threshold)
    missing_matrix = missing_flags.astype(object)
    missing_matrix[missing_flags] = 'Non'
    missing_matrix[~missing_flags] = ''

    # Build a summary table and list missing categories for each country
    missing_categories = {
        country: non_missing_counts.columns[missing_flags.loc[country]].tolist()
        for country in non_missing_counts.index
    }

    summary = pd.DataFrame({
        'has_minimum_per_column': [len(categories) == 0 for categories in missing_categories.values()],
        'missing_columns': [', '.join(categories) if categories else '' for categories in missing_categories.values()]
    }, index=non_missing_counts.index)

    return non_missing_counts, missing_flags, missing_matrix, summary, missing_categories

# Run the check on filtered_focus_data1_common
non_missing_counts, missing_flags, missing_matrix, country_summary, missing_categories = check_country_column_non_missing(filtered_focus_data1)

print("\nSummary of missing data per category:")
missing_per_category = (missing_matrix == 'Non').sum()
print(missing_per_category)

if country_summary['has_minimum_per_column'].all():
    print("\nAll countries have at least one non-missing value in every column.")
else:
    print("\nCountries with missing entities in one or more categories:")
    for country, categories in missing_categories.items():
        if categories:
            print(f"- {country}: missing data in {', '.join(categories)}")

Summary of missing data per category:
date                      0
new_confirmed             0
new_deceased              0
new_recovered           210
new_tested               75
cumulative_confirmed      0
cumulative_deceased       0
cumulative_recovered    210
cumulative_tested        46
dtype: int64

Countries with missing entities in one or more categories:
- AD: missing data in new_recovered, new_tested, cumulative_recovered
- AE: missing data in new_recovered, cumulative_recovered
- AF: missing data in new_recovered, new_tested, cumulative_recovered
- AG: missing data in new_recovered, new_tested, cumulative_recovered
- AI: missing data in new_recovered, new_tested, cumulative_recovered
- AL: missing data in new_recovered, cumulative_recovered
- AM: missing data in new_recovered, cumulative_recovered
- AO: missing data in new_recovered, cumulative_recovered
- AR: missing data in new_recovered, cumulative_recovered
- AS: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- AW: missing data in new_recovered, cumulative_recovered
- AZ: missing data in new_recovered, cumulative_recovered
- BA: missing data in new_recovered, cumulative_recovered
- BB: missing data in new_recovered, cumulative_recovered
- BD: missing data in new_recovered, cumulative_recovered
- BE: missing data in new_recovered, cumulative_recovered
- BF: missing data in new_recovered, cumulative_recovered
- BG: missing data in new_recovered, cumulative_recovered
- BH: missing data in new_recovered, cumulative_recovered
- BI: missing data in new_recovered, cumulative_recovered
- BJ: missing data in new_recovered, new_tested, cumulative_recovered
- BM: missing data in new_recovered, cumulative_recovered
- BN: missing data in new_recovered, cumulative_recovered
- BO: missing data in new_recovered, cumulative_recovered
- BS: missing data in new_recovered, cumulative_recovered
- BT: missing data in new_recovered, cumulative_recovered
- BW: missing data in new_recovered, cumulative_recovered
- BY: missing data in new_recovered, cumulative_recovered
- BZ: missing data in new_recovered, cumulative_recovered
- CA: missing data in new_recovered, cumulative_recovered
- CD: missing data in new_recovered, new_tested, cumulative_recovered
- CF: missing data in new_recovered, new_tested, cumulative_recovered
- CG: missing data in new_recovered, new_tested, cumulative_recovered
- CH: missing data in new_recovered, cumulative_recovered
- CI: missing data in new_recovered, cumulative_recovered
- CK: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- CM: missing data in new_recovered, new_tested, cumulative_recovered
- CN: missing data in new_tested
- CR: missing data in new_recovered, cumulative_recovered
- CU: missing data in new_recovered, cumulative_recovered
- CV: missing data in new_recovered, cumulative_recovered, cumulative_tested
- CW: missing data in new_recovered, cumulative_recovered
- CY: missing data in new_recovered, cumulative_recovered
- DE: missing data in new_recovered, new_tested, cumulative_recovered
- DJ: missing data in new_recovered, cumulative_recovered
- DK: missing data in new_recovered, cumulative_recovered
- DM: missing data in new_recovered, cumulative_recovered
- DO: missing data in new_recovered, cumulative_recovered
- DZ: missing data in new_recovered, new_tested, cumulative_recovered
- EC: missing data in new_recovered, cumulative_recovered
- EE: missing data in new_recovered, cumulative_recovered
- EG: missing data in new_recovered, new_tested, cumulative_recovered
- ER: missing data in new_recovered, new_tested, cumulative_recovered
- ES: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- ET: missing data in new_recovered, cumulative_recovered
- FI: missing data in new_recovered, cumulative_recovered
- FJ: missing data in new_recovered, cumulative_recovered
- FK: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- FM: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- FO: missing data in new_recovered, cumulative_recovered
- GA: missing data in new_recovered, cumulative_recovered
- GB: missing data in new_recovered, cumulative_recovered
- GD: missing data in new_recovered, cumulative_recovered
- GE: missing data in new_recovered, cumulative_recovered
- GF: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- GG: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- GH: missing data in new_recovered, cumulative_recovered
- GI: missing data in new_recovered, cumulative_recovered
- GL: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- GM: missing data in new_recovered, new_tested, cumulative_recovered
- GN: missing data in new_recovered, new_tested, cumulative_recovered
- GQ: missing data in new_recovered, cumulative_recovered
- GR: missing data in new_recovered, cumulative_recovered
- GT: missing data in new_recovered, cumulative_recovered
- GU: missing data in new_recovered, cumulative_recovered
- GW: missing data in new_recovered, cumulative_recovered
- GY: missing data in new_recovered, new_tested, cumulative_recovered
- HN: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- HR: missing data in new_recovered, cumulative_recovered
- HT: missing data in new_recovered, cumulative_recovered
- HU: missing data in new_recovered, cumulative_recovered
- IE: missing data in new_recovered, cumulative_recovered
- IL: missing data in new_recovered, cumulative_recovered
- IM: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- IN: missing data in new_recovered, cumulative_recovered
- IQ: missing data in new_recovered, cumulative_recovered
- IR: missing data in new_recovered, cumulative_recovered
- IS: missing data in new_recovered, cumulative_recovered
- JE: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- JM: missing data in new_recovered, cumulative_recovered
- JO: missing data in new_recovered, cumulative_recovered
- JP: missing data in new_recovered, cumulative_recovered
- KE: missing data in new_recovered, cumulative_recovered
- KG: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- KH: missing data in new_recovered, cumulative_recovered
- KI: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- KM: missing data in new_recovered, new_tested, cumulative_recovered
- KN: missing data in new_recovered, cumulative_recovered
- KP: missing data in new_recovered, cumulative_recovered
- KR: missing data in new_recovered, cumulative_recovered
- KW: missing data in new_recovered, cumulative_recovered
- KY: missing data in new_recovered, cumulative_recovered
- KZ: missing data in new_recovered, cumulative_recovered
- LA: missing data in new_recovered, cumulative_recovered
- LB: missing data in new_recovered, cumulative_recovered
- LC: missing data in new_recovered, cumulative_recovered
- LK: missing data in new_recovered, cumulative_recovered
- LR: missing data in new_recovered, new_tested, cumulative_recovered
- LS: missing data in new_recovered, cumulative_recovered
- LT: missing data in new_recovered, cumulative_recovered
- LU: missing data in new_recovered, cumulative_recovered
- LV: missing data in new_recovered, cumulative_recovered
- LY: missing data in new_recovered, cumulative_recovered, cumulative_tested
- MA: missing data in new_recovered, cumulative_recovered
- MC: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- MD: missing data in new_recovered, cumulative_recovered, cumulative_tested
- ME: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- MG: missing data in new_recovered, cumulative_recovered
- MH: missing data in new_recovered, cumulative_recovered
- MK: missing data in new_recovered, cumulative_recovered
- ML: missing data in new_recovered, cumulative_recovered
- MM: missing data in new_recovered, cumulative_recovered
- MN: missing data in new_recovered, cumulative_recovered
- MP: missing data in new_recovered, cumulative_recovered
- MQ: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- MR: missing data in new_recovered, cumulative_recovered
- MS: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- MT: missing data in new_recovered, cumulative_recovered
- MU: missing data in new_recovered, new_tested, cumulative_recovered
- MV: missing data in new_recovered, cumulative_recovered
- MW: missing data in new_recovered, cumulative_recovered
- MX: missing data in new_recovered, cumulative_recovered
- MZ: missing data in new_recovered, cumulative_recovered
- NC: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- NE: missing data in new_recovered, cumulative_recovered
- NG: missing data in new_recovered, cumulative_recovered
- NI: missing data in new_recovered, new_tested, cumulative_recovered
- NL: missing data in new_recovered, cumulative_recovered
- NO: missing data in new_recovered, cumulative_recovered
- NP: missing data in new_recovered, cumulative_recovered
- NR: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- NU: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- NZ: missing data in new_recovered, cumulative_recovered
- OM: missing data in new_recovered, new_tested, cumulative_recovered
- PA: missing data in new_recovered, cumulative_recovered
- PE: missing data in new_recovered, new_tested, cumulative_recovered
- PF: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- PG: missing data in new_recovered, new_tested, cumulative_recovered
- PK: missing data in new_recovered, cumulative_recovered
- PL: missing data in new_recovered, cumulative_recovered
- PN: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- PR: missing data in new_recovered, cumulative_recovered
- PS: missing data in new_recovered, cumulative_recovered, cumulative_tested
- PW: missing data in new_recovered, new_tested, cumulative_recovered
- PY: missing data in new_recovered, cumulative_recovered
- QA: missing data in new_recovered, cumulative_recovered
- RE: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- RO: missing data in new_tested
- RS: missing data in new_recovered, cumulative_recovered
- RU: missing data in new_recovered, cumulative_recovered
- RW: missing data in new_recovered, cumulative_recovered
- SA: missing data in new_recovered, cumulative_recovered
- SB: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- SC: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- SD: missing data in new_recovered, new_tested, cumulative_recovered
- SE: missing data in new_recovered, cumulative_recovered
- SG: missing data in new_recovered, cumulative_recovered, cumulative_tested
- SH: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- SK: missing data in new_recovered, cumulative_recovered
- SL: missing data in new_recovered, cumulative_recovered
- SM: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- SN: missing data in new_recovered, cumulative_recovered
- SO: missing data in new_recovered, new_tested, cumulative_recovered
- SR: missing data in new_recovered, cumulative_recovered
- SS: missing data in new_recovered, cumulative_recovered
- ST: missing data in new_recovered, cumulative_recovered
- SV: missing data in new_recovered, cumulative_recovered
- SX: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- SY: missing data in new_recovered, new_tested, cumulative_recovered
- SZ: missing data in new_recovered, cumulative_recovered
- TC: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- TD: missing data in new_recovered, new_tested, cumulative_recovered
- TG: missing data in new_recovered, cumulative_recovered
- TJ: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- TK: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- TL: missing data in new_recovered, cumulative_recovered
- TM: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- TN: missing data in new_recovered, cumulative_recovered
- TO: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- TR: missing data in new_recovered, cumulative_recovered
- TT: missing data in new_recovered, cumulative_recovered
- TV: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- TZ: missing data in new_recovered, new_tested, cumulative_recovered
- UG: missing data in new_recovered, cumulative_recovered
- US: missing data in new_recovered, cumulative_recovered
- UY: missing data in new_recovered, cumulative_recovered
- UZ: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- VA: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- VC: missing data in new_recovered, cumulative_recovered
- VE: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- VG: missing data in new_recovered, new_tested, cumulative_recovered
- VI: missing data in new_recovered, cumulative_recovered
- VN: missing data in new_recovered, cumulative_recovered
- VU: missing data in new_recovered, new_tested, cumulative_recovered
- WF: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- WS: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- XK: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- YE: missing data in new_recovered, new_tested, cumulative_recovered
- YT: missing data in new_recovered, new_tested, cumulative_recovered, cumulative_tested
- ZA: missing data in new_recovered, cumulative_recovered
- ZM: missing data in new_recovered, cumulative_recovered
- ZW: missing data in new_recovered, cumulative_recovered

In [17]:
# Function to remove 'new_recovered' and 'cumulative_recovered' columns from the dataframe
def remove_recovered_columns(df):
    """
    Remove 'new_recovered' and 'cumulative_recovered' columns if they exist in the dataframe.
    """
    columns_to_remove = ['new_recovered', 'cumulative_recovered']
    df = df.drop(columns=[col for col in columns_to_remove if col in df.columns], errors='ignore')
    return df

# Apply the function to filtered_focus_data1_common
filtered_focus_data1_common = remove_recovered_columns(filtered_focus_data1)

print(f"After removing columns with too few datapoints, shape: {filtered_focus_data1_common.shape}")
print("Columns remaining:", list(filtered_focus_data1_common.columns))

After removing columns with too few datapoints, shape: (225072, 8)
Columns remaining: ['date', 'location_key', 'new_confirmed', 'new_deceased', 'new_tested', 'cumulative_confirmed', 'cumulative_deceased', 'cumulative_tested']

### - Streamlining data to include same dates

In [18]:
# For dataset 1
# Finding the first common observation date shared for all of the countries to make the comparison fair

filtered_focus_data1 = filtered_focus_data1.copy()

filtered_focus_data1['date'] = pd.to_datetime(filtered_focus_data1['date'].astype('string'), errors='coerce').dt.normalize()

min_dates_1 = filtered_focus_data1.groupby('location_key')['date'].min()
max_dates_1 = filtered_focus_data1.groupby('location_key')['date'].max()

first_common_1 = min_dates_1.max()
last_common_1 = max_dates_1.min()

print(f"First common date: {first_common_1}")
print(f"Last common date: {last_common_1}")

# Filtering the filtered_focus_data1 to only include this data interval
filtered_focus_data1_common = filtered_focus_data1[
    (filtered_focus_data1['date'] >= first_common_1) &
    (filtered_focus_data1['date'] <= last_common_1)
].copy()

print(f"filtered_focus_data1_common shape: {filtered_focus_data1_common.shape}")

# Investigate if some dates are missing for some countries. Print the dates and countries missing for the date interval

date_range = pd.date_range(start=first_common_1, end=last_common_1, freq='D')

missing_by_country_1 = {}
for country, group in filtered_focus_data1_common.groupby('location_key'):
    missing_dates = date_range.difference(pd.DatetimeIndex(group['date']))
    if len(missing_dates):
        missing_by_country_1[country] = missing_dates

if missing_by_country_1:
    print("\nMissing dates in filtered_focus_data1_common:")
    for country, missing_dates in missing_by_country_1.items():
        print(f"{country}: {len(missing_dates)} missing dates (first few: {missing_dates[:5].tolist()})")
else:
    print("\nNo missing dates found in filtered_focus_data1_common.")

First common date: 2020-01-02 00:00:00
Last common date: 2022-09-13 00:00:00
filtered_focus_data1_common shape: (224808, 10)

No missing dates found in filtered_focus_data1_common.

### - Saving the cleaned dataset

In [19]:
#Saving this filterede data for data 1 as a CSV file
output_path = current_dir.parent / 'data' / 'epidemiologi_global_covid_data.csv'
filtered_focus_data1_common.to_csv(output_path, index=False)
print(f"\nSaved merged dataset to: {output_path}")

filtered_focus_data1_common.head()

Saved merged dataset to: c:\Users\Lenovo\OneDrive - Danmarks Tekniske Universitet\02806 Social data analysis and visualization\final_project\data\epidemiologi_global_covid_data.csv

,date,location_key,new_confirmed,new_deceased,new_recovered,new_tested,cumulative_confirmed,cumulative_deceased,cumulative_recovered,cumulative_tested
1,2020-01-02,AD,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN
2,2020-01-03,AD,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN
3,2020-01-04,AD,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN
4,2020-01-05,AD,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN
5,2020-01-06,AD,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN

# Merged data (Dataset 1 and Dataset 2) 
### - Streamlining data to include same dates

In [20]:
# Apply the convert_iso2_to_iso3 function to both datasets
focus_data1["location_key"] = focus_data1["location_key"].apply(convert_iso2_to_iso3)
focus_data2["location_key"] = focus_data2["location_key"].apply(convert_iso2_to_iso3)
focus_data3["location_key"] = focus_data3["location_key"].apply(convert_iso2_to_iso3)

In [21]:
# Merge epidemiology and Oxford government response datasets on date + location_key
merged_data1 = focus_data1.merge(
    focus_data2,
    on=['date', 'location_key'],
    how='inner',
    validate='one_to_one'
)

print(f"focus_data1 shape: {focus_data1.shape}")
print(f"focus_data2 shape: {focus_data2.shape}")
print(f"Merged shape:      {merged_data1.shape}")

focus_data1 shape: (226892, 10)
focus_data2 shape: (171200, 22)
Merged shape:      (170140, 30)

In [22]:
# Apply the function to merged_data
merged_data1 = remove_recovered_columns(merged_data1)

In [23]:
merged_data1.info()

<class 'pandas.DataFrame'>
RangeIndex: 170140 entries, 0 to 170139
Data columns (total 28 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   date                                170140 non-null  str
 1   location_key                        170140 non-null  str
 2   new_confirmed                       170052 non-null  float64
 3   new_deceased                        169886 non-null  float64
 4   new_tested                          73354 non-null   float64
 5   cumulative_confirmed                170053 non-null  float64
 6   cumulative_deceased                 169888 non-null  float64
 7   cumulative_tested                   76225 non-null   float64
 8   school_closing                      169740 non-null  float64
 9   workplace_closing                   169743 non-null  float64
 10  cancel_public_events                169725 non-null  float64
 11  restrictions_on_gatherings          169721 non-null  float64
 12  public_transport_closing            169725 non-null  float64
 13  stay_at_home_requirements           169720 non-null  float64
 14  restrictions_on_internal_movement   169705 non-null  float64
 15  international_travel_controls       169727 non-null  float64
 16  income_support                      169673 non-null  float64
 17  debt_relief                         169687 non-null  float64
 18  fiscal_measures                     105108 non-null  float64
 19  international_support               105188 non-null  float64
 20  public_information_campaigns        169731 non-null  float64
 21  testing_policy                      169707 non-null  float64
 22  contact_tracing                     169648 non-null  float64
 23  emergency_investment_in_healthcare  105070 non-null  float64
 24  investment_in_vaccines              165881 non-null  float64
 25  facial_coverings                    169976 non-null  float64
 26  vaccination_policy                  170031 non-null  float64
 27  stringency_index                    169691 non-null  float64
dtypes: float64(26), str(2)
memory usage: 36.3 MB

In [24]:
# Number of days recorded for each country in merged data
merged_data_numberOfDays=merged_data1['location_key'].value_counts()
merged_data_numberOfDays

location_key
AFG    938
AUS    938
CHL    938
HRV    938
MLT    938
      ...
CZE    881
HKG    693
COM    342
MAC    133
GRD     87
Name: count, Length: 186, dtype: int64

In [25]:
# Analyzing the distribution of the number of days recorded for each country in merged_data using boxplot statistics

def boxplot_stats(series):
    q1 = series.quantile(0.25)
    median = series.quantile(0.5)
    q3 = series.quantile(0.75)
    iqr = q3 - q1

    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr

    outliers = series[(series < lower_bound) | (series > upper_bound)]

    return {
        "min": series.min(),
        "Q1": q1,
        "median": median,
        "Q3": q3,
        "max": series.max(),
        "IQR": iqr,
        "lower_bound": lower_bound,
        "upper_bound": upper_bound,
        "num_outliers": len(outliers)
    }

# Apply to merged data
stats = boxplot_stats(merged_data_numberOfDays)

# Convert to DataFrame for clean display
summary = pd.DataFrame([stats], 
                       index=["Merged Data"])

print(summary)

# Using statistics to filter the data
# We will keep countries that have number of days recorded >= Q1 (first quartile)

# For merged data
q1 = stats['Q1']

# Filtering dataset to exclude data with observation numbers below Q1
filtered_countries = merged_data_numberOfDays[merged_data_numberOfDays >= q1].index.tolist()
filtered_merged_data = merged_data1[merged_data1['location_key'].isin(filtered_countries)]

print(f"Merged Data - Q1 threshold: {q1}")
print(f"Countries kept (>= Q1): {len(filtered_countries)}")
print(f"Filtered merged data shape: {filtered_merged_data.shape}")

             min     Q1  median     Q3  max   IQR  lower_bound  upper_bound  \
Merged Data   87  923.0   930.0  937.0  938  14.0        902.0        958.0

             num_outliers
Merged Data            11
Merged Data - Q1 threshold: 923.0
Countries kept (>= Q1): 141
Filtered merged data shape: (131480, 28)

In [26]:
# For merged dataset
# Finding the first common observation date shared for all of the countries to make the comparison fair

filtered_merged_data = filtered_merged_data.copy()

filtered_merged_data['date'] = pd.to_datetime(filtered_merged_data['date'].astype('string'), errors='coerce').dt.normalize()

min_dates_merged = filtered_merged_data.groupby('location_key')['date'].min()
max_dates_merged = filtered_merged_data.groupby('location_key')['date'].max()

first_common_merged = min_dates_merged.max()
last_common_merged = max_dates_merged.min()

print(f"First common date: {first_common_merged}")
print(f"Last common date: {last_common_merged}")

# Filtering the filtered_merged_data to only include this data interval
filtered_merged_data_common = filtered_merged_data[
    (filtered_merged_data['date'] >= first_common_merged) &
    (filtered_merged_data['date'] <= last_common_merged)
].copy()

print(f"filtered_merged_data_common shape: {filtered_merged_data_common.shape}")

# Investigate if some dates are missing for some countries. Print the dates and countries missing for the date interval

date_range = pd.date_range(start=first_common_merged, end=last_common_merged, freq='D')

missing_by_country_merged = {}
for country, group in filtered_merged_data_common.groupby('location_key'):
    missing_dates = date_range.difference(pd.DatetimeIndex(group['date']))
    if len(missing_dates):
        missing_by_country_merged[country] = missing_dates

if missing_by_country_merged:
    print("\nMissing dates in filtered_merged_data_common:")
    for country, missing_dates in missing_by_country_merged.items():
        print(f"{country}: {len(missing_dates)} missing dates (first few: {missing_dates[:5].tolist()})")
else:
    print("\nNo missing dates found in filtered_merged_data_common.")

First common date: 2020-01-02 00:00:00
Last common date: 2022-07-11 00:00:00
filtered_merged_data_common shape: (130001, 28)

Missing dates in filtered_merged_data_common:
NGA: 1 missing dates (first few: [Timestamp('2022-07-11 00:00:00')])

### - Adding vaccination data

In [27]:
# Merge vaccination data into the filtered merged dataset

def merge_vaccination_data(main_df, vaccination_df):
    """
    Merge vaccination data into a COVID analysis dataframe
    on date and location_key.
    """
    main_df = main_df.copy()
    vax_data = vaccination_df.copy()

    main_df['date'] = pd.to_datetime(
        main_df['date'],
        errors='coerce'
    ).dt.normalize()

    vax_data['date'] = pd.to_datetime(
        vax_data['date'],
        errors='coerce'
    ).dt.normalize()

    merged_with_vax = main_df.merge(
    vax_data,
    on=['date', 'location_key'],
    how='left',
    validate='many_to_one'
    )

    return merged_with_vax

In [28]:
# Merge vaccination data into the filtered merged dataset

merged_data = merge_vaccination_data(filtered_merged_data_common, focus_data3)
merged_data.info()
print(f"Merged vaccination data shape: {merged_data.shape}")

<class 'pandas.DataFrame'>
RangeIndex: 130001 entries, 0 to 130000
Data columns (total 58 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   date                                           130001 non-null  datetime64[us]
 1   location_key                                   130001 non-null  str
 2   new_confirmed                                  130001 non-null  float64
 3   new_deceased                                   130001 non-null  float64
 4   new_tested                                     55074 non-null   float64
 5   cumulative_confirmed                           130001 non-null  float64
 6   cumulative_deceased                            130001 non-null  float64
 7   cumulative_tested                              58606 non-null   float64
 8   school_closing                                 129975 non-null  float64
 9   workplace_closing                              129976 non-null  float64
 10  cancel_public_events                           129969 non-null  float64
 11  restrictions_on_gatherings                     129968 non-null  float64
 12  public_transport_closing                       129968 non-null  float64
 13  stay_at_home_requirements                      129968 non-null  float64
 14  restrictions_on_internal_movement              129963 non-null  float64
 15  international_travel_controls                  129993 non-null  float64
 16  income_support                                 129917 non-null  float64
 17  debt_relief                                    129937 non-null  float64
 18  fiscal_measures                                81222 non-null   float64
 19  international_support                          81235 non-null   float64
 20  public_information_campaigns                   129973 non-null  float64
 21  testing_policy                                 129974 non-null  float64
 22  contact_tracing                                129905 non-null  float64
 23  emergency_investment_in_healthcare             81244 non-null   float64
 24  investment_in_vaccines                         127372 non-null  float64
 25  facial_coverings                               129939 non-null  float64
 26  vaccination_policy                             129930 non-null  float64
 27  stringency_index                               129962 non-null  float64
 28  new_persons_vaccinated                         34910 non-null   float64
 29  cumulative_persons_vaccinated                  33268 non-null   float64
 30  new_persons_fully_vaccinated                   33543 non-null   float64
 31  cumulative_persons_fully_vaccinated            31987 non-null   float64
 32  new_vaccine_doses_administered                 35073 non-null   float64
 33  cumulative_vaccine_doses_administered          34630 non-null   float64
 34  new_persons_vaccinated_pfizer                  503 non-null     float64
 35  cumulative_persons_vaccinated_pfizer           503 non-null     float64
 36  new_persons_fully_vaccinated_pfizer            503 non-null     float64
 37  cumulative_persons_fully_vaccinated_pfizer     503 non-null     float64
 38  new_vaccine_doses_administered_pfizer          0 non-null       float64
 39  cumulative_vaccine_doses_administered_pfizer   0 non-null       float64
 40  new_persons_vaccinated_moderna                 0 non-null       float64
 41  cumulative_persons_vaccinated_moderna          0 non-null       float64
 42  new_persons_fully_vaccinated_moderna           0 non-null       float64
 43  cumulative_persons_fully_vaccinated_moderna    0 non-null       float64
 44  new_vaccine_doses_administered_moderna         0 non-null       float64
 45  cumulative_vaccine_doses_administered_moderna  0 non-null       float64
 46  new_persons_vaccinated_janssen                 0 non-null       float64
 47  cumulative_persons_vaccinated_janssen          0 non-null       float64
 48  new_persons_fully_vaccinated_janssen           0 non-null       float64
 49  cumulative_persons_fully_vaccinated_janssen    0 non-null       float64
 50  new_vaccine_doses_administered_janssen         0 non-null       float64
 51  cumulative_vaccine_doses_administered_janssen  0 non-null       float64
 52  new_persons_vaccinated_sinovac                 503 non-null     float64
 53  total_persons_vaccinated_sinovac               503 non-null     float64
 54  new_persons_fully_vaccinated_sinovac           0 non-null       float64
 55  total_persons_fully_vaccinated_sinovac         0 non-null       float64
 56  new_vaccine_doses_administered_sinovac         0 non-null       float64
 57  total_vaccine_doses_administered_sinovac       0 non-null       float64
dtypes: datetime64[us](1), float64(56), str(1)
memory usage: 57.5 MB
Merged vaccination data shape: (130001, 58)

### - Checking for potentially missing data

In [29]:
# Check that each country has at least one entity value for every data column in filtered_merged_data_common.
# This helps verify that each country doesn't have systematic missingness.

def check_country_column_non_missing(df, country_col='location_key', threshold=1):
    """Return non-missing counts, missing-category flags, and a summary per country."""
    # Count non-missing entries per country and column
    non_missing_counts = df.groupby(country_col).apply(lambda group: group.notna().sum())
    if country_col in non_missing_counts.columns:
        non_missing_counts = non_missing_counts.drop(columns=[country_col])

    # Identify columns where the count of non-missing values is below the threshold
    missing_flags = (non_missing_counts < threshold)
    missing_matrix = missing_flags.astype(object)
    missing_matrix[missing_flags] = 'Non'
    missing_matrix[~missing_flags] = ''

    # Build a summary table and list missing categories for each country
    missing_categories = {
        country: non_missing_counts.columns[missing_flags.loc[country]].tolist()
        for country in non_missing_counts.index
    }

    summary = pd.DataFrame({
        'has_minimum_per_column': [len(categories) == 0 for categories in missing_categories.values()],
        'missing_columns': [', '.join(categories) if categories else '' for categories in missing_categories.values()]
    }, index=non_missing_counts.index)

    return non_missing_counts, missing_flags, missing_matrix, summary, missing_categories

# Run the check on filtered_merged_data_common
non_missing_counts, missing_flags, missing_matrix, country_summary, missing_categories = check_country_column_non_missing(merged_data)

print("\nSummary of missing data per category:")
missing_per_category = (missing_matrix == 'Non').sum()
print(missing_per_category)

if country_summary['has_minimum_per_column'].all():
    print("\nAll countries have at least one non-missing value in every column.")
else:
    print("\nCountries with missing entities in one or more categories:")
    for country, categories in missing_categories.items():
        if categories:
            print(f"- {country}: missing data in {', '.join(categories)}")

Summary of missing data per category:
date                                               0
new_confirmed                                      0
new_deceased                                       0
new_tested                                        37
cumulative_confirmed                               0
cumulative_deceased                                0
cumulative_tested                                 14
school_closing                                     0
workplace_closing                                  0
cancel_public_events                               0
restrictions_on_gatherings                         0
public_transport_closing                           0
stay_at_home_requirements                          0
restrictions_on_internal_movement                  0
international_travel_controls                      0
income_support                                     0
debt_relief                                        0
fiscal_measures                                    0
international_support                              0
public_information_campaigns                       0
testing_policy                                     0
contact_tracing                                    0
emergency_investment_in_healthcare                 0
investment_in_vaccines                             0
facial_coverings                                   0
vaccination_policy                                 0
stringency_index                                   0
new_persons_vaccinated                             3
cumulative_persons_vaccinated                      3
new_persons_fully_vaccinated                       3
cumulative_persons_fully_vaccinated                3
new_vaccine_doses_administered                     3
cumulative_vaccine_doses_administered              3
new_persons_vaccinated_pfizer                    140
cumulative_persons_vaccinated_pfizer             140
new_persons_fully_vaccinated_pfizer              140
cumulative_persons_fully_vaccinated_pfizer       140
new_vaccine_doses_administered_pfizer            141
cumulative_vaccine_doses_administered_pfizer     141
new_persons_vaccinated_moderna                   141
cumulative_persons_vaccinated_moderna            141
new_persons_fully_vaccinated_moderna             141
cumulative_persons_fully_vaccinated_moderna      141
new_vaccine_doses_administered_moderna           141
cumulative_vaccine_doses_administered_moderna    141
new_persons_vaccinated_janssen                   141
cumulative_persons_vaccinated_janssen            141
new_persons_fully_vaccinated_janssen             141
cumulative_persons_fully_vaccinated_janssen      141
new_vaccine_doses_administered_janssen           141
cumulative_vaccine_doses_administered_janssen    141
new_persons_vaccinated_sinovac                   140
total_persons_vaccinated_sinovac                 140
new_persons_fully_vaccinated_sinovac             141
total_persons_fully_vaccinated_sinovac           141
new_vaccine_doses_administered_sinovac           141
total_vaccine_doses_administered_sinovac         141
dtype: int64

Countries with missing entities in one or more categories:
- ABW: missing data in new_persons_vaccinated_pfizer, cumulative_persons_vaccinated_pfizer, new_persons_fully_vaccinated_pfizer, cumulative_persons_fully_vaccinated_pfizer, new_vaccine_doses_administered_pfizer, cumulative_vaccine_doses_administered_pfizer, new_persons_vaccinated_moderna, cumulative_persons_vaccinated_moderna, new_persons_fully_vaccinated_moderna, cumulative_persons_fully_vaccinated_moderna, new_vaccine_doses_administered_moderna, cumulative_vaccine_doses_administered_moderna, new_persons_vaccinated_janssen, cumulative_persons_vaccinated_janssen, new_persons_fully_vaccinated_janssen, cumulative_persons_fully_vaccinated_janssen, new_vaccine_doses_administered_janssen, cumulative_vaccine_doses_administered_janssen, new_persons_vaccinated_sinovac, total_persons_vaccinated_sinovac, new_persons_fully_vaccinated_sinovac, total_persons_fully_vaccinated_sinovac, new_vaccine_doses_administered_sinovac, total_vaccine_doses_administered_sinovac
- AFG: missing data in new_tested, new_persons_vaccinated_pfizer, cumulative_persons_vaccinated_pfizer, new_persons_fully_vaccinated_pfizer, cumulative_persons_fully_vaccinated_pfizer, new_vaccine_doses_administered_pfizer, cumulative_vaccine_doses_administered_pfizer, new_persons_vaccinated_moderna, cumulative_persons_vaccinated_moderna, new_persons_fully_vaccinated_moderna, cumulative_persons_fully_vaccinated_moderna, new_vaccine_doses_administered_moderna, cumulative_vaccine_doses_administered_moderna, new_persons_vaccinated_janssen, cumulative_persons_vaccinated_janssen, new_persons_fully_vaccinated_janssen, cumulative_persons_fully_vaccinated_janssen, new_vaccine_doses_administered_janssen, cumulative_vaccine_doses_administered_janssen, new_persons_vaccinated_sinovac, total_persons_vaccinated_sinovac, new_persons_fully_vaccinated_sinovac, total_persons_fully_vaccinated_sinovac, new_vaccine_doses_administered_sinovac, total_vaccine_doses_administered_sinovac
- ARE: missing data in new_persons_vaccinated_pfizer, cumulative_persons_vaccinated_pfizer, new_persons_fully_vaccinated_pfizer, cumulative_persons_fully_vaccinated_pfizer, new_vaccine_doses_administered_pfizer, cumulative_vaccine_doses_administered_pfizer, new_persons_vaccinated_moderna, cumulative_persons_vaccinated_moderna, new_persons_fully_vaccinated_moderna, cumulative_persons_fully_vaccinated_moderna, new_vaccine_doses_administered_moderna, cumulative_vaccine_doses_administered_moderna, new_persons_vaccinated_janssen, cumulative_persons_vaccinated_janssen, new_persons_fully_vaccinated_janssen, cumulative_persons_fully_vaccinated_janssen, new_vaccine_doses_administered_janssen, cumulative_vaccine_doses_administered_janssen, new_persons_vaccinated_sinovac, total_persons_vaccinated_sinovac, new_persons_fully_vaccinated_sinovac, total_persons_fully_vaccinated_sinovac, new_vaccine_doses_administered_sinovac, total_vaccine_doses_administered_sinovac
- ARG: missing data in new_persons_vaccinated_pfizer, cumulative_persons_vaccinated_pfizer, new_persons_fully_vaccinated_pfizer, cumulative_persons_fully_vaccinated_pfizer, new_vaccine_doses_administered_pfizer, cumulative_vaccine_doses_administered_pfizer, new_persons_vaccinated_moderna, cumulative_persons_vaccinated_moderna, new_persons_fully_vaccinated_moderna, cumulative_persons_fully_vaccinated_moderna, new_vaccine_doses_administered_moderna, cumulative_vaccine_doses_administered_moderna, new_persons_vaccinated_janssen, cumulative_persons_vaccinated_janssen, new_persons_fully_vaccinated_janssen, cumulative_persons_fully_vaccinated_janssen, new_vaccine_doses_administered_janssen, cumulative_vaccine_doses_administered_janssen, new_persons_vaccinated_sinovac, total_persons_vaccinated_sinovac, new_persons_fully_vaccinated_sinovac, total_persons_fully_vaccinated_sinovac, new_vaccine_doses_administered_sinovac, total_vaccine_doses_administered_sinovac
- AUS: missing data in new_persons_vaccinated_pfizer, cumulative_persons_vaccinated_pfizer, new_persons_fully_vaccinated_pfizer, cumulative_persons_fully_vaccinated_pfizer, new_vaccine_doses_administered_pfizer, cumulative_vaccine_doses_administered_pfizer, new_persons_vaccinated_moderna, cumulative_persons_vaccinated_moderna, new_persons_fully_vaccinated_moderna, cumulative_persons_fully_vaccinated_moderna, new_vaccine_doses_administered_moderna, cumulative_vaccine_doses_administered_moderna, new_persons_vaccinated_janssen, cumulative_persons_vaccinated_janssen, new_persons_fully_vaccinated_janssen, cumulative_persons_fully_vaccinated_janssen, new_vaccine_doses_administered_janssen, cumulative_vaccine_doses_administered_janssen, new_persons_vaccinated_sinovac, total_persons_vaccinated_sinovac, new_persons_fully_vaccinated_sinovac, total_persons_fully_vaccinated_sinovac, new_vaccine_doses_administered_sinovac, total_vaccine_doses_administered_sinovac
- AUT: missing data in new_persons_vaccinated_pfizer, cumulative_persons_vaccinated_pfizer, new_persons_fully_vaccinated_pfizer, cumulative_persons_fully_vaccinated_pfizer, new_vaccine_doses_administered_pfizer, cumulative_vaccine_doses_administered_pfizer, new_persons_vaccinated_moderna, cumulative_persons_vaccinated_moderna, new_persons_fully_vaccinated_moderna, cumulative_persons_fully_vaccinated_moderna, new_vaccine_doses_administered_moderna, cumulative_vaccine_doses_administered_moderna, new_persons_vaccinated_janssen, cumulative_persons_vaccinated_janssen, new_persons_fully_vaccinated_janssen, cumulative_persons_fully_vaccinated_janssen, new_vaccine_doses_administered_janssen, cumulative_vaccine_doses_administered_janssen, new_persons_vaccinated_sinovac, total_persons_vaccinated_sinovac, new_persons_fully_vaccinated_sinovac, total_persons_fully_vaccinated_sinovac, new_vaccine_doses_administered_sinovac, total_vaccine_doses_administered_sinovac
- BDI: missing data in new_persons_vaccinated_pfizer, cumulative_persons_vaccinated_pfizer, new_persons_fully_vaccinated_pfizer, cumulative_persons_fully_vaccinated_pfizer, new_vaccine_doses_administered_pfizer, cumulative_vaccine_doses_administered_pfizer, new_persons_vaccinated_moderna, cumulative_persons_vaccinated_moderna, new_persons_fully_vaccinated_moderna, cumulative_persons_fully_vaccinated_moderna, new_vaccine_doses_administered_moderna, cumulative_vaccine_doses_administered_moderna, new_persons_vaccinated_janssen, cumulative_persons_vaccinated_janssen, new_persons_fully_vaccinated_janssen, cumulative_persons_fully_vaccinated_janssen, new_vaccine_doses_administered_janssen, cumulative_vaccine_doses_administered_janssen, new_persons_vaccinated_sinovac, total_persons_vaccinated_sinovac, new_persons_fully_vaccinated_sinovac, total_persons_fully_vaccinated_sinovac, new_vaccine_doses_administered_sinovac, total_vaccine_doses_administered_sinovac
- BEN: missing data in new_tested, new_persons_vaccinated_pfizer, cumulative_persons_vaccinated_pfizer, new_persons_fully_vaccinated_pfizer, cumulative_persons_fully_vaccinated_pfizer, new_vaccine_doses_administered_pfizer, cumulative_vaccine_doses_administered_pfizer, new_persons_vaccinated_moderna, cumulative_persons_vaccinated_moderna, new_persons_fully_vaccinated_moderna, cumulative_persons_fully_vaccinated_moderna, new_vaccine_doses_administered_moderna, cumulative_vaccine_doses_administered_moderna, new_persons_vaccinated_janssen, cumulative_persons_vaccinated_janssen, new_persons_fully_vaccinated_janssen, cumulative_persons_fully_vaccinated_janssen, new_vaccine_doses_administered_janssen, cumulative_vaccine_doses_administered_janssen, new_persons_vaccinated_sinovac, total_persons_vaccinated_sinovac, new_persons_fully_vaccinated_sinovac, total_persons_fully_vaccinated_sinovac, new_vaccine_doses_administered_sinovac, total_vaccine_doses_administered_sinovac
- BGD: missing data in new_persons_vaccinated_pfizer, cumulative_persons_vaccinated_pfizer, new_persons_fully_vaccinated_pfizer, cumulative_persons_fully_vaccinated_pfizer, new_vaccine_doses_administered_pfizer, cumulative_vaccine_doses_administered_pfizer, new_persons_vaccinated_moderna, cumulative_persons_vaccinated_moderna, new_persons_fully_vaccinated_moderna, cumulative_persons_fully_vaccinated_moderna, new_vaccine_doses_administered_moderna, cumulative_vaccine_doses_administered_moderna, new_persons_vaccinated_janssen, cumulative_persons_vaccinated_janssen, new_persons_fully_vaccinated_janssen, cumulative_persons_fully_vaccinated_janssen, new_vaccine_doses_administered_janssen, cumulative_vaccine_doses_administered_janssen, new_persons_vaccinated_sinovac, total_persons_vaccinated_sinovac, new_persons_fully_vaccinated_sinovac, total_persons_fully_vaccinated_sinovac, new_vaccine_doses_administered_sinovac, total_vaccine_doses_administered_sinovac
- BGR: missing data in new_persons_vaccinated_pfizer, cumulative_persons_vaccinated_pfizer, new_persons_fully_vaccinated_pfizer, cumulative_persons_fully_vaccinated_pfizer, new_vaccine_doses_administered_pfizer, cumulative_vaccine_doses_administered_pfizer, new_persons_vaccinated_moderna, cumulative_persons_vaccinated_moderna, new_persons_fully_vaccinated_moderna, cumulative_persons_fully_vaccinated_moderna, new_vaccine_doses_administered_moderna, cumulative_vaccine_doses_administered_moderna, new_persons_vaccinated_janssen, cumulative_persons_vaccinated_janssen, new_persons_fully_vaccinated_janssen, cumulative_persons_fully_vaccinated_janssen, new_vaccine_doses_administered_janssen, cumulative_vaccine_doses_administered_janssen, new_persons_vaccinated_sinovac, total_persons_vaccinated_sinovac, new_persons_fully_vaccinated_sinovac, total_persons_fully_vaccinated_sinovac, new_vaccine_doses_administered_sinovac, total_vaccine_doses_administered_sinovac
- BHR: missing data in new_persons_vaccinated_pfizer, cumulative_persons_vaccinated_pfizer, new_persons_fully_vaccinated_pfizer, cumulative_persons_fully_vaccinated_pfizer, new_vaccine_doses_administered_pfizer, cumulative_vaccine_doses_administered_pfizer, new_persons_vaccinated_moderna, cumulative_persons_vaccinated_moderna, new_persons_fully_vaccinated_moderna, cumulative_persons_fully_vaccinated_moderna, new_vaccine_doses_administered_moderna, cumulative_vaccine_doses_administered_moderna, new_persons_vaccinated_janssen, cumulative_persons_vaccinated_janssen, new_persons_fully_vaccinated_janssen, cumulative_persons_fully_vaccinated_janssen, new_vaccine_doses_administered_janssen, cumulative_vaccine_doses_administered_janssen, new_persons_vaccinated_sinovac, total_persons_vaccinated_sinovac, new_persons_fully_vaccinated_sinovac, total_persons_fully_vaccinated_sinovac, new_vaccine_doses_administered_sinovac, total_vaccine_doses_administered_sinovac
- BHS: missing data in new_persons_vaccinated_pfizer, cumulative_persons_vaccinated_pfizer, new_persons_fully_vaccinated_pfizer, cumulative_persons_fully_vaccinated_pfizer, new_vaccine_doses_administered_pfizer, cumulative_vaccine_doses_administered_pfizer, new_persons_vaccinated_moderna, cumulative_persons_vaccinated_moderna, new_persons_fully_vaccinated_moderna, cumulative_persons_fully_vaccinated_moderna, new_vaccine_doses_administered_moderna, cumulative_vaccine_doses_administered_moderna, new_persons_vaccinated_janssen, cumulative_persons_vaccinated_janssen, new_persons_fully_vaccinated_janssen, cumulative_persons_fully_vaccinated_janssen, new_vaccine_doses_administered_janssen, cumulative_vaccine_doses_administered_janssen, new_persons_vaccinated_sinovac, total_persons_vaccinated_sinovac, new_persons_fully_vaccinated_sinovac, total_persons_fully_vaccinated_sinovac, new_vaccine_doses_administered_sinovac, total_vaccine_doses_administered_sinovac
- BIH: missing data in new_persons_vaccinated_pfizer, cumulative_persons_vaccinated_pfizer, new_persons_fully_vaccinated_pfizer, cumulative_persons_fully_vaccinated_pfizer, new_vaccine_doses_administered_pfizer, cumulative_vaccine_doses_administered_pfizer, new_persons_vaccinated_moderna, cumulative_persons_vaccinated_moderna, new_persons_fully_vaccinated_moderna, cumulative_persons_fully_vaccinated_moderna, new_vaccine_doses_administered_moderna, cumulative_vaccine_doses_administered_moderna, new_persons_vaccinated_janssen, cumulative_persons_vaccinated_janssen, new_persons_fully_vaccinated_janssen, cumulative_persons_fully_vaccinated_janssen, new_vaccine_doses_administered_janssen, cumulative_vaccine_doses_administered_janssen, new_persons_vaccinated_sinovac, total_persons_vaccinated_sinovac, new_persons_fully_vaccinated_sinovac, total_persons_fully_vaccinated_sinovac, new_vaccine_doses_administered_sinovac, total_vaccine_doses_administered_sinovac
- BLR: missing data in new_persons_vaccinated_pfizer, cumulative_persons_vaccinated_pfizer, new_persons_fully_vaccinated_pfizer, cumulative_persons_fully_vaccinated_pfizer, new_vaccine_doses_administered_pfizer, cumulative_vaccine_doses_administered_pfizer, new_persons_vaccinated_moderna, cumulative_persons_vaccinated_moderna, new_persons_fully_vaccinated_moderna, cumulative_persons_fully_vaccinated_moderna, new_vaccine_doses_administered_moderna, cumulative_vaccine_doses_administered_moderna, new_persons_vaccinated_janssen, cumulative_persons_vaccinated_janssen, new_persons_fully_vaccinated_janssen, cumulative_persons_fully_vaccinated_janssen, new_vaccine_doses_administered_janssen, cumulative_vaccine_doses_administered_janssen, new_persons_vaccinated_sinovac, total_persons_vaccinated_sinovac, new_persons_fully_vaccinated_sinovac, total_persons_fully_vaccinated_sinovac, new_vaccine_doses_administered_sinovac, total_vaccine_doses_administered_sinovac
- BLZ: missing data in new_persons_vaccinated_pfizer, cumulative_persons_vaccinated_pfizer, new_persons_fully_vaccinated_pfizer, cumulative_persons_fully_vaccinated_pfizer, new_vaccine_doses_administered_pfizer, cumulative_vaccine_doses_administered_pfizer, new_persons_vaccinated_moderna, cumulative_persons_vaccinated_moderna, new_persons_fully_vaccinated_moderna, cumulative_persons_fully_vaccinated_moderna, new_vaccine_doses_administered_moderna, cumulative_vaccine_doses_administered_moderna, new_persons_vaccinated_janssen, cumulative_persons_vaccinated_janssen, new_persons_fully_vaccinated_janssen, cumulative_persons_fully_vaccinated_janssen, new_vaccine_doses_administered_janssen, cumulative_vaccine_doses_administered_janssen, new_persons_vaccinated_sinovac, total_persons_vaccinated_sinovac, new_persons_fully_vaccinated_sinovac, total_persons_fully_vaccinated_sinovac, new_vaccine_doses_administered_sinovac, total_vaccine_doses_administered_sinovac
- BMU: missing data in new_persons_vaccinated_pfizer, cumulative_persons_vaccinated_pfizer, new_persons_fully_vaccinated_pfizer, cumulative_persons_fully_vaccinated_pfizer, new_vaccine_doses_administered_pfizer, cumulative_vaccine_doses_administered_pfizer, new_persons_vaccinated_moderna, cumulative_persons_vaccinated_moderna, new_persons_fully_vaccinated_moderna, cumulative_persons_fully_vaccinated_moderna, new_vaccine_doses_administered_moderna, cumulative_vaccine_doses_administered_moderna, new_persons_vaccinated_janssen, cumulative_persons_vaccinated_janssen, new_persons_fully_vaccinated_janssen, cumulative_persons_fully_vaccinated_janssen, new_vaccine_doses_administered_janssen, cumulative_vaccine_doses_administered_janssen, new_persons_vaccinated_sinovac, total_persons_vaccinated_sinovac, new_persons_fully_vaccinated_sinovac, total_persons_fully_vaccinated_sinovac, new_vaccine_doses_administered_sinovac, total_vaccine_doses_administered_sinovac
- BOL: missing data in new_persons_vaccinated_pfizer, cumulative_persons_vaccinated_pfizer, new_persons_fully_vaccinated_pfizer, cumulative_persons_fully_vaccinated_pfizer, new_vaccine_doses_administered_pfizer, cumulative_vaccine_doses_administered_pfizer, new_persons_vaccinated_moderna, cumulative_persons_vaccinated_moderna, new_persons_fully_vaccinated_moderna, cumulative_persons_fully_vaccinated_moderna, new_vaccine_doses_administered_moderna, cumulative_vaccine_doses_administered_moderna, new_persons_vaccinated_janssen, cumulative_persons_vaccinated_janssen, new_persons_fully_vaccinated_janssen, cumulative_persons_fully_vaccinated_janssen, new_vaccine_doses_administered_janssen, cumulative_vaccine_doses_administered_janssen, new_persons_vaccinated_sinovac, total_persons_vaccinated_sinovac, new_persons_fully_vaccinated_sinovac, total_persons_fully_vaccinated_sinovac, new_vaccine_doses_administered_sinovac, total_vaccine_doses_administered_sinovac

### - Saving the cleaned datasets

In [30]:
# Save to CSV
output_path = current_dir.parent / 'data' / 'merged_covid_data.csv'
merged_data.to_csv(output_path, index=False)
print(f"\nSaved merged dataset to: {output_path}")

merged_data.head()

Saved merged dataset to: c:\Users\Lenovo\OneDrive - Danmarks Tekniske Universitet\02806 Social data analysis and visualization\final_project\data\merged_covid_data.csv

,date,location_key,new_confirmed,new_deceased,new_tested,cumulative_confirmed,cumulative_deceased,cumulative_tested,school_closing,workplace_closing,...,new_persons_fully_vaccinated_janssen,cumulative_persons_fully_vaccinated_janssen,new_vaccine_doses_administered_janssen,cumulative_vaccine_doses_administered_janssen,new_persons_vaccinated_sinovac,total_persons_vaccinated_sinovac,new_persons_fully_vaccinated_sinovac,total_persons_fully_vaccinated_sinovac,new_vaccine_doses_administered_sinovac,total_vaccine_doses_administered_sinovac
0,2020-01-02,ARE,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-01-03,ARE,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-01-04,ARE,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-01-05,ARE,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-01-06,ARE,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN