In [29]:
import pandas as pd
import numpy as np
from pathlib import Path

import pycountry

# Get the directory where the current notebook is located
current_dir = Path.cwd()

# Define the path relative to the notebook
data_path1 = current_dir.parent / "data" / "epidemiology.csv" #This file contains the epidemiological data, including the number of cases, deaths, and recoveries for each country and date.
data_path2 = current_dir.parent / "data" / "oxford-government-response.csv" #This file contains the Oxford COVID-19 Government Response Tracker data, which includes various indicators of government responses to the pandemic, such as school closures, travel restrictions, and public information campaigns.
data_path3 = current_dir.parent / "data" / "vaccinations.csv" #This file contains vaccination data, including the number of vaccinations administered, the percentage of the population vaccinated, and the types of vaccines used in each country.
data_path4 = current_dir.parent / "data" / "daily-tests-per-thousand-people-smoothed-7-day.csv" #This file contains data on the number of daily tests per thousand people, smoothed over a 7-day period.

In [30]:
# Load the datasets
data1=pd.read_csv(data_path1) #epedemiology data
data2=pd.read_csv(data_path2) #government response data
data3=pd.read_csv(data_path3) #vaccination data
data4=pd.read_csv(data_path4) #testing data

In [31]:
#Examine the first few rows of the datasets
data1.head(2)

,date,location_key,new_confirmed,new_deceased,new_recovered,new_tested,cumulative_confirmed,cumulative_deceased,cumulative_recovered,cumulative_tested
0,2020-01-01,AD,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN
1,2020-01-02,AD,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN

In [32]:
data2.head(2)

,date,location_key,school_closing,workplace_closing,cancel_public_events,restrictions_on_gatherings,public_transport_closing,stay_at_home_requirements,restrictions_on_internal_movement,international_travel_controls,...,fiscal_measures,international_support,public_information_campaigns,testing_policy,contact_tracing,emergency_investment_in_healthcare,investment_in_vaccines,facial_coverings,vaccination_policy,stringency_index
0,2020-01-01,AD,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2020-01-02,AD,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [33]:
data3.head(2)

,date,location_key,new_persons_vaccinated,cumulative_persons_vaccinated,new_persons_fully_vaccinated,cumulative_persons_fully_vaccinated,new_vaccine_doses_administered,cumulative_vaccine_doses_administered,new_persons_vaccinated_pfizer,cumulative_persons_vaccinated_pfizer,...,new_persons_fully_vaccinated_janssen,cumulative_persons_fully_vaccinated_janssen,new_vaccine_doses_administered_janssen,cumulative_vaccine_doses_administered_janssen,new_persons_vaccinated_sinovac,total_persons_vaccinated_sinovac,new_persons_fully_vaccinated_sinovac,total_persons_fully_vaccinated_sinovac,new_vaccine_doses_administered_sinovac,total_vaccine_doses_administered_sinovac
0,2021-01-25,AD,NaN,576.0,NaN,NaN,NaN,576.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021-02-01,AD,460.0,1036.0,NaN,NaN,460.0,1036.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
data4.head(2)

,Entity,Code,Day,Daily tests per thousand people (7-day smoothed),Daily tests per thousand people (7-day smoothed) (Annotations)
0,Afghanistan,AFG,2022-02-05,0.032,NaN
1,Afghanistan,AFG,2022-02-06,0.032,NaN

In [35]:
# Filter for country codes only (leave out regional data)
# Return unique location keys for dataset 1
def get_unique_location_keys(data1):
    return list(set(data1["location_key"].dropna().str.split("_").str[0]))

unique_Country_Keys1 = get_unique_location_keys(data1)

print(unique_Country_Keys1)
print(len(unique_Country_Keys1))

['SL', 'CY', 'SR', 'MZ', 'AZ', 'BM', 'KM', 'SV', 'SY', 'LS', 'GN', 'KW', 'SB', 'DM', 'YE', 'VE', 'MU', 'XK', 'AI', 'GQ', 'ST', 'HT', 'GA', 'PG', 'AW', 'RO', 'BF', 'AG', 'IQ', 'RU', 'BO', 'EE', 'BW', 'BN', 'NL', 'CG', 'UZ', 'HU', 'MN', 'TK', 'WS', 'AF', 'KR', 'SN', 'EH', 'IT', 'BB', 'DO', 'LV', 'MP', 'CR', 'BE', 'NC', 'BD', 'SO', 'MK', 'AD', 'LB', 'TM', 'SK', 'GL', 'DK', 'RW', 'ES', 'AU', 'CU', 'BS', 'GD', 'KG', 'SC', 'CL', 'VC', 'NO', 'SD', 'CV', 'PH', 'DE', 'GF', 'VG', 'TH', 'MX', 'SM', 'GE', 'KZ', 'NZ', 'GY', 'TR', 'JP', 'NI', 'YT', 'IM', 'PN', 'CZ', 'AM', 'PA', 'VU', 'MR', 'KP', 'PF', 'TO', 'BG', 'UA', 'US', 'AS', 'NG', 'GI', 'TZ', 'CI', 'TJ', 'KH', 'GT', 'MM', 'PL', 'SH', 'UG', 'NR', 'MT', 'WF', 'HR', 'FR', 'LA', 'GG', 'BH', 'SG', 'DJ', 'VI', 'NE', 'BR', 'KI', 'CA', 'ER', 'GU', 'LY', 'TD', 'IL', 'RE', 'EC', 'SE', 'VN', 'RS', 'SS', 'MV', 'BZ', 'FO', 'BA', 'EG', 'FK', 'KY', 'PE', 'TW', 'GR', 'AE', 'FJ', 'AO', 'CN', 'CM', 'ML', 'MA', 'CO', 'PY', 'IE', 'QA', 'SZ', 'MS', 'FI', 'TT', 'OM', 'CF', 'MQ', 'BJ', 'CK', 'ZW', 'FM', 'SI', 'MY', 'CW', 'ET', 'TV', 'ZM', 'ME', 'MD', 'SX', 'GH', 'PT', 'LU', 'TL', 'JE', 'NU', 'UY', 'LK', 'ID', 'AL', 'GW', 'MC', 'MH', 'TC', 'CH', 'HK', 'DZ', 'BT', 'PW', 'ZA', 'AR', 'KN', 'AT', 'MW', 'IS', 'BI', 'PR', 'KE', 'MO', 'JO', 'NP', 'PS', 'JM', 'LI', 'TN', 'BY', 'GB', 'VA', 'MG', 'GM', 'LT', 'CD', 'PK', 'SA', 'IN', 'TG', 'IR', 'LR', 'LC', 'HN']
232

In [36]:
# Filter for country codes only (leave out regional data)
# Return unique location keys for dataset 2
def get_unique_location_keys(data2):
    return list(set(data2["location_key"].dropna().str.split("_").str[0]))

unique_Country_Keys2 = get_unique_location_keys(data2)

print(unique_Country_Keys2)
print(len(unique_Country_Keys2))

['SL', 'CY', 'SR', 'MZ', 'AZ', 'BM', 'KM', 'SV', 'SY', 'LS', 'GN', 'KW', 'SB', 'DM', 'YE', 'VE', 'MU', 'XK', 'HT', 'GA', 'PG', 'AW', 'RO', 'BF', 'IQ', 'RU', 'BO', 'EE', 'BW', 'BN', 'NL', 'CG', 'UZ', 'HU', 'MN', 'AF', 'KR', 'SN', 'IT', 'BB', 'DO', 'LV', 'CR', 'BE', 'BD', 'SO', 'AD', 'LB', 'TM', 'SK', 'GL', 'DK', 'RW', 'ES', 'AU', 'CU', 'BS', 'GD', 'KG', 'SC', 'CL', 'NO', 'SD', 'CV', 'PH', 'DE', 'TH', 'MX', 'SM', 'GE', 'KZ', 'NZ', 'GY', 'TR', 'JP', 'NI', 'VU', 'CZ', 'PA', 'MR', 'TO', 'BG', 'UA', 'US', 'NG', 'TZ', 'CI', 'TJ', 'KH', 'GT', 'MM', 'PL', 'UG', 'MT', 'HR', 'FR', 'LA', 'BH', 'SG', 'DJ', 'VI', 'NE', 'BR', 'KI', 'CA', 'ER', 'GU', 'LY', 'TD', 'IL', 'EC', 'SE', 'VN', 'RS', 'SS', 'BZ', 'FO', 'BA', 'EG', 'PE', 'TW', 'GR', 'AE', 'FJ', 'AO', 'CN', 'CM', 'ML', 'MA', 'CO', 'PY', 'IE', 'QA', 'SZ', 'FI', 'TT', 'OM', 'CF', 'BJ', 'ZW', 'SI', 'MY', 'ET', 'ZM', 'MD', 'GH', 'PT', 'LU', 'TL', 'UY', 'LK', 'ID', 'AL', 'MC', 'CH', 'HK', 'DZ', 'BT', 'ZA', 'AR', 'AT', 'MW', 'IS', 'BI', 'PR', 'KE', 'MO', 'JO', 'NP', 'PS', 'JM', 'LI', 'TN', 'BY', 'GB', 'MG', 'GM', 'LT', 'CD', 'PK', 'SA', 'IN', 'TG', 'IR', 'LR', 'HN']
186

In [37]:
# Function to convert location_key from ISO-2 to ISO-3 format
def convert_iso2_to_iso3(location_key):
    """
    Convert a location_key from ISO-2 to ISO-3 format.
    """
    if pd.isna(location_key):
        return location_key
    
    parts = location_key.split("_")
    iso2 = parts[0]
    
    country = pycountry.countries.get(alpha_2=iso2)
    
    if country:
        parts[0] = country.alpha_3  # Replace ISO-2 with ISO-3
        return "_".join(parts)
    else:
        return location_key  # Return original if not found (e.g. 'XK' for Kosovo)

In [38]:
# Pulling out focus data from dataset 1 
# Filtering dataset to only include data by country
focus_data1 = data1[data1['location_key'].isin(unique_Country_Keys1)]
focus_data1.info()

<class 'pandas.DataFrame'>
Index: 226892 entries, 0 to 12525824
Data columns (total 10 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   date                  226892 non-null  str
 1   location_key          226892 non-null  str
 2   new_confirmed         226799 non-null  float64
 3   new_deceased          226624 non-null  float64
 4   new_recovered         15712 non-null   float64
 5   new_tested            76705 non-null   float64
 6   cumulative_confirmed  226798 non-null  float64
 7   cumulative_deceased   226625 non-null  float64
 8   cumulative_recovered  14759 non-null   float64
 9   cumulative_tested     80010 non-null   float64
dtypes: float64(8), str(2)
memory usage: 19.0 MB

In [39]:
# Pulling out focus data from dataset 2
# Filtering dataset to only include data by country
focus_data2 = data2[data2['location_key'].isin(unique_Country_Keys2)]
focus_data2.info()

# Pulling out focus data from dataset 3 (vaccination data)
# Filter for country codes only (leave out regional data)
unique_Country_Keys3 = list(set(data3['location_key'].dropna().str.split('_').str[0]))
focus_data3 = data3[data3['location_key'].isin(unique_Country_Keys3)]
focus_data3.info()

<class 'pandas.DataFrame'>
Index: 171200 entries, 0 to 303968
Data columns (total 22 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   date                                171200 non-null  str
 1   location_key                        171200 non-null  str
 2   school_closing                      170800 non-null  float64
 3   workplace_closing                   170803 non-null  float64
 4   cancel_public_events                170785 non-null  float64
 5   restrictions_on_gatherings          170781 non-null  float64
 6   public_transport_closing            170785 non-null  float64
 7   stay_at_home_requirements           170780 non-null  float64
 8   restrictions_on_internal_movement   170765 non-null  float64
 9   international_travel_controls       170787 non-null  float64
 10  income_support                      170733 non-null  float64
 11  debt_relief                         170747 non-null  float64
 12  fiscal_measures                     105697 non-null  float64
 13  international_support               105777 non-null  float64
 14  public_information_campaigns        170791 non-null  float64
 15  testing_policy                      170767 non-null  float64
 16  contact_tracing                     170708 non-null  float64
 17  emergency_investment_in_healthcare  105659 non-null  float64
 18  investment_in_vaccines              166826 non-null  float64
 19  facial_coverings                    171036 non-null  float64
 20  vaccination_policy                  171091 non-null  float64
 21  stringency_index                    170751 non-null  float64
dtypes: float64(20), str(2)
memory usage: 30.0 MB
<class 'pandas.DataFrame'>
Index: 55873 entries, 0 to 2545117
Data columns (total 32 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   date                                           55873 non-null  str
 1   location_key                                   55873 non-null  str
 2   new_persons_vaccinated                         54577 non-null  float64
 3   cumulative_persons_vaccinated                  51786 non-null  float64
 4   new_persons_fully_vaccinated                   52513 non-null  float64
 5   cumulative_persons_fully_vaccinated            50019 non-null  float64
 6   new_vaccine_doses_administered                 54922 non-null  float64
 7   cumulative_vaccine_doses_administered          54431 non-null  float64
 8   new_persons_vaccinated_pfizer                  569 non-null    float64
 9   cumulative_persons_vaccinated_pfizer           569 non-null    float64
 10  new_persons_fully_vaccinated_pfizer            1111 non-null   float64
 11  cumulative_persons_fully_vaccinated_pfizer     1112 non-null   float64
 12  new_vaccine_doses_administered_pfizer          542 non-null    float64
 13  cumulative_vaccine_doses_administered_pfizer   543 non-null    float64
 14  new_persons_vaccinated_moderna                 0 non-null      float64
 15  cumulative_persons_vaccinated_moderna          0 non-null      float64
 16  new_persons_fully_vaccinated_moderna           542 non-null    float64
 17  cumulative_persons_fully_vaccinated_moderna    543 non-null    float64
 18  new_vaccine_doses_administered_moderna         542 non-null    float64
 19  cumulative_vaccine_doses_administered_moderna  543 non-null    float64
 20  new_persons_vaccinated_janssen                 0 non-null      float64
 21  cumulative_persons_vaccinated_janssen          0 non-null      float64
 22  new_persons_fully_vaccinated_janssen           542 non-null    float64
 23  cumulative_persons_fully_vaccinated_janssen    543 non-null    float64
 24  new_vaccine_doses_administered_janssen         542 non-null    float64
 25  cumulative_vaccine_doses_administered_janssen  543 non-null    float64
 26  new_persons_vaccinated_sinovac                 569 non-null    float64
 27  total_persons_vaccinated_sinovac               569 non-null    float64
 28  new_persons_fully_vaccinated_sinovac           0 non-null      float64
 29  total_persons_fully_vaccinated_sinovac         0 non-null      float64
 30  new_vaccine_doses_administered_sinovac         0 non-null      float64
 31  total_vaccine_doses_administered_sinovac       0 non-null      float64
dtypes: float64(30), str(2)
memory usage: 14.1 MB

In [40]:
# Number of days recorded for each country in dataset 1
focus_data1_numberOfDays=focus_data1['location_key'].value_counts()
focus_data1_numberOfDays

location_key
AU    990
TH    990
AT    989
BE    989
BR    989
     ...
ZW    987
TW    974
HK    693
MO    152
EH      1
Name: count, Length: 232, dtype: int64

In [41]:
# Number of days recorded for each country in datset 2
focus_data2_numberOfDays=focus_data2['location_key'].value_counts()
focus_data2_numberOfDays

location_key
AF    938
AU    938
CL    938
HR    938
MT    938
     ...
GU    899
PS    898
CZ    881
KM    342
GD     87
Name: count, Length: 186, dtype: int64

In [42]:
#Analyzing the distribution of the number of days recorded for each country in both datasets using boxplot statistics

def boxplot_stats(series):
    q1 = series.quantile(0.25)
    median = series.quantile(0.5)
    q3 = series.quantile(0.75)
    iqr = q3 - q1

    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr

    outliers = series[(series < lower_bound) | (series > upper_bound)]

    return {
        "min": series.min(),
        "Q1": q1,
        "median": median,
        "Q3": q3,
        "max": series.max(),
        "IQR": iqr,
        "lower_bound": lower_bound,
        "upper_bound": upper_bound,
        "num_outliers": len(outliers)
    }

# Apply to both datasets
stats1 = boxplot_stats(focus_data1_numberOfDays)
stats2 = boxplot_stats(focus_data2_numberOfDays)

# Convert to DataFrame for clean display
summary = pd.DataFrame([stats1, stats2], 
                       index=["Dataset 1", "Dataset 2"])

print(summary)

           min     Q1  median     Q3  max   IQR  lower_bound  upper_bound  \
Dataset 1    1  987.0   987.0  987.0  990   0.0        987.0        987.0
Dataset 2   87  923.0   930.0  937.0  938  14.0        902.0        958.0

           num_outliers
Dataset 1            26
Dataset 2             9

In [43]:
# Using statistics to filter the data
# We will keep countries that have number of days recorded >= Q1 (first quartile)

# For dataset 1
q1_dataset1 = stats1['Q1']
# Filtering dataset to exclude countries with observation numbers below Q1
filtered_countries_1 = focus_data1_numberOfDays[focus_data1_numberOfDays >= q1_dataset1].index.tolist()
filtered_focus_data1 = focus_data1[focus_data1['location_key'].isin(filtered_countries_1)]

print(f"Dataset 1 - Q1 threshold: {q1_dataset1}")
print(f"Countries kept (>= Q1): {len(filtered_countries_1)}")
print(f"Filtered data1 shape: {filtered_focus_data1.shape}")

Dataset 1 - Q1 threshold: 987.0
Countries kept (>= Q1): 228
Filtered data1 shape: (225072, 10)

# Epidemiologi_global_covid 
### - Checking for potential missing data

In [44]:
# Check that each country has at least one entity value for every data column in filtered_focus_data1_common.
# This helps verify that each country doesn't have systematic missingness.

def check_country_column_non_missing(df, country_col='location_key', threshold=1):
    """Return non-missing counts, missing-category flags, and a summary per country."""
    # Count non-missing entries per country and column
    non_missing_counts = df.groupby(country_col).apply(lambda group: group.notna().sum())
    if country_col in non_missing_counts.columns:
        non_missing_counts = non_missing_counts.drop(columns=[country_col])

    # Identify columns where the count of non-missing values is below the threshold
    missing_flags = (non_missing_counts < threshold)
    missing_matrix = missing_flags.astype(object)
    missing_matrix[missing_flags] = 'Non'
    missing_matrix[~missing_flags] = ''

    # Build a summary table and list missing categories for each country
    missing_categories = {
        country: non_missing_counts.columns[missing_flags.loc[country]].tolist()
        for country in non_missing_counts.index
    }

    summary = pd.DataFrame({
        'has_minimum_per_column': [len(categories) == 0 for categories in missing_categories.values()],
        'missing_columns': [', '.join(categories) if categories else '' for categories in missing_categories.values()]
    }, index=non_missing_counts.index)

    return non_missing_counts, missing_flags, missing_matrix, summary, missing_categories

# Run the check on filtered_focus_data1_common
non_missing_counts, missing_flags, missing_matrix, country_summary, missing_categories = check_country_column_non_missing(filtered_focus_data1_common)

print("\nSummary of missing data per category:")
missing_per_category = (missing_matrix == 'Non').sum()
print(missing_per_category)

if country_summary['has_minimum_per_column'].all():
    print("\nAll countries have at least one non-missing value in every column.")
else:
    print("\nCountries with missing entities in one or more categories:")
    for country, categories in missing_categories.items():
        if categories:
            print(f"- {country}: missing data in {', '.join(categories)}")

Summary of missing data per category:
date                     0
new_confirmed            0
new_deceased             0
new_tested              75
cumulative_confirmed     0
cumulative_deceased      0
cumulative_tested       46
dtype: int64

Countries with missing entities in one or more categories:
- AD: missing data in new_tested
- AF: missing data in new_tested
- AG: missing data in new_tested
- AI: missing data in new_tested
- AS: missing data in new_tested, cumulative_tested
- BJ: missing data in new_tested
- CD: missing data in new_tested
- CF: missing data in new_tested
- CG: missing data in new_tested
- CK: missing data in new_tested, cumulative_tested
- CM: missing data in new_tested
- CN: missing data in new_tested
- CV: missing data in cumulative_tested
- DE: missing data in new_tested
- DZ: missing data in new_tested
- EG: missing data in new_tested
- ER: missing data in new_tested
- ES: missing data in new_tested, cumulative_tested
- FK: missing data in new_tested, cumulative_tested
- FM: missing data in new_tested, cumulative_tested
- GF: missing data in new_tested, cumulative_tested
- GG: missing data in new_tested, cumulative_tested
- GL: missing data in new_tested, cumulative_tested
- GM: missing data in new_tested
- GN: missing data in new_tested
- GY: missing data in new_tested
- HN: missing data in new_tested, cumulative_tested
- IM: missing data in new_tested, cumulative_tested
- JE: missing data in new_tested, cumulative_tested
- KG: missing data in new_tested, cumulative_tested
- KI: missing data in new_tested, cumulative_tested
- KM: missing data in new_tested
- LR: missing data in new_tested
- LY: missing data in cumulative_tested
- MC: missing data in new_tested, cumulative_tested
- MD: missing data in cumulative_tested
- ME: missing data in new_tested, cumulative_tested
- MQ: missing data in new_tested, cumulative_tested
- MS: missing data in new_tested, cumulative_tested
- MU: missing data in new_tested
- NC: missing data in new_tested, cumulative_tested
- NI: missing data in new_tested
- NR: missing data in new_tested, cumulative_tested
- NU: missing data in new_tested, cumulative_tested
- OM: missing data in new_tested
- PE: missing data in new_tested
- PF: missing data in new_tested, cumulative_tested
- PG: missing data in new_tested
- PN: missing data in new_tested, cumulative_tested
- PS: missing data in cumulative_tested
- PW: missing data in new_tested
- RE: missing data in new_tested, cumulative_tested
- RO: missing data in new_tested
- SB: missing data in new_tested, cumulative_tested
- SC: missing data in new_tested, cumulative_tested
- SD: missing data in new_tested
- SG: missing data in cumulative_tested
- SH: missing data in new_tested, cumulative_tested
- SM: missing data in new_tested, cumulative_tested
- SO: missing data in new_tested
- SX: missing data in new_tested, cumulative_tested
- SY: missing data in new_tested
- TC: missing data in new_tested, cumulative_tested
- TD: missing data in new_tested
- TJ: missing data in new_tested, cumulative_tested
- TK: missing data in new_tested, cumulative_tested
- TM: missing data in new_tested, cumulative_tested
- TO: missing data in new_tested, cumulative_tested
- TV: missing data in new_tested, cumulative_tested
- TZ: missing data in new_tested
- UZ: missing data in new_tested, cumulative_tested
- VA: missing data in new_tested, cumulative_tested
- VE: missing data in new_tested, cumulative_tested
- VG: missing data in new_tested
- VU: missing data in new_tested
- WF: missing data in new_tested, cumulative_tested
- WS: missing data in new_tested, cumulative_tested
- XK: missing data in new_tested, cumulative_tested
- YE: missing data in new_tested
- YT: missing data in new_tested, cumulative_tested

In [45]:
# Function to remove 'new_recovered' and 'cumulative_recovered' columns from the dataframe
def remove_recovered_columns(df):
    """
    Remove 'new_recovered' and 'cumulative_recovered' columns if they exist in the dataframe.
    """
    columns_to_remove = ['new_recovered', 'cumulative_recovered']
    df = df.drop(columns=[col for col in columns_to_remove if col in df.columns], errors='ignore')
    return df

# Apply the function to filtered_focus_data1_common
filtered_focus_data1_common = remove_recovered_columns(filtered_focus_data1_common)

print(f"After removing columns with too few datapoints, shape: {filtered_focus_data1_common.shape}")
print("Columns remaining:", list(filtered_focus_data1_common.columns))

After removing columns with too few datapoints, shape: (224808, 8)
Columns remaining: ['date', 'location_key', 'new_confirmed', 'new_deceased', 'new_tested', 'cumulative_confirmed', 'cumulative_deceased', 'cumulative_tested']

### - Streamlining data to include same dates

In [46]:
# For dataset 1
# Finding the first common observation date shared for all of the countries to make the comparison fair

filtered_focus_data1 = filtered_focus_data1.copy()

filtered_focus_data1['date'] = pd.to_datetime(filtered_focus_data1['date'].astype('string'), errors='coerce').dt.normalize()

min_dates_1 = filtered_focus_data1.groupby('location_key')['date'].min()
max_dates_1 = filtered_focus_data1.groupby('location_key')['date'].max()

first_common_1 = min_dates_1.max()
last_common_1 = max_dates_1.min()

print(f"First common date: {first_common_1}")
print(f"Last common date: {last_common_1}")

# Filtering the filtered_focus_data1 to only include this data interval
filtered_focus_data1_common = filtered_focus_data1[
    (filtered_focus_data1['date'] >= first_common_1) &
    (filtered_focus_data1['date'] <= last_common_1)
].copy()

print(f"filtered_focus_data1_common shape: {filtered_focus_data1_common.shape}")

# Investigate if some dates are missing for some countries. Print the dates and countries missing for the date interval

date_range = pd.date_range(start=first_common_1, end=last_common_1, freq='D')

missing_by_country_1 = {}
for country, group in filtered_focus_data1_common.groupby('location_key'):
    missing_dates = date_range.difference(pd.DatetimeIndex(group['date']))
    if len(missing_dates):
        missing_by_country_1[country] = missing_dates

if missing_by_country_1:
    print("\nMissing dates in filtered_focus_data1_common:")
    for country, missing_dates in missing_by_country_1.items():
        print(f"{country}: {len(missing_dates)} missing dates (first few: {missing_dates[:5].tolist()})")
else:
    print("\nNo missing dates found in filtered_focus_data1_common.")

First common date: 2020-01-02 00:00:00
Last common date: 2022-09-13 00:00:00
filtered_focus_data1_common shape: (224808, 10)

No missing dates found in filtered_focus_data1_common.

### - Saving the cleaned dataset

In [47]:
#Saving this filterede data for data 1 as a CSV file
output_path = current_dir.parent / 'data' / 'epidemiologi_global_covid_data.csv'
filtered_focus_data1_common.to_csv(output_path, index=False)
print(f"\nSaved merged dataset to: {output_path}")

filtered_focus_data1_common.head()

Saved merged dataset to: c:\Users\Lenovo\OneDrive - Danmarks Tekniske Universitet\02806 Social data analysis and visualization\final_project\data\epidemiologi_global_covid_data.csv

,date,location_key,new_confirmed,new_deceased,new_recovered,new_tested,cumulative_confirmed,cumulative_deceased,cumulative_recovered,cumulative_tested
1,2020-01-02,AD,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN
2,2020-01-03,AD,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN
3,2020-01-04,AD,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN
4,2020-01-05,AD,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN
5,2020-01-06,AD,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN

# Merged data (Dataset 1 and Dataset 2) 
### - Streamlining data to include same dates

In [ ]:
# Apply the convert_iso2_to_iso3 function to both datasets
focus_data1["location_key"] = focus_data1["location_key"].apply(convert_iso2_to_iso3)
focus_data2["location_key"] = focus_data2["location_key"].apply(convert_iso2_to_iso3)
focus_data3["location_key"] = focus_data3["location_key"].apply(convert_iso2_to_iso3)]

In [52]:
# Merge epidemiology and Oxford government response datasets on date + location_key
merged_data = focus_data1.merge(
    focus_data2,
    on=['date', 'location_key'],
    how='inner',
    validate='one_to_one'
)

print(f"focus_data1 shape: {focus_data1.shape}")
print(f"focus_data2 shape: {focus_data2.shape}")
print(f"Merged shape:      {merged_data.shape}")

focus_data1 shape: (226892, 10)
focus_data2 shape: (171200, 22)
Merged shape:      (170140, 30)

In [54]:
# Apply the function to merged_data
merged_data = remove_recovered_columns(merged_data)

In [55]:
merged_data

,date,location_key,new_confirmed,new_deceased,new_tested,cumulative_confirmed,cumulative_deceased,cumulative_tested,school_closing,workplace_closing,...,fiscal_measures,international_support,public_information_campaigns,testing_policy,contact_tracing,emergency_investment_in_healthcare,investment_in_vaccines,facial_coverings,vaccination_policy,stringency_index
0,2020-01-01,AND,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00
1,2020-01-02,AND,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00
2,2020-01-03,AND,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00
3,2020-01-04,AND,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00
4,2020-01-05,AND,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170135,2022-07-04,ZWE,0.0,0.0,NaN,255755.0,5558.0,NaN,1.0,1.0,...,NaN,NaN,2.0,3.0,1.0,NaN,0.0,3.0,5.0,42.59
170136,2022-07-05,ZWE,0.0,0.0,NaN,255755.0,5558.0,NaN,1.0,1.0,...,NaN,NaN,2.0,3.0,1.0,NaN,0.0,3.0,5.0,42.59
170137,2022-07-06,ZWE,136.0,4.0,NaN,255891.0,5562.0,NaN,1.0,1.0,...,NaN,NaN,2.0,3.0,1.0,NaN,0.0,3.0,5.0,42.59
170138,2022-07-07,ZWE,33.0,1.0,NaN,255924.0,5563.0,NaN,1.0,1.0,...,NaN,NaN,2.0,3.0,1.0,NaN,0.0,3.0,5.0,42.59
170139,2022-07-08,ZWE,15.0,1.0,NaN,255939.0,5564.0,NaN,1.0,1.0,...,NaN,NaN,2.0,3.0,1.0,NaN,0.0,3.0,5.0,42.59

In [56]:
# Number of days recorded for each country in merged data
merged_data_numberOfDays=merged_data['location_key'].value_counts()
merged_data_numberOfDays

location_key
AFG    938
AUS    938
CHL    938
HRV    938
MLT    938
      ...
CZE    881
HKG    693
COM    342
MAC    133
GRD     87
Name: count, Length: 186, dtype: int64

In [57]:
# Analyzing the distribution of the number of days recorded for each country in merged_data using boxplot statistics

def boxplot_stats(series):
    q1 = series.quantile(0.25)
    median = series.quantile(0.5)
    q3 = series.quantile(0.75)
    iqr = q3 - q1

    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr

    outliers = series[(series < lower_bound) | (series > upper_bound)]

    return {
        "min": series.min(),
        "Q1": q1,
        "median": median,
        "Q3": q3,
        "max": series.max(),
        "IQR": iqr,
        "lower_bound": lower_bound,
        "upper_bound": upper_bound,
        "num_outliers": len(outliers)
    }

# Apply to merged data
stats = boxplot_stats(merged_data_numberOfDays)

# Convert to DataFrame for clean display
summary = pd.DataFrame([stats], 
                       index=["Merged Data"])

print(summary)

# Using statistics to filter the data
# We will keep countries that have number of days recorded >= Q1 (first quartile)

# For merged data
q1 = stats['Q1']

# Filtering dataset to exclude data with observation numbers below Q1
filtered_countries = merged_data_numberOfDays[merged_data_numberOfDays >= q1].index.tolist()
filtered_merged_data = merged_data[merged_data['location_key'].isin(filtered_countries)]

print(f"Merged Data - Q1 threshold: {q1}")
print(f"Countries kept (>= Q1): {len(filtered_countries)}")
print(f"Filtered merged data shape: {filtered_merged_data.shape}")

             min     Q1  median     Q3  max   IQR  lower_bound  upper_bound  \
Merged Data   87  923.0   930.0  937.0  938  14.0        902.0        958.0

             num_outliers
Merged Data            11
Merged Data - Q1 threshold: 923.0
Countries kept (>= Q1): 141
Filtered merged data shape: (131480, 28)

In [58]:
# For merged dataset
# Finding the first common observation date shared for all of the countries to make the comparison fair

filtered_merged_data = filtered_merged_data.copy()

filtered_merged_data['date'] = pd.to_datetime(filtered_merged_data['date'].astype('string'), errors='coerce').dt.normalize()

min_dates_merged = filtered_merged_data.groupby('location_key')['date'].min()
max_dates_merged = filtered_merged_data.groupby('location_key')['date'].max()

first_common_merged = min_dates_merged.max()
last_common_merged = max_dates_merged.min()

print(f"First common date: {first_common_merged}")
print(f"Last common date: {last_common_merged}")

# Filtering the filtered_merged_data to only include this data interval
filtered_merged_data_common = filtered_merged_data[
    (filtered_merged_data['date'] >= first_common_merged) &
    (filtered_merged_data['date'] <= last_common_merged)
].copy()

print(f"filtered_merged_data_common shape: {filtered_merged_data_common.shape}")

# Investigate if some dates are missing for some countries. Print the dates and countries missing for the date interval

date_range = pd.date_range(start=first_common_merged, end=last_common_merged, freq='D')

missing_by_country_merged = {}
for country, group in filtered_merged_data_common.groupby('location_key'):
    missing_dates = date_range.difference(pd.DatetimeIndex(group['date']))
    if len(missing_dates):
        missing_by_country_merged[country] = missing_dates

if missing_by_country_merged:
    print("\nMissing dates in filtered_merged_data_common:")
    for country, missing_dates in missing_by_country_merged.items():
        print(f"{country}: {len(missing_dates)} missing dates (first few: {missing_dates[:5].tolist()})")
else:
    print("\nNo missing dates found in filtered_merged_data_common.")

First common date: 2020-01-02 00:00:00
Last common date: 2022-07-11 00:00:00
filtered_merged_data_common shape: (130001, 28)

Missing dates in filtered_merged_data_common:
NGA: 1 missing dates (first few: [Timestamp('2022-07-11 00:00:00')])

### - Adding vaccination data

In [59]:
def merge_vaccination_data(main_df, vaccination_df):
    """
    Merge vaccination data into a COVID analysis dataframe
    on date and location_key.
    """
    vax_data = vaccination_df.copy()

    vax_data['date'] = pd.to_datetime(
        vax_data['date'],
        errors='coerce'
    ).dt.normalize()

    merged_with_vax = main_df.merge(
        vax_data,
        on=['date', 'location_key'],
        how='left',
        validate='many_to_one'
    )

    return merged_data

### - Checking for potentially missing data

In [60]:
# Check that each country has at least one entity value for every data column in filtered_merged_data_common.
# This helps verify that each country doesn't have systematic missingness.

def check_country_column_non_missing(df, country_col='location_key', threshold=1):
    """Return non-missing counts, missing-category flags, and a summary per country."""
    # Count non-missing entries per country and column
    non_missing_counts = df.groupby(country_col).apply(lambda group: group.notna().sum())
    if country_col in non_missing_counts.columns:
        non_missing_counts = non_missing_counts.drop(columns=[country_col])

    # Identify columns where the count of non-missing values is below the threshold
    missing_flags = (non_missing_counts < threshold)
    missing_matrix = missing_flags.astype(object)
    missing_matrix[missing_flags] = 'Non'
    missing_matrix[~missing_flags] = ''

    # Build a summary table and list missing categories for each country
    missing_categories = {
        country: non_missing_counts.columns[missing_flags.loc[country]].tolist()
        for country in non_missing_counts.index
    }

    summary = pd.DataFrame({
        'has_minimum_per_column': [len(categories) == 0 for categories in missing_categories.values()],
        'missing_columns': [', '.join(categories) if categories else '' for categories in missing_categories.values()]
    }, index=non_missing_counts.index)

    return non_missing_counts, missing_flags, missing_matrix, summary, missing_categories

# Run the check on filtered_merged_data_common
non_missing_counts, missing_flags, missing_matrix, country_summary, missing_categories = check_country_column_non_missing(merged_data)

print("\nSummary of missing data per category:")
missing_per_category = (missing_matrix == 'Non').sum()
print(missing_per_category)

if country_summary['has_minimum_per_column'].all():
    print("\nAll countries have at least one non-missing value in every column.")
else:
    print("\nCountries with missing entities in one or more categories:")
    for country, categories in missing_categories.items():
        if categories:
            print(f"- {country}: missing data in {', '.join(categories)}")

Summary of missing data per category:
date                                   0
new_confirmed                          0
new_deceased                           0
new_tested                            48
cumulative_confirmed                   0
cumulative_deceased                    0
cumulative_tested                     23
school_closing                         1
workplace_closing                      1
cancel_public_events                   1
restrictions_on_gatherings             1
public_transport_closing               1
stay_at_home_requirements              1
restrictions_on_internal_movement      1
international_travel_controls          1
income_support                         1
debt_relief                            1
fiscal_measures                        2
international_support                  2
public_information_campaigns           1
testing_policy                         1
contact_tracing                        1
emergency_investment_in_healthcare     2
investment_in_vaccines                 1
facial_coverings                       0
vaccination_policy                     0
stringency_index                       1
dtype: int64

Countries with missing entities in one or more categories:
- AFG: missing data in new_tested
- AND: missing data in new_tested
- BEN: missing data in new_tested
- CAF: missing data in new_tested
- CHN: missing data in new_tested
- CMR: missing data in new_tested
- COD: missing data in new_tested
- COG: missing data in new_tested
- COM: missing data in new_tested, cumulative_tested, school_closing, workplace_closing, cancel_public_events, restrictions_on_gatherings, public_transport_closing, stay_at_home_requirements, restrictions_on_internal_movement, international_travel_controls, income_support, debt_relief, fiscal_measures, international_support, public_information_campaigns, testing_policy, contact_tracing, emergency_investment_in_healthcare, investment_in_vaccines, stringency_index
- CPV: missing data in cumulative_tested
- DEU: missing data in new_tested
- DZA: missing data in new_tested
- EGY: missing data in new_tested
- ERI: missing data in new_tested
- ESP: missing data in new_tested, cumulative_tested
- GIN: missing data in new_tested
- GMB: missing data in new_tested
- GRD: missing data in new_tested, cumulative_tested, fiscal_measures, international_support, emergency_investment_in_healthcare
- GRL: missing data in new_tested, cumulative_tested
- GUY: missing data in new_tested
- HKG: missing data in new_tested
- HND: missing data in new_tested, cumulative_tested
- KGZ: missing data in new_tested, cumulative_tested
- KIR: missing data in new_tested, cumulative_tested
- LBR: missing data in new_tested
- LBY: missing data in cumulative_tested
- MAC: missing data in new_tested, cumulative_tested
- MCO: missing data in new_tested, cumulative_tested
- MDA: missing data in cumulative_tested
- MUS: missing data in new_tested
- NIC: missing data in new_tested
- OMN: missing data in new_tested
- PER: missing data in new_tested
- PNG: missing data in new_tested
- PSE: missing data in cumulative_tested
- ROU: missing data in new_tested
- SDN: missing data in new_tested
- SGP: missing data in cumulative_tested
- SLB: missing data in new_tested, cumulative_tested
- SMR: missing data in new_tested, cumulative_tested
- SOM: missing data in new_tested
- SYC: missing data in new_tested, cumulative_tested
- SYR: missing data in new_tested
- TCD: missing data in new_tested
- TJK: missing data in new_tested, cumulative_tested
- TKM: missing data in new_tested, cumulative_tested
- TON: missing data in new_tested, cumulative_tested
- TZA: missing data in new_tested
- UZB: missing data in new_tested, cumulative_tested
- VEN: missing data in new_tested, cumulative_tested
- VUT: missing data in new_tested
- XK: missing data in new_tested, cumulative_tested
- YEM: missing data in new_tested

### - Adding vaccination data

### - Saving the cleaned datasets

In [ ]:
# Save to CSV
output_path = current_dir.parent / 'data' / 'merged_covid_data.csv'
merged_data.to_csv(output_path, index=False)
print(f"\nSaved merged dataset to: {output_path}")

merged_data.head()

Saved merged dataset to: c:\Users\Lenovo\OneDrive - Danmarks Tekniske Universitet\02806 Social data analysis and visualization\final_project\data\merged_covid_data.csv

,date,location_key,new_confirmed,new_deceased,new_recovered,new_tested,cumulative_confirmed,cumulative_deceased,cumulative_recovered,cumulative_tested,...,fiscal_measures,international_support,public_information_campaigns,testing_policy,contact_tracing,emergency_investment_in_healthcare,investment_in_vaccines,facial_coverings,vaccination_policy,stringency_index
0,2020-01-01,AND,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2020-01-02,AND,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2020-01-03,AND,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2020-01-04,AND,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2020-01-05,AND,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0